src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Obligation_Date__c</fullName>
        <label>Financial Obligation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Key_Handover_Date__c</fullName>
        <label>Key Handover Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Move_Out_Date__c</fullName>
        <description>Captured on the case termination record type</description>
        <label>Move Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <description>To indicate when a Contract Linked to this case will Terminate</description>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Termination_Reason_new__c</fullName>
        <label>Termination Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Downsizing</fullName>
                </value>
                <value>
                    <fullName>Lease Cancellation</fullName>
                </value>
                <value>
                    <fullName>Lease Merger</fullName>
                </value>
                <value>
                    <fullName>Relocation Contraction</fullName>
                </value>
                <value>
                    <fullName>Relocation expansion</fullName>
                </value>
                <value>
                    <fullName>Area Amendment</fullName>
                </value>
                <value>
                    <fullName>Rent Reduction</fullName>
                </value>
                <value>
                    <fullName>Splitting</fullName>
                </value>
                <value>
                    <fullName>Changing: The name/Activity/FZ-LLC/Branch/Shareholders</fullName>
                </value>
                <value>
                    <fullName>Lease termination for DED tenant</fullName>
                </value>
                <value>
                    <fullName>Relocation due to TECOM request.(without financial impact)</fullName>
                </value>
                <value>
                    <fullName>Calculation Only</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Financial Challenges</fullName>
                    <isActive>false</isActive>
                    <label>Financial Challenges</label>
                </value>
                <value>
                    <fullName>High Rent</fullName>
                    <isActive>false</isActive>
                    <label>High Rent</label>
                </value>
                <value>
                    <fullName>Moving to other free zone in UAE</fullName>
                    <isActive>false</isActive>
                    <label>Moving to other free zone in UAE</label>
                </value>
                <value>
                    <fullName>Repossession</fullName>
                    <isActive>false</isActive>
                    <label>Repossession</label>
                </value>
                <value>
                    <fullName>Unsatisfied service</fullName>
                    <isActive>false</isActive>
                    <label>Unsatisfied service</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Orders_In_Progress__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Work Orders In Progress</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Lease_Termination</fullName>
        <active>true</active>
        <businessProcess>Termination Process</businessProcess>
        <description>To be used when a termination has been initiated on an active lease contract</description>
        <label>Lease Termination</label>
    </recordTypes>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <businessProcess>Application Form</businessProcess>
        <description>To create a Case for Land On-Boarding</description>
        <label>Land On-Boarding</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Encrypted_Contact_Id__c</fullName>
        <description>Encrypted contact id which will be sent to contact email for broker registration.</description>
        <externalId>true</externalId>
        <label>Encrypted Contact Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Billing_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Billing Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Registration_Page_Indicator__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Custom field to track the completed section of application for customer registration.</description>
        <label>Registration Page Indicator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Security__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Security Clearance?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TerminationIntegrationTest.cls
/*
 *  Class: TerminationIntegrationTest
 *  Created by : Raza khan (raza.khan@wear4c.com)
 *  Description: This class is for covering the test cases of integration for termination requests.
 * 
 * 
 * */

@istest
public class TerminationIntegrationTest {
    
    
    @TestSetup
    private static void setupData()
    {
        PricingUtilsTest.createData();
        
        Id accId = [select id from Account where name = 'Test Company' limit 1].id;
        List<RecordType> recrordType = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType where SobjectType ='Case'];
        Map<String, Id> recordTypeMap = new Map<String, Id>();
        for(RecordType rec : recrordType)
        {
            recordTypeMap.put(rec.DeveloperName, rec.id);
        }
        //'Lease_Termination'
        Quote q = [select id, OpportunityId from Quote where name='Test Quote' limit 1];
        
        Contact sobj = new Contact(
            AccountId = accId,                                                                // Account Name
            Email = 'oeafefe@web.de',                                                                          // Email
            Phone = '223424234',                                                                               // Phone
            MobilePhone = '(824) 543-5345',                                                                    // Mobile
            CurrencyIsoCode = 'AED',                                                              // Contact Currency
            Encrypted_Contact_Id__c = 'knA4xzSqpPeaE7dFajzaCuz2eVJ6rn%2FKESjtD4%2FJM8IQ4QsP6Kj3I114VnlbU1bI',  // Encrypted Contact Id
            Registration_Page_Indicator__c = 1,                                                              // Registration Page Indicator
           // Security__c = false,                                                                               // Security Clearance?
            Is_Billing_Contact__c = true,                                                                      // Is Billing Contact
            Is_Active__c = true  ,																				// Is Active
			Lastname = 'test'
        );
        insert sobj;
        
        
        Contract contr = new Contract(
            accountId = accId,
            Status = 'Draft',   // Status
            StartDate = system.today().addDays(-30),  // Contract Start Date
            Contact__c = sobj.id,      // Contact
            ContractTerm = 12,                    // Contract Term (months)
            Opportunity__c = q.OpportunityId,  // Opportunity
            Quote__c = q.id        // Quote
        );
        insert contr;
        
        Case cas = new Case(
            recordtypeId = recordTypeMap.get('Lease_Termination'),
            Status = 'New',                     // Status
            Priority = 'Medium',                               // Priority
            Work_Orders_In_Progress__c = false,                // Work Orders In Progress
            Type = 'Termination',                              // Type
            Contract__c = contr.Id,                // Contract
            Quote__c = q.id,                   // Quote
            ContactId = sobj.id,                  // Contact Name
            Termination_Date__c = system.today().addDays(-10),    // Termination Date
            Move_Out_Date__c = system.today().addDays(30),       // Move Out Date
            Termination_Reason_new__c = 'Lease Cancellation',  // Termination Reason
            Key_Handover_Date__c = system.today().addDays(50), // Key Handover Date
            Financial_Obligation_Date__c = system.today()
        );
        insert cas;
         Case assignmentCase = new Case(
            recordtypeId = recordTypeMap.get('Lease_Termination'),
            Status = 'New',                     // Status
            Priority = 'Medium',                               // Priority
            Work_Orders_In_Progress__c = false,                // Work Orders In Progress
            Type = 'Termination',                              // Type
            Contract__c = contr.Id,                // Contract
            Quote__c = q.id,                   // Quote
            ContactId = sobj.id,                  // Contact Name
            Termination_Date__c = system.today().addDays(-10),    // Termination Date
            Move_Out_Date__c = system.today().addDays(30),       // Move Out Date
            Termination_Reason_new__c = 'Lease Cancellation',  // Termination Reason
            Key_Handover_Date__c = system.today().addDays(50), // Key Handover Date
            Financial_Obligation_Date__c = system.today()
        );
        insert assignmentCase;
        
        
    }
    
    @istest
    private static void testTeremination()
    {
        String responseStr = '{"YardiIntegrationStatus":"Success","YardiIntegrationErrorMessage":"","OpportunityTCode":"123456","OpportunityAmendmentId":1234,"outstandingPayments":[{"description":"testing","chargeCode":"123","vatAmount":1234,"billedAmount":123,"chargeFrom":"2020-01-01","chargeTo":"2020-05-01","opportunityId":""}]}';
        Test.setMock(HttpCalloutMock.class, new NewRenewLeaseMockResponse(responseStr));
        List<Case> updatecase = [Select id, status from case where type ='Termination' ];
        test.startTest();
        updatecase[0].status = 'Brand Sales Approved';
        update updatecase;
        test.stopTest();
    }
    
    @istest
    private static void testAssignment()
    {
        String responseStr = '{"YardiIntegrationStatus":"Success","YardiIntegrationErrorMessage":"","OpportunityTCode":"123456","OpportunityAmendmentId":1234,"outstandingPayments":[{"description":"testing","chargeCode":"123","vatAmount":1234,"billedAmount":123,"chargeFrom":"2020-01-01","chargeTo":"2020-05-01","opportunityId":""}]}';
        Test.setMock(HttpCalloutMock.class, new NewRenewLeaseMockResponse(responseStr));
        List<Case> updatecase = [Select id, status from case where type ='Termination' ];
        test.startTest();
        updatecase[0].status = 'Brand Sales Approved';
        update updatecase;
        test.stopTest();
    }
    
    
}