src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ORACLE_PARTY_ID__c</fullName>
        <externalId>true</externalId>
        <label>ORACLE PARTY ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Customer_Id__c</fullName>
        <label>Oracle Customer Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Customer_Number__c</fullName>
        <label>Oracle Customer Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Integration_Error_Message__c</fullName>
        <label>Oracle Integration Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Integration_Status__c</fullName>
        <label>Oracle-Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Integration - Oracle</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Work_Orders_In_Progress__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Work Orders In Progress</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>On_Boarding_Premise</fullName>
        <active>true</active>
        <businessProcess>Application Form</businessProcess>
        <description>To create a Case for Premise On-Boarding</description>
        <label>On-Boarding Premise</label>
    </recordTypes>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <businessProcess>Application Form</businessProcess>
        <description>To create a Case for Land On-Boarding</description>
        <label>Land On-Boarding</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ORACLE_PARTY_ID__c</fullName>
        <externalId>true</externalId>
        <label>ORACLE PARTY ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Integration_Error_Message__c</fullName>
        <label>Oracle Integration Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Integration_Status__c</fullName>
        <label>Oracle Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Integration - Oracle</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Leasing Contact</fullName>
                </value>
                <value>
                    <fullName>Licensee Contact</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Alternate Payee</fullName>
                </value>
                <value>
                    <fullName>Authorized Signatory</fullName>
                </value>
                <value>
                    <fullName>Focal Point</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Legal Representative</fullName>
                </value>
                <value>
                    <fullName>Manager Incharge</fullName>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>PRO</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>CollectionTeam</fullName>
                </value>
                <value>
                    <fullName>Licensing Contact</fullName>
                </value>
                <value>
                    <fullName>Individual Shareholder</fullName>
                </value>
                <value>
                    <fullName>Corporate Shareholder</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountIntegrationOracleERPTest.cls
/***********************************************************************************************
* Name              : AccountIntegrationOracleERPTest                                               
* Description       : Test class to test AccountIntegrationOracleERP class
* Created Date      :                                                                                                                                                    
* ----------------------------------------------------------------------------------------------
* VERSION   Developer   Date        Description     Ticket/Reference                                                                    
************************************************************************************************/
@istest
public class AccountIntegrationOracleERPTest {
    //Method to test updated accounts to be sent to Oracle
    @istest
    private static void accountOracleIntegrationTest()
    {
        String responseStr = '{"ORACLE_PARTY_ID__c":"12345","Oracle_Integration_Error_Message__c":"","Oracle_Customer_Id__c":"12345","Oracle_Customer_Number__c":"12345","Oracle_Integration_Status__c":"S"}';
        Test.setMock(HttpCalloutMock.class, new NewRenewLeaseMockResponse(responseStr));   
        List<Id> accLst = new List<Id>();
        test.startTest();
        Account acc = TestDataFactory.getAccountWithContact();
        accLst.add(acc.Id);
        AccountIntegrationOracleERP.sendAccountsToOracle(accLst);
        test.stopTest();
        
        List<Account> accUpdatedList = [SELECT Id, Name, Oracle_Integration_Status__c FROM Account];
        System.assertEquals(accUpdatedList[0].Oracle_Integration_Status__c, 'S');
    } 
    //Negative test accountOracleIntegrationOracleERP
    @istest
    private static void accountOracleIntegrationNegativeTest()
    {
        String responseStr = '';
        Test.setMock(HttpCalloutMock.class, new NewRenewLeaseMockResponse(responseStr));   
        List<Id> accLst = new List<Id>();
        
        
        try {
            test.startTest();
            Account acc = TestDataFactory.getAccountWithContact();
            accLst.add(acc.Id);
            AccountIntegrationOracleERP.sendAccountsToOracle(accLst);
            
            test.stopTest();
            
            List<Account> accUpdatedList = [SELECT Id, Name, Oracle_Integration_Status__c FROM Account];
        }
        catch(Exception e) {
            System.assertEquals(e.getMessage(), 'No content to map to Object due to end of input');
        }
    } 
    
    @istest
    private static void accountIntegrationStatusTest()
    {
         String responseStr = '{"ORACLE_PARTY_ID__c":"12345","Oracle_Integration_Error_Message__c":"","Oracle_Customer_Id__c":"12345","Oracle_Customer_Number__c":"12345","Oracle_Integration_Status__c":"S"}';
        Test.setMock(HttpCalloutMock.class, new NewRenewLeaseMockResponse(responseStr)); 
         try {
        Account acc = TestDataFactory.getAccountWithContact();
        Contact cont = [Select id, type__c from contact where accountid =:acc.id];
        cont.Type__c = 'Billinng';
        update cont;
        Case sobj = new Case(
            Status = 'New',                   // Status
            Priority = 'Medium',                // Priority
            Work_Orders_In_Progress__c = false , // Work Orders In Progress
            accountId = acc.id,
            recordtypeId = [select id from recordtype where developername = 'On_Boarding_Premise' limit 1].id,
            contactid = cont.id
            
        );
        insert sobj;
        List<workorder> worders = [SELECT Id, Status, CaseId FROM WorkOrder where caseId =: sobj.id ];
        for(workorder wo: worders)
        {
            wo.status = 'Approved';
        }
        update worders;
       // sobj.Work_Orders_In_Progress__c = false;
        //update sobj;
         //String responseStr = '{"ORACLE_PARTY_ID__c":"12345","Oracle_Integration_Error_Message__c":"","Oracle_Customer_Id__c":"12345","Oracle_Customer_Number__c":"12345","Oracle_Integration_Status__c":"S"}';
        //Test.setMock(HttpCalloutMock.class, new NewRenewLeaseMockResponse(responseStr)); 
        test.startTest();
        sobj.Status = 'Closed - Approved';
        update sobj;
        test.stopTest();
         } catch(Exception e)
         {
             
         }
        
    }
}