src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Plan_Request_Date_Approval_Date__c</fullName>
        <label>Business Plan Request Date-Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Framework__c</fullName>
        <label>Legal Framework</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Branch of a Foreign Company</fullName>
                </value>
                <value>
                    <fullName>Branch of a UAE Company</fullName>
                </value>
                <value>
                    <fullName>Branch of a UAE Establishment</fullName>
                </value>
                <value>
                    <fullName>Freelancer</fullName>
                </value>
                <value>
                    <fullName>Free Zone Limited Liability company</fullName>
                </value>
                <value>
                    <fullName>Limited Liability company</fullName>
                </value>
                <value>
                    <fullName>Decree Company</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <isActive>false</isActive>
                    <label>NA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Security_Clearance_Date__c</fullName>
        <label>Security Clearance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Security_Clearance_Status__c</fullName>
        <label>Security Clearance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ParentCon__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ParentCon</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Security_Clearance_Date__c</fullName>
        <label>Security Clearance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Security_Clearance_Status__c</fullName>
        <label>Security Clearance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Leasing Contact</fullName>
                </value>
                <value>
                    <fullName>Licensee Contact</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Alternate Payee</fullName>
                </value>
                <value>
                    <fullName>Authorized Signatory</fullName>
                </value>
                <value>
                    <fullName>Focal Point</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Legal Representative</fullName>
                </value>
                <value>
                    <fullName>Manager Incharge</fullName>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>PRO</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>CollectionTeam</fullName>
                </value>
                <value>
                    <fullName>Licensing Contact</fullName>
                </value>
                <value>
                    <fullName>Individual Shareholder</fullName>
                </value>
                <value>
                    <fullName>Corporate Shareholder</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isSubmit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isSubmit</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Activity_Logged_Time__c</fullName>
        <label>Activity Logged Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Company</fullName>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <businessProcess>Land%2FLease</businessProcess>
        <label>Company</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/EmailMessageTriggerHandlerTest.cls
/**
 *  @description Test class for WorkOrderToolbarHandler
 *
 *  2019-08-19  Shraddha N    First version
 *  
 */

@isTest
public class EmailMessageTriggerHandlerTest {
	
    //Common test data to be used in test class
    @testSetup
    //@isTest
    public static void setUp(){
       
        //EmailMessageMock fakeResponse = new EmailMessageMock(200, 'Complete', '{"body" : [{"FromName": "sForceTest1"}]}', null);
      	//Test.setMock(HttpCalloutMock.class, fakeResponse); //HttpCalloutMock
        
        Account accountObject = new Account(Name = 'Test',Phone='1111111', Legal_Framework__c = 'Branch of a Foreign Company', Security_Clearance_Date__c = Date.today(), Security_Clearance_Status__c = 'NA', Business_Plan_Request_Date_Approval_Date__c = Date.today());
        insert accountObject;
        
        Contact contactObject = new Contact(LastName = 'Test',Email = 'test.mail@test.com', isSubmit__c = true, ParentCon__c = true, AccountId= accountObject.Id ,Type__c = 'Billing;Leasing Contact;Licensee Contact;Manager Incharge');
        insert contactObject;
        
        Case caseObject = new Case(Status = 'New', ContactId = contactObject.Id);
        insert caseObject;
        
		Lead leadObject = new Lead(LastName = 'Test',Activity_Logged_Time__c = System.today().addDays(2));
		insert leadObject;       
        
        Case caseObj = [SELECT ContactEmail FROM Case WHERE ContactId = :contactObject.Id LIMIT 1];
        
        EmailMessage emailMessageObject = new EmailMessage(ToAddress = caseObj.ContactEmail,
                                                           FromAddress = 'testemail@test.com',
                                                           FromName = 'Test',
                                                           HtmlBody = 'Test Email Message Body',
                                                           MessageDate = System.today(),
                                                           Incoming = FALSE,
                                                           Status = '0',
                                                           ParentId = caseObject.Id);
        insert emailMessageObject;
       
        List<EmailMessage> getEmailMessageObject = [SELECT Id, ActivityId, Incoming, ToAddress FROM EmailMessage LIMIT 1] ;

        Task taskObject = [SELECT Id FROM Task WHERE Id = :getEmailMessageObject[0].ActivityId];
        taskObject.WhatId = null;
        taskObject.WhoId = leadObject.Id;
        update taskObject;
        
        //EmailMessage getEmailMessageObject = [SELECT Id, ActivityId, Incoming, ToAddress FROM EmailMessage LIMIT 1] ;
        
    }
    
   //method to test afterInsert
    @isTest
    public static void afterInsertTest(){
        
        List<EmailMessage> emailMessageList = [SELECT Id, ActivityId, Incoming, ToAddress FROM EmailMessage WHERE Incoming = FALSE];
        
        Test.startTest();
        	EmailMessageTriggerHandler.afterInsert(emailMessageList);
        Test.stopTest();
        Lead leadObject1 = [SELECT Activity_Logged_Time__c FROM Lead WHERE LastName = 'Test' LIMIT 1];
        //System.assertEquals(errorMessage, '');
        System.assertEquals(leadObject1.Activity_Logged_Time__c,DateTime.now() );
    }
  
}