src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ORACLE_PARTY_ID__c</fullName>
        <externalId>true</externalId>
        <label>ORACLE PARTY ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Integration_Status__c</fullName>
        <label>Oracle-Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Integration - Oracle</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Yardi_Account_Id__c</fullName>
        <externalId>true</externalId>
        <label>Yardi Account Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Yardi_Integration_Status__c</fullName>
        <label>Yardi Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Integration - Yardi</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
                <value>
                    <fullName>Synced</fullName>
                    <isActive>false</isActive>
                    <label>Synced</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Yardi_Integration_Status__c</fullName>
        <label>Yardi Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Integration</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ORACLE_PARTY_ID__c</fullName>
        <externalId>true</externalId>
        <label>ORACLE PARTY ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Integration_Status__c</fullName>
        <label>Oracle Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Integration - Oracle</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Leasing Contact</fullName>
                </value>
                <value>
                    <fullName>Licensee Contact</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Alternate Payee</fullName>
                </value>
                <value>
                    <fullName>Authorized Signatory</fullName>
                </value>
                <value>
                    <fullName>Focal Point</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Legal Representative</fullName>
                </value>
                <value>
                    <fullName>Manager Incharge</fullName>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>PRO</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>CollectionTeam</fullName>
                </value>
                <value>
                    <fullName>Licensing Contact</fullName>
                </value>
                <value>
                    <fullName>Individual Shareholder</fullName>
                </value>
                <value>
                    <fullName>Corporate Shareholder</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Yardi_Integration_Status__c</fullName>
        <label>Yardi Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Integration - Yardi</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountIntegrationUtil.cls
/*
* Created By : Raza Khan (raza.khan@weare4c.com)
* Dated:       28-07-2019
* Description: This is the util class for calling the account integrations api
*              for oracle and yardi integrations.
* 
* 
* 
* */

public class AccountIntegrationUtil {
    
    Public static map<Id,String> caseRecordTypes{
        get{
            if(caseRecordTypes == null)
            {
                caseRecordTypes = new Map<Id,String>();
                for(RecordTypeInfo rec: Schema.SObjectType.Case.getRecordTypeInfosByName().values())
                {
                    caseRecordTypes.put(rec.getRecordTypeId(), rec.getName());
                }
                
            }
            return caseRecordTypes;
        } set;
    }
    
    public static void updateAccountStatusYardiIntegration(List<Case> newCases, Map<Id, Case> oldmap)
    {
        List<Id> accountIds = new List<Id>();
        System.debug('caseRecordTypes ===='+caseRecordTypes);
        for(Case c: newCases)
        {
            System.debug('caseRecordTypes values==== '+caseRecordTypes.get(c.recordTypeId));
            if(c.status != oldmap.get(c.id).status && c.status == 'Closed - Approved' &&
               (caseRecordTypes.get(c.recordTypeId) == 'On-Boarding Premise' || caseRecordTypes.get(c.RecordTypeId) == 'Land On-Boarding'))
            {
                accountIds.add(c.AccountId);
            }
        }
        if(!accountIds.isempty())
        {
            updateAccountStatusYardi(accountIds);
        }
    }
    
    public static void updateContactStatusYardiIntegration(List<Account> newAccounts, Map<Id, Account> oldMap)
    {
        List<Id> accountIds = new List<Id>();
        
        for(Account a: newAccounts)
        {
            if(a.Yardi_Account_Id__c != oldmap.get(a.id).Yardi_Account_Id__c  && a.Yardi_Account_Id__c  != null)
            {
                accountIds.add(a.id);
            }
        }
        if(!accountIds.isempty())
        {
            List<Contact> contacts = [Select id, Yardi_Integration_Status__c  from contact where accountId in: accountIds
                                      And Type__c  includes('Leasing Contact','Billing', 'Licensing Contact') ];
            for(Contact c: contacts)
            {
                c.Yardi_Integration_Status__c = 'Ready for Integration - Yardi';
                
            }
            if(contacts != null)
            {
                update contacts;
            }
        }
    }
    
    public static void updateContactStatusOracleIntegration(List<Account> newAccounts, Map<Id, Account> oldMap)
    {
        List<Id> accountIds = new List<Id>();
        
        for(Account a: newAccounts)
        {
            if(a.ORACLE_PARTY_ID__c  != oldmap.get(a.id).ORACLE_PARTY_ID__c   && a.ORACLE_PARTY_ID__c != null)
            {
                accountIds.add(a.id);
            }
        }
        if(!accountIds.isempty())
        {
            List<Contact> contacts = [Select id, Oracle_Integration_Status__c   from contact where accountId in: accountIds
                                      And Type__c  includes('Leasing Contact','Billing', 'Licensing Contact') ];
            for(Contact c: contacts)
            {
                c.Oracle_Integration_Status__c  = 'Ready for Integration - Oracle';
                
            }
            if(contacts != null)
            {
                update contacts;
            }
        }
    }
    
    
    public static void updateAccountStatusYardi(List<Id> accountIds)
    {
        List<Account> accounts = [Select id, Yardi_Integration_Status__c  from Account where Id in:accountIds ];
        for(Account a: accounts)
        {
            a.Yardi_Integration_Status__c = 'Ready for Integration - Yardi';
        }
        update accounts;
    }
    
    
    public static void sendAccountsToOracle(List<Account> newAcoounts)
    {
        List<Id> accountIds = new List<Id>();
        
        for(Account a: newAcoounts)
        {
            accountIds.add(a.Id);
        }
        if(!accountIds.isempty())
        {
            AccountIntegrationOracleERP.sendAccountsToOracle(accountIds);
        }
        
    }
}