src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reseller</fullName>
                </value>
                <value>
                    <fullName>Art</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Fashion</fullName>
                </value>
                <value>
                    <fullName>Luxury</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Brand</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Kiosk</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Analyst</fullName>
                    <isActive>false</isActive>
                    <label>Analyst</label>
                </value>
                <value>
                    <fullName>Broker</fullName>
                    <isActive>false</isActive>
                    <label>Broker</label>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                    <isActive>false</isActive>
                    <label>Business Partner</label>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                    <isActive>false</isActive>
                    <label>Competitor</label>
                </value>
                <value>
                    <fullName>Customer</fullName>
                    <isActive>false</isActive>
                    <label>Customer</label>
                </value>
                <value>
                    <fullName>Integrator</fullName>
                    <isActive>false</isActive>
                    <label>Integrator</label>
                </value>
                <value>
                    <fullName>Investor</fullName>
                    <isActive>false</isActive>
                    <label>Investor</label>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <isActive>false</isActive>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>Partner</fullName>
                    <isActive>false</isActive>
                    <label>Partner</label>
                </value>
                <value>
                    <fullName>Press</fullName>
                    <isActive>false</isActive>
                    <label>Press</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Plan_Request_Date_Approval_Date__c</fullName>
        <label>Business Plan Request Date-Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Framework__c</fullName>
        <label>Legal Framework</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Branch of a Foreign Company</fullName>
                </value>
                <value>
                    <fullName>Branch of a UAE Company</fullName>
                </value>
                <value>
                    <fullName>Branch of a UAE Establishment</fullName>
                </value>
                <value>
                    <fullName>Freelancer</fullName>
                </value>
                <value>
                    <fullName>Free Zone Limited Liability company</fullName>
                </value>
                <value>
                    <fullName>Limited Liability company</fullName>
                </value>
                <value>
                    <fullName>Decree Company</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <isActive>false</isActive>
                    <label>NA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Security_Clearance_Date__c</fullName>
        <label>Security Clearance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Security_Clearance_Status__c</fullName>
        <label>Security Clearance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ParentCon__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ParentCon</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Security_Clearance_Date__c</fullName>
        <label>Security Clearance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Security_Clearance_Status__c</fullName>
        <label>Security Clearance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Leasing Contact</fullName>
                </value>
                <value>
                    <fullName>Licensee Contact</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Alternate Payee</fullName>
                </value>
                <value>
                    <fullName>Authorized Signatory</fullName>
                </value>
                <value>
                    <fullName>Focal Point</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Legal Representative</fullName>
                </value>
                <value>
                    <fullName>Manager Incharge</fullName>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>PRO</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>CollectionTeam</fullName>
                </value>
                <value>
                    <fullName>Licensing Contact</fullName>
                </value>
                <value>
                    <fullName>Individual Shareholder</fullName>
                </value>
                <value>
                    <fullName>Corporate Shareholder</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isSubmit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isSubmit</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bank Account</fullName>
                    <default>true</default>
                    <label>Bank Account</label>
                </value>
                <value>
                    <fullName>Trust Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsMovedToNextStep__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Moved To Next Step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal_Framework__c</fullName>
        <formula>TEXT(Account.Legal_Framework__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Legal Framework</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minimum_Required_Share_Capital__c</fullName>
        <label>Minimum Required Share Capital</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Skip_Lease_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Skip Lease Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work_Order_Number__c</fullName>
        <label>Work Order Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DDAIntegrationServiceRequestMock.cls
@isTest
global class DDAIntegrationServiceRequestMock implements HttpCalloutMock {
    //WorkOrder data
    @isTest
    global static Id workOrderSetUp(){
        Case caseObject = new Case(Status = 'New');
        insert caseObject;
        Account accountObject = new Account(Name = 'Test',Phone='1111111', Legal_Framework__c = 'Branch of a Foreign Company', Security_Clearance_Date__c = Date.today(), Security_Clearance_Status__c = 'NA', Business_Plan_Request_Date_Approval_Date__c = Date.today());
        insert accountObject;
        Contact contactObject = new Contact(LastName = 'Test',Email = 'test.mail@test.com', isSubmit__c = true, ParentCon__c = true, AccountId= accountObject.Id ,Type__c = 'Billing;Leasing Contact;Licensee Contact;Manager Incharge');
        insert contactObject;
        WorkOrder workOrderObject = new WorkOrder(Status = 'New', 
                                     Description = 'test Description', 
                                     AccountId = accountObject.Id, 
                                     CaseId = caseObject.Id, 
                                     Skip_Lease_Validation__c = true, 
                                     Work_Order_Number__c = 1, 
                                     Account_Type__c = 'Trust Account', 
                                     Minimum_Required_Share_Capital__c = 10000,
                                     IsMovedToNextStep__c = true);
        insert workOrderObject; 
        return workOrderObject.Id;
    }
	// Implement this interface method
    global HTTPResponse respond(HTTPRequest req) {
        Id workOrderId = workOrderSetUp();
       
        // Create a fake response
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type', 'application/json');
        res.setBody('{"CreateNewServiceRequestResponse" : {"result" : [ {"errorMessage" : "","externalOLIID" : "","isSuccess" : "true", "oraclePartyId" : "","serviceRequestId" : "", "workOrderId" :"'+ workOrderId +'" ,"requestName":"test","requestId":""} ]}}');
        res.setStatusCode(200);
        return res;
    }
}