src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reseller</fullName>
                </value>
                <value>
                    <fullName>Art</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Fashion</fullName>
                </value>
                <value>
                    <fullName>Luxury</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Brand</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Kiosk</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Analyst</fullName>
                    <isActive>false</isActive>
                    <label>Analyst</label>
                </value>
                <value>
                    <fullName>Broker</fullName>
                    <isActive>false</isActive>
                    <label>Broker</label>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                    <isActive>false</isActive>
                    <label>Business Partner</label>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                    <isActive>false</isActive>
                    <label>Competitor</label>
                </value>
                <value>
                    <fullName>Customer</fullName>
                    <isActive>false</isActive>
                    <label>Customer</label>
                </value>
                <value>
                    <fullName>Integrator</fullName>
                    <isActive>false</isActive>
                    <label>Integrator</label>
                </value>
                <value>
                    <fullName>Investor</fullName>
                    <isActive>false</isActive>
                    <label>Investor</label>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <isActive>false</isActive>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>Partner</fullName>
                    <isActive>false</isActive>
                    <label>Partner</label>
                </value>
                <value>
                    <fullName>Press</fullName>
                    <isActive>false</isActive>
                    <label>Press</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Plan_Request_Date_Approval_Date__c</fullName>
        <label>Business Plan Request Date-Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Framework__c</fullName>
        <label>Legal Framework</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Branch of a Foreign Company</fullName>
                </value>
                <value>
                    <fullName>Branch of a UAE Company</fullName>
                </value>
                <value>
                    <fullName>Branch of a UAE Establishment</fullName>
                </value>
                <value>
                    <fullName>Freelancer</fullName>
                </value>
                <value>
                    <fullName>Free Zone Limited Liability company</fullName>
                </value>
                <value>
                    <fullName>Limited Liability company</fullName>
                </value>
                <value>
                    <fullName>Decree Company</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <isActive>false</isActive>
                    <label>NA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Security_Clearance_Date__c</fullName>
        <label>Security Clearance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Security_Clearance_Status__c</fullName>
        <label>Security Clearance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Document__c.object
<CustomObject>
    <description>Custom object used as a placeholder to associate files with records. This object has a lookup to Account, and the rest of the relationships managed using a Lightning component.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AG_Number__c</fullName>
        <displayFormat>AG-{000000}</displayFormat>
        <label>AG Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Legal_Framework__c</fullName>
        <label>Legal Framework</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Freezone</fullName>
                </value>
                <value>
                    <fullName>Freelance</fullName>
                </value>
                <value>
                    <fullName>Branch UAE</fullName>
                </value>
                <value>
                    <fullName>Branch Foreign</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Soft Booked</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <isActive>false</isActive>
                    <label>NA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Opportunity.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Is_Registered_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Registered Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revision_Number__c</fullName>
        <label>Revision Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Registration_Request_Status_Setting__mdt.object
<CustomObject>
    <description>This setting is used in license registration request to manage statuses and toolbar.</description>
    <fields>
        <fullName>Convert_To_Trust_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Convert To Trust Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal_Framework__c</fullName>
        <label>Legal Framework</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Move_To_Next_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Move To Next Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validate_Lease_Items__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Validate Lease Items</label>
        <type>Checkbox</type>
    </fields>
    <label>Registration Request Status Setting</label>
    <pluralLabel>Registration Request Status Settings</pluralLabel>
</CustomObject>

src/objects/Requested_Licensed_Activity__c.object
<CustomObject>
    <description>This is a junction object to link an Activity with a Case (customer onboarding process). Used to capture Requested and Licensed Activities</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Requested/Licensed Activities</relationshipLabel>
        <relationshipName>Requested_Licensed_Activities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Requested/Licensed Activity</label>
    <nameField>
        <label>Requested Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requested/Licensed Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <description>Object used to store Unit Inventory mastered in Yardi on SF.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to link leased property units to account and in inventory management</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Soft Booked</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bank Account</fullName>
                    <default>true</default>
                    <label>Bank Account</label>
                </value>
                <value>
                    <fullName>Trust Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsMovedToNextStep__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Moved To Next Step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal_Framework__c</fullName>
        <formula>TEXT(Account.Legal_Framework__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Legal Framework</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minimum_Required_Share_Capital__c</fullName>
        <label>Minimum Required Share Capital</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Skip_Lease_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Skip Lease Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trust_Account_Payments_Received__c</fullName>
        <label>Trust Account Payments Received</label>
        <summarizedField>Trust_Account_Payment__c.Amount__c</summarizedField>
        <summaryForeignKey>Trust_Account_Payment__c.Work_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Work_Order_Number__c</fullName>
        <label>Work Order Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Work_Order_Type__c</fullName>
        <label>Work Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sequencial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WorkOrderUtils.cls
/************************************************************************************
* Name          : WorkOrderUtils                                                 
* Description   : Utility of Work Order Trigger
* Created Date  :                                                    
* Created By    : 4C - Anshul Garg (anshul.garg@weare4c.com)
* Jira/Req By   :                                                                                                                                           
* -----------------------------------------------------------------------------------------------------------------------
* VERSION   Developer   Date        Description     Ticket/Reference    

************************************************************************************/
global class WorkOrderUtils {
    /**
     *  @description Throws error if WOs are not approved sequentially
     *  @param  workOrderList  List of WorkOrders from Trigger.New
     *  @return 
     */
	public static void checkWorkOrderSequence(List<WorkOrder> workOrderList) {
        Set<Id> caseIds = new Set<Id>();
        System.debug('workOrderList'+workOrderList);
        
        for(WorkOrder wo : workOrderList) {
            if(wo.Status == 'Approved' || wo.Status == 'Rejected' || wo.Status == 'Completed') {
            	caseIds.add(wo.CaseId);
            }
        }
		System.debug('caseIds'+caseIds);  
        List<WorkOrder> workOrdersRelatedToCasesLst = 
            [SELECT Id, Status, Work_Order_Type__c, RecordTypeId, Work_Order_Number__c, CaseId
            FROM WorkOrder
            WHERE CaseId IN: caseIds
            AND Id NOT IN : Trigger.new
            AND (Status != 'Approved' 
            AND Status != 'Rejected'
            AND  Status != 'Completed')];
        
        System.debug('workOrdersRelatedToCasesLst'+workOrdersRelatedToCasesLst);
        
        //Set<Integer> sequenceNumbers = new Set<Integer>();
        Map<Id, Set<Decimal>> mapCaseIdWithSequenceNumber = new Map<Id, Set<Decimal>>();
        
        for(WorkOrder woObj : workOrdersRelatedToCasesLst) {
            //sequenceNumbers.add(woObj.Work_Order_Number__c);
            if(!mapCaseIdWithSequenceNumber.containsKey(woObj.CaseId)) {
                mapCaseIdWithSequenceNumber.put(woObj.CaseId,new Set<Decimal> {woObj.Work_Order_Number__c});
            }
            else {
                mapCaseIdWithSequenceNumber.get(woObj.CaseId).add(woObj.Work_Order_Number__c);
            }
            
           /* if(!quoteVsProductMap.containsKey(lineItemObj.QuoteId)) {
               quoteVsProductMap.put(lineItemObj.QuoteId, new Set<Id> {lineItemObj.Product2Id});
           }
           else {
               quoteVsProductMap.get(lineItemObj.QuoteId).add(lineItemObj.Product2Id);
           }*/
        }
        System.debug('mapCaseIdWithSequenceNumber=='+mapCaseIdWithSequenceNumber);
        
        for(WorkOrder woObj : workOrderList) {
            if(woObj.Status == 'Approved' || woObj.Status == 'Rejected' || woObj.Status == 'Completed') {
                if(mapCaseIdWithSequenceNumber.containsKey(woObj.caseId)) {
                    Set<Decimal> workOrderNumberSet = mapCaseIdWithSequenceNumber.get(woObj.CaseId);
                    System.debug('workOrderNumberSet=='+workOrderNumberSet);
                    workOrderNumberSet.remove(null);
                    if(!workOrderNumberSet.isEmpty()) {
                        for(Decimal sequenceNumber : workOrderNumberSet) {
                            if(sequenceNumber < woObj.Work_Order_Number__c) {
                                woObj.addError('The work orders has to be approved or rejected sequentially. Please approve or reject previous work orders first.');
                            }
                        }
                    }
                }
            }
        }
        
    }
    
    //Added methods from WorkOrderToolbarHandler
    @AuraEnabled
    global static WorkOrder getWorkOrderDetails(Id workOrderId) {
        try{            
            return [SELECT Id,Status,Account.Legal_Framework__c,
                    IsMovedToNextStep__c,Account.Security_Clearance_Status__c,Trust_Account_Payments_Received__c,
                    Account.Security_Clearance_Date__c,Account_Type__c,Minimum_Required_Share_Capital__c,
                    Account.Business_Plan_Request_Date_Approval_Date__c 
                    FROM WorkOrder WHERE Id = :workOrderId LIMIT 1];
        }catch(Exception ex){
            System.debug(ex);
            throw new AuraHandledException('Darn it! Something went wrong: '+ ex.getMessage());
        }
    }
    
    @AuraEnabled
    global static List<QuoteLineItem> getQuoteProducts(WorkOrder workOrder) {
        try{
            return [SELECT Id,Is_Registered_Address__c,Product2.Name,Quote.Opportunity.AG_Number__c,Product2.Unit__r.Name
                    FROM QuoteLineItem WHERE Quote.AccountId = :workOrder.AccountId AND Revision_Number__c = null];
        }catch(Exception ex){
            System.debug(ex);
            throw new AuraHandledException('Darn it! Something went wrong: '+ ex.getMessage());
        }
    }
    
    @AuraEnabled
    global static void updateRegisteredAddress(String qLineId) {
        try{
            update new QuoteLineItem(Id=qLineId,Is_Registered_Address__c=true);
        }catch(Exception ex){
            System.debug(ex);
            throw new AuraHandledException('Darn it! Something went wrong: '+ ex.getMessage());
        }
    }
    
    @AuraEnabled
    global static List<Registration_Request_Status_Setting__mdt> getStatusSettings() {
        try{
            return [SELECT Id,MasterLabel,DeveloperName,Convert_To_Trust_Account__c,Legal_Framework__c,
                    Move_To_Next_Status__c,Status__c,Validate_Lease_Items__c
                    FROM Registration_Request_Status_Setting__mdt];
        }catch(Exception ex){
            System.debug(ex);
            throw new AuraHandledException('Darn it! Something went wrong: '+ ex.getMessage());
        }
    }
    
    @AuraEnabled
    global static String sendUpdateToDDA(Id workOrderId, Boolean convertToTrust, Boolean isMoveToNext) {
        try{
            WorkOrder wo = [SELECT Id,AccountId,Skip_Lease_Validation__c,No_Of_Trust_account_Payments__c,Account_Type__c FROM WorkOrder WHERE Id =: workOrderId];            
            String errorMessage = '';
            if(isMoveToNext){
                errorMessage = isMoveToNextPossible(wo);
            }
            if(convertToTrust){
                errorMessage = isConvertToTrustPossible(wo);
            }
            if(String.isEmpty(errorMessage)){
                if(isMoveToNext){wo.IsMovedToNextStep__c = isMoveToNext;}
                if(convertToTrust){wo.Account_Type__c='Trust Account';}
                update wo;
                DDAIntegration.createNewServiceRequest(new Set<Id>{workOrderId}, convertToTrust, isMoveToNext);
                return '';
            }else{
                return errorMessage;
            }
        }catch(Exception ex){
            System.debug(ex);
            throw new AuraHandledException('Darn it! Something went wrong: '+ ex.getMessage());
        }
    }
    
    public static String isMoveToNextPossible(WorkOrder wo){
        String errorMessage = '';
        List<Document__c> docs = [SELECT Id,Name FROM Document__c WHERE Work_Order__c = :wo.Id AND Is_Mandatory__c = true AND File_Attached__c = false];
        if(!docs.isEmpty()){
            errorMessage = '* Please attach all mandatory Documents to Work Order.<br/>';
        }
        
        Boolean oppProductsFlag = true;
        Boolean opportunityFlag = true;
        Boolean serviceRequestTrustAccountPaymentFlag = true;
        Boolean licensedActivityFlag = true;
        Boolean opportunityStatusFlag = true;
        Boolean multipleUnits = false;
        Boolean isRegAddSelected = false;
        
        List<Quote> opportunityList = [SELECT Id,(SELECT Id,Is_Registered_Address__c FROM QuoteLineItems WHERE Revision_Number__c = null) FROM Quote WHERE AccountId = :wo.AccountId];
        opportunityFlag = opportunityList.isEmpty()?false:true;
        
        if(!opportunityFlag){
            errorMessage +='* Please add opportunity to related account.<br/>';
        }        

        if(opportunityFlag==true){
            for(Quote quo : opportunityList){
                oppProductsFlag = quo.QuoteLineItems.isEmpty()?false:true;
                if(!quo.QuoteLineItems.isEmpty() && quo.QuoteLineItems.size()>1){
                    multipleUnits = true;
                    for(QuoteLineItem qline : quo.QuoteLineItems){
                        if(qline.Is_Registered_Address__c){
                            isRegAddSelected = true;
                        }
                    }
                }
            }
        }
        
        if(oppProductsFlag==false && wo.Skip_Lease_Validation__c==false){
            errorMessage +='* Please add products to related opportunity.<br/>';
        }
        
        if(multipleUnits && !isRegAddSelected){
            errorMessage +='* Please select registered address.<br/>';
        }

        if(wo.No_Of_Trust_account_Payments__c==0 && wo.Account_Type__c == 'Trust Account'){
            errorMessage += '* Please add at least one Trust Account Payment.<br/>';
        }
        
        List<Requested_Licensed_Activity__c> requestedLicActs = [SELECT Id FROM Requested_Licensed_Activity__c WHERE Account__c =: wo.AccountId];
        if(requestedLicActs.isEmpty()){
            errorMessage += '* Please add requested licensed activities.<br/>';
        }
        
        if(errorMessage!=null){
            errorMessage = errorMessage.replace('null','');
        }
        return errorMessage;
    }
    
    public static String isConvertToTrustPossible(WorkOrder wo){
        String errorMessage = '';
        List<Document__c> docs = [SELECT Id,Name FROM Document__c WHERE Work_Order__c = :wo.Id AND Is_Mandatory__c = true AND File_Attached__c = false];
        if(!docs.isEmpty()){
            errorMessage = '* Please attach all mandatory Documents to Work Order.<br/>';
        }
        
        Boolean oppProductsFlag = true;
        Boolean opportunityFlag = true;
        Boolean serviceRequestTrustAccountPaymentFlag = true;
        Boolean licensedActivityFlag = true;
        Boolean opportunityStatusFlag = true;
        
        List<Opportunity> opportunityList = [SELECT Id FROM Opportunity WHERE AccountId = :wo.AccountId];
        opportunityFlag = opportunityList.isEmpty()?false:true;
        
        if(!opportunityFlag){
            errorMessage +='* Please add opportunity to related account.<br/>';
        }

        if(opportunityFlag==true){
            for(Opportunity opp:opportunityList){
                oppProductsFlag = opp.opportunityLineItems.isEmpty()?false:true;                
            }
        }
        
        if(oppProductsFlag==false && wo.Skip_Lease_Validation__c==false){errorMessage +='* Please add products to related opportunity.<br/>';}

        if(wo.No_Of_Trust_account_Payments__c==0 && wo.Account_Type__c == 'Trust Account'){
            errorMessage += '* Please add at least one Trust Account Payment.<br/>';        
        }
        
        List<Requested_Licensed_Activity__c> requestedLicActs = [SELECT Id FROM Requested_Licensed_Activity__c WHERE Account__c =: wo.AccountId];
        if(requestedLicActs.isEmpty()){
            errorMessage += '* Please add requested licensed activities.<br/>';
        }
        
        if(errorMessage!=null){
            errorMessage = errorMessage.replace('null','');
        }
        return errorMessage;
    }
}