src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yardi_Account_Id__c</fullName>
        <externalId>true</externalId>
        <label>Yardi Account Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Yardi_Integration_Error_Message__c</fullName>
        <label>Yardi Integration Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yardi_Integration_Status__c</fullName>
        <label>Yardi Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Integration - Yardi</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
                <value>
                    <fullName>Synced</fullName>
                    <isActive>false</isActive>
                    <label>Synced</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Comments__c</fullName>
        <label>Case Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Obligation_Date__c</fullName>
        <label>Financial Obligation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Cancelled__c</fullName>
        <formula>IF(
ISPICKVAL( Status, &quot;Cancelled&quot;),true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key_Handover_Date__c</fullName>
        <label>Key Handover Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Move_Out_Date__c</fullName>
        <description>Captured on the case termination record type</description>
        <label>Move Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SF_AGNO__c</fullName>
        <formula>Quote__r.Opportunity.AG_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SF AGNO</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Termination with Downsize</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Reason_new__c</fullName>
        <label>Termination Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Downsizing</fullName>
                </value>
                <value>
                    <fullName>Lease Cancellation</fullName>
                </value>
                <value>
                    <fullName>Lease Merger</fullName>
                </value>
                <value>
                    <fullName>Relocation Contraction</fullName>
                </value>
                <value>
                    <fullName>Relocation expansion</fullName>
                </value>
                <value>
                    <fullName>Area Amendment</fullName>
                </value>
                <value>
                    <fullName>Rent Reduction</fullName>
                </value>
                <value>
                    <fullName>Splitting</fullName>
                </value>
                <value>
                    <fullName>Changing: The name/Activity/FZ-LLC/Branch/Shareholders</fullName>
                </value>
                <value>
                    <fullName>Lease termination for DED tenant</fullName>
                </value>
                <value>
                    <fullName>Relocation due to TECOM request.(without financial impact)</fullName>
                </value>
                <value>
                    <fullName>Calculation Only</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Financial Challenges</fullName>
                    <isActive>false</isActive>
                    <label>Financial Challenges</label>
                </value>
                <value>
                    <fullName>High Rent</fullName>
                    <isActive>false</isActive>
                    <label>High Rent</label>
                </value>
                <value>
                    <fullName>Moving to other free zone in UAE</fullName>
                    <isActive>false</isActive>
                    <label>Moving to other free zone in UAE</label>
                </value>
                <value>
                    <fullName>Repossession</fullName>
                    <isActive>false</isActive>
                    <label>Repossession</label>
                </value>
                <value>
                    <fullName>Unsatisfied service</fullName>
                    <isActive>false</isActive>
                    <label>Unsatisfied service</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Type__c</fullName>
        <formula>IF(
  Termination_Date__c = Contract__r.EndDate, &quot;Normal&quot;,
 IF(
   Termination_Date__c &lt; Contract__r.EndDate, &quot;Early&quot;,
&quot;Normal&quot;)
)</formula>
        <label>Termination Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yardi_Brand_Code__c</fullName>
        <formula>Quote__r.Opportunity.T_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Yardi Lease Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yardi_Integration_Error_Message__c</fullName>
        <label>Yardi Integration Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Yardi_Integration_Status__c</fullName>
        <label>Yardi Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Integration</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Assignment</fullName>
        <active>true</active>
        <businessProcess>Application Form</businessProcess>
        <label>Assignment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lease_Termination</fullName>
        <active>true</active>
        <businessProcess>Termination Process</businessProcess>
        <description>To be used when a termination has been initiated on an active lease contract</description>
        <label>Lease Termination</label>
    </recordTypes>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <businessProcess>Application Form</businessProcess>
        <description>To create a Case for Land On-Boarding</description>
        <label>Land On-Boarding</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yardi_Integration_Error_Message__c</fullName>
        <label>Yardi Integration Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yardi_Integration_Status__c</fullName>
        <label>Yardi Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Integration - Yardi</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AG_Number__c</fullName>
        <displayFormat>AG-{000000}</displayFormat>
        <label>AG Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Downsize</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Yardi_Integration_Error_Message__c</fullName>
        <label>Yardi Integration Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yardi_Integration_Status__c</fullName>
        <label>Yardi Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Outstanding_Payments__c.object
<CustomObject>
    <description>Custom Object to store any outstanding payments when termination is initiated.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Outstanding Payments</relationshipLabel>
        <relationshipName>Outstanding_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charge_Code__c</fullName>
        <label>Charge Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charge_From__c</fullName>
        <label>Charge From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Charge_To__c</fullName>
        <label>Charge To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Outstanding Payments</relationshipLabel>
        <relationshipName>Outstanding_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Outstanding Payments</relationshipLabel>
        <relationshipName>Outstanding_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Outstanding_Lease_Amount__c</fullName>
        <label>Outstanding LeaseAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VAT_Amount__c</fullName>
        <label>VAT Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Outstanding Payment</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Outstanding Payments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outstanding Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Opportunity.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Terms_Changed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Legal Terms Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Yardi_Brand_Code__c</fullName>
        <formula>Opportunity.Account.Yardi_Account_Id__c</formula>
        <label>Yardi Brand Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yardi_Integration_Error_Message__c</fullName>
        <label>Yardi Integration Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Yardi_Integration_Status__c</fullName>
        <label>Yardi Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Integration</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Charge_Code__c</fullName>
        <label>Charge Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yardi_Integration_Error_Message__c</fullName>
        <label>Yardi Integration Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yardi_Integration_Status__c</fullName>
        <label>Yardi Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Integration</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TerminationIntegration.cls
/***********************************************************************************************
* Name              : TerminationIntegration                                               
* Description       : Real-time integration for termination/assignment details to be sent to OIC, which will push the details to Yardi
* Created Date      : 06/08/2019                                                    
* Created By        : Raza khan (raza.khan@were4c.com)                                                                                                    
* ----------------------------------------------------------------------------------------------
* VERSION   Developer   Date        Description     Ticket/Reference                                                                    
* 1.0       Raza      20/08/2019   Created 
* 2.0 .     Raza     03/09/2019 .  Update .         Update the notice date for the terminations
* 3.0 .     Raza     08/09/2019 .  Update .         Update the controller to add new assignment integration request
************************************************************************************************/

public with sharing class TerminationIntegration {
    
    
    public static void sentTerminationToOIC(List<Id> caseIds)
    {
        List<Case> terminationCases =  [SELECT Id, Quote__c,SF_AGNO__c,Yardi_Brand_Code__c,Financial_Obligation_Date__c,
                                        Case_Comments__c,Move_Out_Date__c,Key_Handover_Date__c,Termination_Type__c,Termination_Reason_new__c,
                                        Is_Cancelled__c,Quote__r.OpportunityId, Yardi_Integration_Error_Message__c, Yardi_Integration_Status__c,
                                        Contract__c, AccountId,type, createddate FROM Case where recordtype.Developername = 'Lease_Termination' and Id in:caseIds ];
        
        Map<Id, String> productCodeMap = getProductCode(terminationCases);
        
        List<case> terminationToUpdate = new List<Case>();
        List<Outstanding_Payments__c> outsandingPayments = new List<Outstanding_Payments__c>();
        
        for(Case cas:terminationCases )
        {
            RequestWrapper.TerminationRequestWrapper requestWrap = new RequestWrapper.TerminationRequestWrapper();
            requestWrap.propertyCode = productCodeMap.get(cas.Quote__c);
            requestWrap.opportunityAGNumber = cas.SF_AGNO__c;
            requestWrap.brandCode = cas.Yardi_Brand_Code__c;
            requestWrap.fodDate = cas.Financial_Obligation_Date__c;
            requestWrap.description = cas.Case_Comments__c != null ? cas.Case_Comments__c: '';
            requestWrap.moveOutDate = cas.Move_Out_Date__c;
            requestWrap.keyHandOverDate = cas.Key_Handover_Date__c != null ?  cas.Key_Handover_Date__c: system.today().addYears(-20);
            requestWrap.terminationType = cas.Termination_Type__c;
            requestWrap.reason = cas.Termination_Reason_new__c;
            requestWrap.isCancelled = cas.Is_Cancelled__c;
            requestWrap.opportunityId = cas.Quote__r.OpportunityId;
            requestWrap.NoticeDate = cas.CreatedDate.date();
            
            httpResponse response = new httpResponse();
            
            try{ 
                String request = JSON.serialize(requestWrap);   
                System.debug('request:'+ request);
                response =  RealTimeIntegrationFramework.realTimeCall(request,System.Label.OIC_Termination_Endpoint);  // need to change the end point to termination
                
                system.debug('response:'+ response);                                             
                RequestWrapper.TerminationResponse responseData = (RequestWrapper.TerminationResponse)JSON.deserialize(response.getBody(), RequestWrapper.TerminationResponse.class);
                if(responseData != null){
                    if( responseData.opportunityTCode != null && !string.isBlank(responseData.opportunityTCode)  ){
                        
                        cas.Yardi_Integration_Status__c  = responseData.yardiIntegrationStatus;
                        cas.Yardi_Integration_Error_Message__c  = responseData.yardiIntegrationErrorMessage;
                        
                        if(responseData.outstandingPayments != null){
                            
                            for(RequestWrapper.OutstandingPayment wpayment: responseData.outstandingPayments)
                            {
                                if((wpayment.billedAmount != null && wpayment.billedAmount >0) ||
                                   (wpayment.vatAmount != null && wpayment.vatAmount >0))
                                {
                                    Outstanding_Payments__c payment = new Outstanding_Payments__c();
                                    payment.Description__c   = wpayment.description;
                                    payment.Charge_Code__c  = wpayment.chargeCode;
                                    payment.Outstanding_Lease_Amount__c   = wpayment.billedAmount;
                                    payment.VAT_Amount__c  = wpayment.vatAmount;
                                    payment.Charge_From__c   = wpayment.chargeFrom;
                                    payment.Charge_From__c  = wpayment.chargeTo;
                                    payment.Charge_To__c = wpayment.chargeTo;
                                    payment.Opportunity__c  = cas.Quote__r.OpportunityId;
                                    payment.Contract__c = cas.Contract__c;
                                    payment.Account__c = cas.AccountId;
                                    outsandingPayments.add(payment);
                                }
                                
                            }
                        }
                        
                        
                    } 
                }else{
                    cas.Yardi_Integration_Status__c  = 'Error';
                    cas.Yardi_Integration_Error_Message__c  = response.getBody();
                }
                
            }
            catch(Exception e){
                System.debug('Callout error: '+ e);
                cas.Yardi_Integration_Error_Message__c = e.getMessage();
            }     
            
            terminationToUpdate.add(cas);   
        }
        
        if(terminationToUpdate.size() > 0){
            update terminationToUpdate;
        }
        
        if(outsandingPayments.size() >0){
            insert outsandingPayments;
        }
    }
    
     public static void sentAssigmentToOIC(List<Id> caseIds)
    {
        List<Case> terminationCases =  [Select  id , accountId, Account.Yardi_Account_Id__c, account.ParentId, account.Parent.Yardi_Account_Id__c,Opportunity__c,
                                        Opportunity__r.AG_Number__c, Quote__r.Legal_Terms_Changed__c,Opportunity__r.Type, Opportunity__r.Sub_Type__c,Opportunity__r.name, 
                                        Account.Legal_Name__c, Opportunity__r.Lease_Type__c,createddate,Opportunity__r.Retail_Sales_Category__c, Case_Comments__c,Opportunity__r.T_Code__c,
                                        Quote__r.Yardi_Brand_Code__c, Quote__r.Contact.Yardi_Contact_Id__c,Yardi_Integration_Status__c, Yardi_Integration_Error_Message__c
                                        FROM Case where recordtype.Developername = 'Assignment' and Id in:caseIds ];
        
        Map<Id, String> productCodeMap = getProductCode(terminationCases);
        
        List<case> terminationToUpdate = new List<Case>();
        
        for(Case cas:terminationCases )
        {
            RequestWrapper.Assignment requestWrap = new RequestWrapper.Assignment();
            requestWrap.propertyCode = productCodeMap.get(cas.Quote__c);
            requestWrap.extRefLeaseId = cas.Opportunity__c;
            requestWrap.opportunityAGNumber = cas.SF_AGNO__c;
           	requestWrap.legalTermChanged = cas.Quote__r.Legal_Terms_Changed__c;
            requestWrap.amendmentType = cas.Opportunity__r.Type;
            requestWrap.amendmentSubType = cas.Opportunity__r.Sub_Type__c;
            requestWrap.yardiLeaseCode = cas.Opportunity__r.T_Code__c;
            requestWrap.yardibrandCode = cas.Quote__r.Yardi_Brand_Code__c; 
            requestWrap.status  = cas.Quote__r.Status;
            requestWrap.leaseName = cas.Opportunity__r.Name;
            requestWrap.companyName = cas.Account.Legal_Name__c;
            requestWrap.leaseType = cas.Opportunity__r.Lease_Type__c;
            requestWrap.assignmentDate = cas.createddate.date();
            requestWrap.description = cas.Case_Comments__c != null ? cas.Case_Comments__c: '';
            requestWrap.yardiContactCode = cas.Quote__r.Contact.Yardi_Contact_Id__c;
            httpResponse response = new httpResponse();
            
            try{ 
                String request = JSON.serialize(requestWrap);   
                System.debug('request:'+ request);
                response =  RealTimeIntegrationFramework.realTimeCall(request,'System.Label.OIC_Assignment_Endpoint');  // need to change the end point to assignment
                
                system.debug('response:'+ response);                                             
                RequestWrapper.TerminationResponse responseData = (RequestWrapper.TerminationResponse)JSON.deserialize(response.getBody(), RequestWrapper.TerminationResponse.class);
                if(responseData != null){ 
                    if( responseData.opportunityTCode != null && !string.isBlank(responseData.opportunityTCode)  ){
                        
                        cas.Yardi_Integration_Status__c  = responseData.yardiIntegrationStatus;
                        cas.Yardi_Integration_Error_Message__c  = responseData.yardiIntegrationErrorMessage;
                        
                       
                        }
                        
                        
                    } 
                else{
                    cas.Yardi_Integration_Status__c  = 'Error';
                    cas.Yardi_Integration_Error_Message__c  = response.getBody();
                }
                
            }
            catch(Exception e){
                System.debug('Callout error: '+ e);
                cas.Yardi_Integration_Error_Message__c = e.getMessage();
            }     
            
            terminationToUpdate.add(cas);   
        }
        
        if(terminationToUpdate.size() > 0){
            update terminationToUpdate;
        }
    }
    
    private static map<Id, String> getProductCode(List<Case> cases)
    {
        Map<Id, String> productCodeMap = new Map<Id, String>();
        List<Id> quoteIds = new List<Id>();
        for(Case c: cases)
        {
            quoteIds.add(c.Quote__c);
        }
        List<QuoteLineItem> items = [Select id, QuoteId, Product_Code__c from QuoteLineItem where QuoteId in:quoteIds and Product_Code__c  != null  ];
        for( QuoteLineItem qli: items)
            productCodeMap.put(qli.QuoteId, qli.Product_Code__c);
        
        return productCodeMap;
        
    }
    
}