src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reseller</fullName>
                </value>
                <value>
                    <fullName>Art</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Fashion</fullName>
                </value>
                <value>
                    <fullName>Luxury</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Brand</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Kiosk</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Analyst</fullName>
                    <isActive>false</isActive>
                    <label>Analyst</label>
                </value>
                <value>
                    <fullName>Broker</fullName>
                    <isActive>false</isActive>
                    <label>Broker</label>
                </value>
                <value>
                    <fullName>Business Partner</fullName>
                    <isActive>false</isActive>
                    <label>Business Partner</label>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                    <isActive>false</isActive>
                    <label>Competitor</label>
                </value>
                <value>
                    <fullName>Customer</fullName>
                    <isActive>false</isActive>
                    <label>Customer</label>
                </value>
                <value>
                    <fullName>Integrator</fullName>
                    <isActive>false</isActive>
                    <label>Integrator</label>
                </value>
                <value>
                    <fullName>Investor</fullName>
                    <isActive>false</isActive>
                    <label>Investor</label>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <isActive>false</isActive>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>Partner</fullName>
                    <isActive>false</isActive>
                    <label>Partner</label>
                </value>
                <value>
                    <fullName>Press</fullName>
                    <isActive>false</isActive>
                    <label>Press</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Framework__c</fullName>
        <label>Legal Framework</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Branch of a Foreign Company</fullName>
                </value>
                <value>
                    <fullName>Branch of a UAE Company</fullName>
                </value>
                <value>
                    <fullName>Branch of a UAE Establishment</fullName>
                </value>
                <value>
                    <fullName>Freelancer</fullName>
                </value>
                <value>
                    <fullName>Free Zone Limited Liability company</fullName>
                </value>
                <value>
                    <fullName>Limited Liability company</fullName>
                </value>
                <value>
                    <fullName>Decree Company</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <isActive>false</isActive>
                    <label>NA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Registration_Request_Status_Setting__mdt.object
<CustomObject>
    <description>This setting is used in license registration request to manage statuses and toolbar.</description>
    <fields>
        <fullName>Legal_Framework__c</fullName>
        <label>Legal Framework</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Move_To_Next_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Move To Next Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Registration Request Status Setting</label>
    <pluralLabel>Registration Request Status Settings</pluralLabel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bank Account</fullName>
                    <default>true</default>
                    <label>Bank Account</label>
                </value>
                <value>
                    <fullName>Trust Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_To_RC__c</fullName>
        <label>Assigned To RC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Branch__c</fullName>
        <label>Bank Branch</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <label>Bank</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_For_Review_Reason__c</fullName>
        <label>Call For Review Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDA_Request_Id__c</fullName>
        <externalId>true</externalId>
        <label>DDA Request Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsMovedToNextStep__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Moved To Next Step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Data_Migrated_and_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Data Migrated and Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal_Framework__c</fullName>
        <formula>TEXT(Account.Legal_Framework__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Legal Framework</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minimum_Required_Share_Capital__c</fullName>
        <label>Minimum Required Share Capital</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skip_Lease_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Skip Lease Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Due__c</fullName>
        <label>Total Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Under_Registration_BU_Sub_Category__c</fullName>
        <label>Under Registration BU Sub Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Order_Number__c</fullName>
        <label>Work Order Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LicenseRegistrationWebserviceTest.cls
/**
*  @description Test class for LicenseRegistrationWebservice
*
*  2019-08-22  Shraddha N    First version
*  
*/
@isTest
public class LicenseRegistrationWebserviceTest {
    
    /* global HTTPResponse respond(HTTPRequest request) {
        // Create a fake response
        HttpResponse response = new HttpResponse();
        response.setHeader('Content-Type', 'application/json');
        response.setBody('{"result": "abc"}');
        response.setStatusCode(200);
        return response; 
    }*/
    
    /*Common test data to be used in test class*/
    @testSetup
    public static void setUp(){

        WorkOrder workOrderObject = new WorkOrder(Status = 'New', 
                                                  Description = 'test Description', 
                                                  Work_Order_Number__c = 1, 
                                                  Account_Type__c = 'Trust Account', 
                                                  Minimum_Required_Share_Capital__c = 10000,
                                                  IsMovedToNextStep__c = true,
                                                  DDA_Request_Id__c = 'Req-1',
                                                  Service_Name__c = 'Test Service',
                                                  Is_Data_Migrated_and_Locked__c = FALSE,
                                                  Assigned_To_RC__c = 'Test Assignment',
                                                  Under_Registration_BU_Sub_Category__c = 'Test Under Registration BU Sub_Category',
                                                  Skip_Lease_Validation__c = TRUE,
                                                  Call_For_Review_Reason__c = 'Test Call',
                                                  Total_Amount_Due__c = 123,
                                                  Bank__c = 'Test Bank',
                                                  Bank_Branch__c = 'Test Bank Branch');
        insert workOrderObject;  
    }
    
    // Getting metadata object record
    @testVisible 
    static List<Registration_Request_Status_Setting__mdt> customMetadata { 
        get {
            if ( customMetadata == null )
                customMetadata = [SELECT Id,Legal_Framework__c, Move_To_Next_Status__c,Status__c
                                  FROM Registration_Request_Status_Setting__mdt]; 
            return customMetadata;
        } 
        set; 
    }
    
    //Method to test pushServiceRequestUpdates method
    @isTest
    public static void pushServiceRequestUpdatesTest(){
        WorkOrder workOrderObject = [SELECT Id, DDA_Request_Id__c, Service_Name__c, Status, Is_Data_Migrated_and_Locked__c,
                                     Assigned_To_RC__c, Under_Registration_BU_Sub_Category__c, Skip_Lease_Validation__c,
                                     Call_For_Review_Reason__c, Total_Amount_Due__c, Minimum_Required_Share_Capital__c,
                                     Bank__c, Bank_Branch__c FROM WorkOrder WHERE Status = 'New' LIMIT 1];
        
        LicenseRegistrationWebservice.ServiceRequest serviceReqObject = new LicenseRegistrationWebservice.ServiceRequest();
        serviceReqObject.workOrderId = workOrderObject.Id;
        serviceReqObject.ddaSerReqId = workOrderObject.DDA_Request_Id__c;
        serviceReqObject.serviceName = workOrderObject.Service_Name__c;
        serviceReqObject.status = workOrderObject.Status;
        serviceReqObject.isDataMigratedLocked = workOrderObject.Is_Data_Migrated_and_Locked__c;
        serviceReqObject.assignedToRCName = workOrderObject.Assigned_To_RC__c;
        serviceReqObject.busiUnitSubCat = workOrderObject.Under_Registration_BU_Sub_Category__c;
        serviceReqObject.skipLeaseValidation = workOrderObject.Skip_Lease_Validation__c;
        serviceReqObject.callForReviewReason = workOrderObject.Call_For_Review_Reason__c;
        serviceReqObject.totalAmountDue = workOrderObject.Total_Amount_Due__c;
        serviceReqObject.minReqShareCapital = workOrderObject.Minimum_Required_Share_Capital__c;
        serviceReqObject.bank = workOrderObject.Bank__c;
        serviceReqObject.bankBranch = workOrderObject.Bank_Branch__c;
        
        LicenseRegistrationWebservice.ServiceRequest serviceReqObject2 = new LicenseRegistrationWebservice.ServiceRequest();

        List<LicenseRegistrationWebservice.ServiceRequest> serviceReqList = new List<LicenseRegistrationWebservice.ServiceRequest>();
        serviceReqList.add(serviceReqObject);
        
        
        Test.startTest();        
        LicenseRegistrationWebservice.RequestResponse reqResponse1 = LicenseRegistrationWebservice.pushServiceRequestUpdates(serviceReqList);
        serviceReqList.add(serviceReqObject2);
        LicenseRegistrationWebservice.RequestResponse reqResponse2 = LicenseRegistrationWebservice.pushServiceRequestUpdates(serviceReqList);
        Test.stopTest();
        
        System.assertNotEquals(NULL, reqResponse1);
        System.assertNotEquals(NULL, reqResponse2);
        System.assertEquals(TRUE, reqResponse1.success);
        System.assertEquals(FALSE, reqResponse2.success);
        System.assertEquals('', reqResponse1.errorMessage);
        System.assertNotEquals('', reqResponse2.errorMessage);
    }
}