src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Plan_Request_Date_Approval_Date__c</fullName>
        <label>Business Plan Request Date-Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Framework__c</fullName>
        <label>Legal Framework</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Branch of a Foreign Company</fullName>
                </value>
                <value>
                    <fullName>Branch of a UAE Company</fullName>
                </value>
                <value>
                    <fullName>Branch of a UAE Establishment</fullName>
                </value>
                <value>
                    <fullName>Freelancer</fullName>
                </value>
                <value>
                    <fullName>Free Zone Limited Liability company</fullName>
                </value>
                <value>
                    <fullName>Limited Liability company</fullName>
                </value>
                <value>
                    <fullName>Decree Company</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <isActive>false</isActive>
                    <label>NA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Security_Clearance_Date__c</fullName>
        <label>Security Clearance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Security_Clearance_Status__c</fullName>
        <label>Security Clearance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Business_Park__c.object
<CustomObject>
    <description>Object to store Business Parks. Business Parks are managed manually in Salesforce, with Oracle being the master.</description>
    <fields>
        <fullName>Business_Park_Yardi__c</fullName>
        <externalId>true</externalId>
        <label>Business Park (Yardi)</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Business Park</label>
    <nameField>
        <label>Business Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Billing_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Billing Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ParentCon__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ParentCon</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Security_Clearance_Date__c</fullName>
        <label>Security Clearance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Security_Clearance_Status__c</fullName>
        <label>Security Clearance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Leasing Contact</fullName>
                </value>
                <value>
                    <fullName>Licensee Contact</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Alternate Payee</fullName>
                </value>
                <value>
                    <fullName>Authorized Signatory</fullName>
                </value>
                <value>
                    <fullName>Focal Point</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Legal Representative</fullName>
                </value>
                <value>
                    <fullName>Manager Incharge</fullName>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>PRO</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>CollectionTeam</fullName>
                </value>
                <value>
                    <fullName>Licensing Contact</fullName>
                </value>
                <value>
                    <fullName>Individual Shareholder</fullName>
                </value>
                <value>
                    <fullName>Corporate Shareholder</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isSubmit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isSubmit</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Framework__c</fullName>
        <label>Legal Framework</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Freezone</fullName>
                </value>
                <value>
                    <fullName>Freelance</fullName>
                </value>
                <value>
                    <fullName>Branch UAE</fullName>
                </value>
                <value>
                    <fullName>Branch Foreign</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Proposed_End_Date__c</fullName>
        <label>Proposed End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <label>Proposed Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Downsize</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OpportunityUtilityTest.cls
/**
 *  @description Test class for OpportunityUtility
 *
 *  2019-08-29  Anshul G    First version
 *  
 */
@isTest
public class OpportunityUtilityTest {
    //Common test data to be used in test class
    @testSetup
    public static void testDataSetUp(){
        Account accountObject = new Account(Name = 'Test Account 1',Phone='1111111', Legal_Framework__c = 'Branch of a Foreign Company', Security_Clearance_Date__c = Date.today(), Security_Clearance_Status__c = 'NA', Business_Plan_Request_Date_Approval_Date__c = Date.today());
        insert accountObject;
        Account accountObject2 = new Account(Name = 'Test Account 2',Phone='1111111', Legal_Framework__c = 'Branch of a Foreign Company', Security_Clearance_Date__c = Date.today(), Security_Clearance_Status__c = 'NA', Business_Plan_Request_Date_Approval_Date__c = Date.today());
        insert accountObject2;
        Account accountObject3 = new Account(Name = 'Test Account 3',Phone='1111111', Legal_Framework__c = 'Branch of a Foreign Company', Security_Clearance_Date__c = Date.today(), Security_Clearance_Status__c = 'NA', Business_Plan_Request_Date_Approval_Date__c = Date.today());
        insert accountObject3;
        
        Contact contactObject = new Contact(LastName = 'Test Contact 1',Email = 'test.mail@test.com', isSubmit__c = true, ParentCon__c = true, AccountId= accountObject.id ,Type__c = 'Manager Incharge');
        insert contactObject;
        Contact contactObject2 = new Contact(LastName = 'Test Contact 2',Email = 'test.mail1@test.com', isSubmit__c = true, ParentCon__c = true, AccountId= accountObject2.id ,Type__c = 'Billing',Is_Billing_Contact__c = TRUE);
        insert contactObject2;
        
        Business_Park__c businessParkObject = new Business_Park__c(Name = 'Test BusinessPark',
                                                                   Business_Park_Yardi__c = 'Test Yardi');
        insert businessParkObject;
        
        Opportunity opportunityObject1 = new Opportunity(Name = 'Test Opportunity',
                                                         AccountId = accountObject.Id,
                                                         Contact__c = contactObject.Id,
                                                         Business_Park__c = businessParkObject.Id,
                                                         StageName = 'New',
                                                         CloseDate = System.today()
                                                         
                                                        );
        insert opportunityObject1;
        
        Quote quoteObject1 = new Quote(Name = 'Test Quote',
                                       Proposed_Start_Date__c = System.today(),
                                       Proposed_End_Date__c = System.today().addDays(2),
                                       Pricebook2Id = Test.getStandardPricebookId(),
                                       OpportunityId = opportunityObject1.Id);
        insert quoteObject1;
        
        Opportunity opportunityObject2 = new Opportunity(Name = 'Test Opportunity 2',
                                                         AccountId = accountObject.Id,
                                                         Contact__c = contactObject.Id,
                                                         Business_Park__c = businessParkObject.Id,
                                                         StageName = 'New',
                                                         CloseDate = System.today()
                                                        );
        insert opportunityObject2;
        
        Quote quoteObject2 = new Quote(Name = 'Test Quote',
                                       Proposed_Start_Date__c = System.today(),
                                       Proposed_End_Date__c = System.today().addDays(2),
                                       Pricebook2Id = Test.getStandardPricebookId(),
                                       OpportunityId = opportunityObject2.Id);
        insert quoteObject2;
        
        opportunityObject2.StageName = 'Negotiation';
        opportunityObject2.Type = 'Renewal';
        update opportunityObject2;
        
    }
    
    //Method to test validateOpportunityStatusChange method - Positive Testing
    @isTest
    public static void validateOpportunityStatusChangePositiveTest(){
        String errorMessage = '';  
        Test.startTest();
        Opportunity opportunityObject1 = [SELECT Id, Type, StageName FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Case caseObject = new Case(Status = 'Finance Approved', Opportunity__c = opportunityObject1.Id);
        insert caseObject;   
        
        opportunityObject1.StageName = 'Negotiation';
        opportunityObject1.Type = 'Renewal';
        try{
             update opportunityObject1;
        } catch(Exception e){
            errorMessage = e.getMessage();
        }
        Test.stopTest();
       System.assertEquals(errorMessage.contains('Stage of this opportunity can not be changed as it have In Progess Case Termination') , TRUE);
    }
    
    //Method to test validateOpportunityStatusChange method- Negative Testing
    @isTest
    public static void validateOpportunityStatusChangeNegativeTest(){
        String errorMessage = '';  
        Test.startTest();        
        Opportunity opportunityObject1 = [SELECT Id, Type, StageName FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Case caseObject = new Case(Status = 'New', Opportunity__c = opportunityObject1.Id);
        insert caseObject;   
        
        opportunityObject1.StageName = 'Negotiation';
        opportunityObject1.Type = 'Renewal';
        
       try{
             update opportunityObject1;
        } catch(Exception e){
            errorMessage = e.getMessage();
        }
        Test.stopTest();
        
       System.assertEquals(errorMessage.contains('Stage of this opportunity can not be changed as it have In Progess Case Termination') , FALSE);
       
    }
    
    //Method to test checkContactRoleAgainstAccount method- Positive Testing
    @isTest
    public static void checkContactRoleAgainstAccountPositiveTest(){
        String errorMessage = '';        
        Account accountObject = [SELECT Id FROM Account WHERE Name = 'Test Account 1' LIMIT 1];
        Contact contactObject = [SELECT Id FROM Contact WHERE LastName = 'Test Contact 2' LIMIT 1];
        Opportunity opportunityObject = [SELECT Id, Type, StageName, AccountId, Contact__c FROM Opportunity WHERE Name = 'Test Opportunity 2' LIMIT 1];
		
		Test.startTest();        
        opportunityObject.AccountId = accountObject.Id;
        opportunityObject.Contact__c = contactObject.Id;
        try{
            update opportunityObject;
        }  catch(Exception e){
            errorMessage = e.getMessage();
        }
        Test.stopTest();
        
        System.assertEquals(errorMessage.contains(System.Label.Account_Related_Contact_Role), TRUE);
    }
    
    //Method to test checkContactRoleAgainstAccount method- Negative Testing
    @isTest
    public static void checkContactRoleAgainstAccountNegativeTest(){
        String errorMessage = '';  
        Account accountObject = [SELECT Id FROM Account WHERE Name = 'Test Account 2' LIMIT 1];
        Contact contactObject = [SELECT Id FROM Contact WHERE LastName = 'Test Contact 2' LIMIT 1];
          
        Opportunity opportunityObject = [SELECT Id, Type, StageName, AccountId, Contact__c FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        
        Test.startTest();
        opportunityObject.AccountId = accountObject.Id;
        opportunityObject.Contact__c = contactObject.Id;
      
        try{
            update opportunityObject;
        }  catch(Exception e){
            errorMessage = e.getMessage();
        }
        Test.stopTest();
        
        System.assertEquals(errorMessage.contains(System.Label.Account_Related_Contact_Role), FALSE);
    }
}