src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Business_Account</fullName>
        <active>true</active>
        <label>Business Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Business_Park__c.object
<CustomObject>
    <description>Object to store Business Parks. Business Parks are managed manually in Salesforce, with Oracle being the master.</description>
    <fields>
        <fullName>Business_Park_Yardi__c</fullName>
        <externalId>true</externalId>
        <label>Business Park (Yardi)</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Business Park</label>
    <nameField>
        <label>Business Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Leasing Contact</fullName>
                </value>
                <value>
                    <fullName>Licensee Contact</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Alternate Payee</fullName>
                </value>
                <value>
                    <fullName>Authorized Signatory</fullName>
                </value>
                <value>
                    <fullName>Focal Point</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Legal Representative</fullName>
                </value>
                <value>
                    <fullName>Manager Incharge</fullName>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>PRO</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>CollectionTeam</fullName>
                </value>
                <value>
                    <fullName>Licensing Contact</fullName>
                </value>
                <value>
                    <fullName>Individual Shareholder</fullName>
                </value>
                <value>
                    <fullName>Corporate Shareholder</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Payment_Term__c.object
<CustomObject>
    <description>Object used to capture Payment Term information, to be used on Quotes.</description>
    <fields>
        <fullName>Number_Of_Payments__c</fullName>
        <label>Number Of Payments</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payment Terms</label>
    <nameField>
        <label>Payment Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <formula>Unit__r.Building__r.Business_Park__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Park</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Term</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Products (Payment Term)</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Terms</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DDA</fullName>
                </value>
                <value>
                    <fullName>AXS</fullName>
                </value>
                <value>
                    <fullName>Parking Cards</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <label>Unique Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Number_Of_Payments__c</fullName>
        <label>Number Of Payments</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Payment Terms</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_End_Date__c</fullName>
        <label>Proposed End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <label>Proposed Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Best_Rate__c</fullName>
        <label>Total Rent Best Rate</label>
        <summarizedField>QuoteLineItem.Total_Best_Rate__c</summarizedField>
        <summaryFilterItems>
            <field>QuoteLineItem.Parent_Quote_Line_Item__c</field>
            <operation>equals</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Downsize</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Revision__c.object
<CustomObject>
    <description>Object used to track the Quote Revisions to support summaries for multi-year leases.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quote Revisions</relationshipLabel>
        <relationshipName>Quote_Revisions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Best_Rate__c</fullName>
        <label>Total Best Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Offered_Price__c</fullName>
        <label>Total Offered Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Revision</label>
    <nameField>
        <displayFormat>REV-{000000}</displayFormat>
        <label>Quote Revision Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Revisions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Best_Rate__c</fullName>
        <label>Best Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offer_Price__c</fullName>
        <label>Offer Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quote_Revision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Revision</label>
        <referenceTo>Quote_Revision__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Best_Rate__c</fullName>
        <label>Total Best Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Offered_Price__c</fullName>
        <label>Total Offered Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transactional_Unit__c</fullName>
        <label>Transactional Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sqft</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Grace Period</fullName>
                </value>
                <value>
                    <fullName>Revision</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GetChildOpportunityTest.cls
@isTest
public class GetChildOpportunityTest {
    @testSetUp
    public static void setUp(){
        //if (test.isRunningTest()) Test.setMock(HttpCalloutMock.class, new GetChildOpportunity());
        //Id recordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business_Account').getRecordTypeId();
       // String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Account' and Name = 'Business_Account'].Id;
        Account accountObject = new Account(Name = 'Test Account',
                                                         Phone = '123456'
                                                        );
        insert accountObject;
        
        Contact contactObject = new Contact(LastName = 'Test Contact',
                                            AccountId = accountObject.Id,
                                            Email = 'test@test.com',
                                            Phone = '123456');
        insert contactObject;
            
        Business_Park__c businessParkObject = new Business_Park__c(Name = 'Test BusinessPark',
                                                                                Business_Park_Yardi__c = 'Test Yardi');
        insert businessParkObject;
        
        Opportunity opportunityObject = new Opportunity(Name = 'Test Opportunity',
                                                                      AccountId = accountObject.Id,
                                                                      Contact__c = contactObject.Id,
                                                                      Business_Park__c = businessParkObject.Id,
                                                                      StageName = 'New',
                                                                      CloseDate = System.today()
                                                                      );
        insert opportunityObject;
        
        Payment_Term__c paymentTermObject = new Payment_Term__c(Name = 'Test Payment Term',
                                                               Number_Of_Payments__c = 2);
        insert paymentTermObject;
        
        Quote quoteObject = new Quote(Name = 'Test Quote',
                                     Proposed_Start_Date__c = System.today(),
                                     Proposed_End_Date__c = System.today().addDays(2),
                                     Type__c = 'Expansion',
                                     Payment_Terms__c = paymentTermObject.Id,
                                     OpportunityId = opportunityObject.Id,
                                     Pricebook2Id = Test.getStandardPricebookId());
        insert quoteObject;
        Quote_Revision__c revisionObj = new Quote_Revision__c(Quote__c = quoteObject.Id,
                                                              Total_Best_Rate__c = 300,
                                                              Total_Offered_Price__c = 500
                                                            );
        insert revisionObj;
        
        Product2 prod = new Product2(Name = 'testProd',isActive = true,Unique_Key__c = 'pricingEngineTestProd' );
        insert prod;
        
        PricebookEntry pbe = new PricebookEntry(isActive = true,UnitPrice = 100,Product2Id = prod.Id,
                                                Pricebook2Id = Test.getStandardPricebookId(),CurrencyIsoCode = 'AED');
        insert pbe;
        
        QuoteLineItem qliObject = new QuoteLineItem(QuoteId = quoteObject.Id,
                                                    Best_Rate__c = 100,
                                                    Offer_Price__c = 80,
                                                    PricebookEntryId = pbe.Id,
                                                    Quantity = 1.00,
                                                    UnitPrice = 100,
                                                    Start_Date__c = Date.Today() + 120,
                                                    End_Date__c = Date.Today() + 120 + 365,
                                                    Type__c = 'Normal',
                                                    Area__c = 1000,
                                                    Transactional_Unit__c = 'Sqft',
                                                    Quote_Revision__c = revisionObj.Id,
                                                    Product2Id = prod.Id);
        insert qliObject;
        
        opportunityObject.SyncedQuoteId = quoteObject.Id;
		update opportunityObject;
    }
    
	@isTest
    public static void createAndGetChildOpportunityTest(){
        Opportunity opportunityObject = [SELECT Id FROM Opportunity WHERE Name =: 'Test Opportunity' LIMIT 1];
        Test.startTest();
        GetChildOpportunity.createAndGetChildOpportunity(opportunityObject.Id);
        Test.stopTest();
    }
    
    @isTest
    public static List<Quote> getQuoteRecordTest(){
         Opportunity opportunityObject = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        List<Quote> quoteList = [SELECT Id FROM Quote WHERE Name = 'Test Quote' AND OpportunityId = :opportunityObject.Id LIMIT 1];
        Test.startTest();
        GetChildOpportunity.getQuoteRecord(opportunityObject.Id);
        Test.stopTest();
        return quoteList;
    }
    
    @isTest
    public static List<QuoteLineItem> getQuoteLineItemRecordTest(){
        Quote quoteObject = [SELECT Id FROM Quote WHERE Name = 'Test Quote' LIMIT 1];
        List<QuoteLineItem> qliList = [SELECT Id FROM QuoteLineItem WHERE QuoteId = :quoteObject.Id LIMIT 1];
        
        Test.startTest();
        GetChildOpportunity.getQuoteLineItemRecord(quoteObject.Id);
        Test.stopTest();
        return qliList;
    }
}