src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License_Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Business_Park__c.object
<CustomObject>
    <description>Object to store Business Parks. Business Parks are managed manually in Salesforce, with Oracle being the master.</description>
    <fields>
        <fullName>Business_Park_Yardi__c</fullName>
        <externalId>true</externalId>
        <label>Business Park (Yardi)</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Business Park</label>
    <nameField>
        <label>Business Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Leasing Contact</fullName>
                </value>
                <value>
                    <fullName>Licensee Contact</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Alternate Payee</fullName>
                </value>
                <value>
                    <fullName>Authorized Signatory</fullName>
                </value>
                <value>
                    <fullName>Focal Point</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Legal Representative</fullName>
                </value>
                <value>
                    <fullName>Manager Incharge</fullName>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>PRO</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>CollectionTeam</fullName>
                </value>
                <value>
                    <fullName>Licensing Contact</fullName>
                </value>
                <value>
                    <fullName>Individual Shareholder</fullName>
                </value>
                <value>
                    <fullName>Corporate Shareholder</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expansion_Separate_Amendment_Terms__c</fullName>
        <label>Expansion Separate Amendment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>Combined Rates and Dates</label>
                </value>
                <value>
                    <fullName>-1</fullName>
                    <label>Separate Rates and Dates</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Downsize</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <formula>Unit__r.Building__r.Business_Park__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Park</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DDA</fullName>
                </value>
                <value>
                    <fullName>AXS</fullName>
                </value>
                <value>
                    <fullName>Parking Cards</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <label>Unique Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>CCL_Sign_Date__c</fullName>
        <label>CCL Sign Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expansion_Separate_Amendment_Terms__c</fullName>
        <formula>TEXT(Opportunity.Expansion_Separate_Amendment_Terms__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expansion Separate Amendment Terms</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_End_Date__c</fullName>
        <label>Proposed End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <label>Proposed Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Downsize</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Best_Rate__c</fullName>
        <label>Best Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offer_Price__c</fullName>
        <label>Offer Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transactional_Unit__c</fullName>
        <label>Transactional Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sqft</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Grace Period</fullName>
                </value>
                <value>
                    <fullName>Revision</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QLIOverrideDeleteExtensionTest.cls
/**
 *  @description Test class for QLIOverrideDeleteExtension Controller
 *
 *  2019/08/27  Amruta K     First version
 *  
 */
@isTest
public class QLIOverrideDeleteExtensionTest {

    @testSetup
    public static void createData(){
        Business_Park__c bsp = new Business_Park__c(Name = 'D3',Business_Park_Yardi__c = 'D3');
        insert bsp;
        
        Account acc = new Account(Name='Test Account', License_Business_Park__c = bsp.Id );
        insert acc;
        
        Contact conObj = new Contact(LastName = 'Test Contact', AccountId = acc.Id);
        insert conObj;
        
        Opportunity opp = new Opportunity(Name = 'Test Opp' , AccountId = acc.Id , StageName = 'New',
                                          CloseDate = Date.newInstance(2019,7,2),
                                         Sub_Type__c = 'Expansion',CurrencyIsoCode = 'AED', Contact__c = conObj.Id,Business_Park__c = bsp.Id);
        insert opp;
        
        Opportunity opp1 = new Opportunity(Name = 'Test Opp1' , AccountId = acc.Id , StageName = 'New',
                                          CloseDate = Date.newInstance(2019,7,2), Type = 'Renewal', Parent_Opportunity__c = opp.Id,
                                         Sub_Type__c = 'Expansion',CurrencyIsoCode = 'AED', Contact__c = conObj.Id,Business_Park__c = bsp.Id,
                                          Expansion_Separate_Amendment_Terms__c = '0');
        insert opp1;
        
        Quote q = new Quote(Name = 'Test Quote',OpportunityId = opp.Id,CCL_Sign_Date__c = Date.today(),
                            Status = 'Draft',Type__c = 'Renewal', Proposed_Start_Date__c = Date.today(),
                            Proposed_End_Date__c = Date.today().addDays(90),Lease_Start_Date__c = Date.today(),
                            Pricebook2Id = Test.getStandardPricebookId(),Lease_End_Date__c = Date.today().addDays(90));
        insert q;
        
        Product2 prod = new Product2(Name = 'testProd',isActive = true,Unique_Key__c = 'pricingEngineTestProd' );
        insert prod;
        Product2 prod1 = new Product2(Name = 'testProd1',isActive = true,Unique_Key__c = 'pricingEngineTestProd1');
        insert prod1;
        // Test pricebook entry
        PricebookEntry pbe = new PricebookEntry(isActive = true,UnitPrice = 100,Product2Id = prod.Id,
                                                Pricebook2Id = Test.getStandardPricebookId(),CurrencyIsoCode = 'AED');
        insert pbe;
        PricebookEntry pbe1 = new PricebookEntry(
                IsActive = true,
                Product2Id = prod1.Id,
                Pricebook2Id = Test.getStandardPricebookId(),
                UnitPrice = 100
        );
        insert pbe1;
        
        QuoteLineItem qli = new QuoteLineItem(
                QuoteId = q.Id,
                Best_Rate__c = 10000,
                Offer_Price__c = 8000,
                PricebookEntryId = pbe1.Id,
                Quantity = 1,
                UnitPrice = 10000,
                Start_Date__c = Date.Today() + 120,
                End_Date__c = Date.Today() + 120 + 365,
                Type__c = 'Normal',
                Area__c = 1000,
                Transactional_Unit__c = 'Unit',
            	Product2Id = prod.Id
        );
        
        Quote q1 = new Quote(Name = 'Test Quote1',OpportunityId = opp1.Id,CCL_Sign_Date__c = Date.today(),
                            Status = 'Draft',Type__c = 'Renewal', Proposed_Start_Date__c = Date.today(),
                            Proposed_End_Date__c = Date.today().addDays(90),Lease_Start_Date__c = Date.today(),
                            Pricebook2Id = Test.getStandardPricebookId(),Lease_End_Date__c = Date.today().addDays(90));
        insert q1;
        
        Product2 prod11 = new Product2(Name = 'testProd1',isActive = true,Unique_Key__c = 'pricingEngineTestProd1' );
        insert prod11;
        Product2 prod12 = new Product2(Name = 'testProd12',isActive = true,Unique_Key__c = 'pricingEngineTestProd12');
        insert prod12;
        // Test pricebook entry
        PricebookEntry pbe11 = new PricebookEntry(isActive = true,UnitPrice = 100,Product2Id = prod11.Id,
                                                Pricebook2Id = Test.getStandardPricebookId(),CurrencyIsoCode = 'AED');
        insert pbe11;
        PricebookEntry pbe12 = new PricebookEntry(
                IsActive = true,
                Product2Id = prod12.Id,
                Pricebook2Id = Test.getStandardPricebookId(),
                UnitPrice = 100
        );
        insert pbe12;
        
        QuoteLineItem qli2 = new QuoteLineItem(
                QuoteId = q1.Id,
                Best_Rate__c = 10000,
                Offer_Price__c = 8000,
                PricebookEntryId = pbe12.Id,
                Quantity = 1,
                UnitPrice = 10000,
                Start_Date__c = Date.Today() + 120,
                End_Date__c = Date.Today() + 120 + 365,
                Type__c = 'Normal',
                Area__c = 1000,
                Transactional_Unit__c = 'Unit',
            	Product2Id = prod.Id
        );

        List<QuoteLineItem> quoteLineItemsList= new List<QuoteLineItem>();
        quoteLineItemsList.add(qli);
        quoteLineItemsList.add(qli2);
        
       	insert quoteLineItemsList;
    }
    
    /* Method to test Error message if Opportunity Type is not Renewal & display error*/
    @isTest
    public static void testCheckOpportunityForError() {
        List<QuoteLineItem> qliLst = [SELECT Id,Quote.Opportunity.Type FROM QuoteLineItem
                                      WHERE Quote.Opportunity.Type = 'Renewal'];
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(qliLst[0]);
        QLIOverrideDeleteExtension qliObj = new QLIOverrideDeleteExtension(sc);
        qliObj.displayError = false;
        qliObj.checkOpportunity();
        Test.stopTest();
                
        System.assertEquals(qliObj.displayError, true);
        
    }
    /* Method to test Success message if Opportunity Type is not Renewal & delete the record*/
    @isTest
    public static void testCheckOpportunityForSuccess() {
        List<QuoteLineItem> qliLst = [SELECT Id,Quote.Opportunity.Type FROM QuoteLineItem];
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(qliLst[0]);
        QLIOverrideDeleteExtension qliObj = new QLIOverrideDeleteExtension(sc);
        qliObj.displaySuccess = false;
        qliObj.checkOpportunity();
        Test.stopTest();
        List<QuoteLineItem> qliLstDeleted = [SELECT Id,Quote.Opportunity.Type FROM QuoteLineItem
                                      WHERE Quote.Opportunity.Type != 'Renewal'];
		System.assertEquals(qliObj.displaySuccess, true);
        System.assertEquals(qliLstDeleted.Size(), 0);
    }
}