src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Document__c.object
<CustomObject>
    <description>Custom object used as a placeholder to associate files with records. This object has a lookup to Account, and the rest of the relationships managed using a Lightning component.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Signed Lease Agreement</fullName>
                </value>
                <value>
                    <fullName>Tenant Statement</fullName>
                </value>
                <value>
                    <fullName>Credit Note</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Rent Increase Notifications</fullName>
                </value>
                <value>
                    <fullName>Final Settlements</fullName>
                </value>
                <value>
                    <fullName>Collection</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Unit Takeover Form</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Lease Agreement</fullName>
                </value>
                <value>
                    <fullName>Lease Agreement -Special Terms</fullName>
                </value>
                <value>
                    <fullName>PSA with Visa Matrix Ready for Collection</fullName>
                </value>
                <value>
                    <fullName>New Lease -Ready for Collection</fullName>
                </value>
                <value>
                    <fullName>New Lease -Ready for collection-7Reminde</fullName>
                </value>
                <value>
                    <fullName>New Lease -Ready for collection-14Remind</fullName>
                </value>
                <value>
                    <fullName>New Lease -Ready for Colllection-21Remin</fullName>
                </value>
                <value>
                    <fullName>New Lease-Space Leased Notification</fullName>
                </value>
                <value>
                    <fullName>Printed Lease Agreement</fullName>
                </value>
                <value>
                    <fullName>Reminder Letter 1</fullName>
                </value>
                <value>
                    <fullName>Reminder Letter 2</fullName>
                </value>
                <value>
                    <fullName>Reminder Letter 3</fullName>
                </value>
                <value>
                    <fullName>Lease Doc</fullName>
                </value>
                <value>
                    <fullName>Lease Amendment</fullName>
                </value>
                <value>
                    <fullName>Audited Sales Report</fullName>
                </value>
                <value>
                    <fullName>First Inspection Report</fullName>
                </value>
                <value>
                    <fullName>Second Inspection Report</fullName>
                </value>
                <value>
                    <fullName>FILE NOTE</fullName>
                </value>
                <value>
                    <fullName>Sublease Lease Agreement</fullName>
                </value>
                <value>
                    <fullName>Second Amendment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_link__c</fullName>
        <label>Public link</label>
        <type>Url</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FileHandlerTest.cls
@istest
public class FileHandlerTest {
    private static Id accountId;
    
    @testsetup
    private static void testData()
    {
        TestDataFactory.getAccountWithContact();
        accountId = [Select id from account where name like'%test account%' limit 1].id;
        Document__c doc = new Document__c(name = 'Test 1', Account__c = accountId);
        Document__c doc1 = new Document__c(name = 'Test 2', Account__c = accountId);
        insert new List<Document__c>{doc, doc1};
            
            
            }
    
    @istest
    private static void posFileTest()
    {
        String jsonreq = '{"Params":{"ParentId":"'+accountId+'","FileName":"test file","FileType":"jpg","Base64String":"1257782001-snbjhsoasjl","Category":"Legal","Description":"testing"}}';
        Map<String, String> mparams= new Map<String, String>{'ParentId'=>accountId,
            'FileName'=> 'test file','FileType'=>'jpg','Base64String'=>EncodingUtil.base64encode(blob.valueOf('1257782001-snbjhsoasjl')),'Category'=>'Legal','Description'=>'testing'
            };
                Test.setMock(HttpCalloutMock.class, new DDAIntegrationMock());
        // Test.setMock(HttpCalloutMock.class, new NewRenewLeaseMockResponse(''));
        
        test.startTest();
        FilesHandler.doPost(mparams);
        test.stopTest();
        
    }
    @istest
    private static void getFileTest()
    {	
        
        // Document__c doc = new Document__c(name = 'Test 1', Public_link__c = 'test.com',Category__c= 'Legal',Description__c='test');
        //insert doc;
        // Document__c query = [SELECT   Id, Name,Public_link__c,Category__c, Description__c FROM Document__c  Where Id =:doc.Id];
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/files/'; 
        req.addParameter('Id', accountId);
        req.httpMethod = 'GET'; 
        RestContext.request = req;
        
        RestContext.response = res;
        
        //Test.setMock(HttpCalloutMock.class, new DDAIntegrationMock());
        Test.setMock(HttpCalloutMock.class, new NewRenewLeaseMockResponse(''));
        
        test.startTest();
        FilesHandler.doGet();
        test.stopTest();
        
    }
    @istest
    private static void getAllDocuments()
    {
        test.startTest();
        FilesHandler.getAllDocuments('ParentId');
        test.stopTest();
    }
}