src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery_Location__c</fullName>
        <label>Delivery Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Zone__c</fullName>
        <label>Delivery Zone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ORACLE_PARTY_ID__c</fullName>
        <externalId>true</externalId>
        <label>ORACLE PARTY ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Courier_Request__c.object
<CustomObject>
    <description>Object used to track Courier Requests as part of the Leasing module.</description>
    <fields>
        <fullName>AXS_Request_Id__c</fullName>
        <externalId>true</externalId>
        <label>AXS Request Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agreement_Num__c</fullName>
        <label>Agreement#</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Airway_Bill_Number__c</fullName>
        <label>Airway Bill Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building_Name__c</fullName>
        <label>Building Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Location__c</fullName>
        <label>Delivery Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Zone__c</fullName>
        <label>Delivery Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>D3</fullName>
                </value>
                <value>
                    <fullName>DI</fullName>
                </value>
                <value>
                    <fullName>DIAC</fullName>
                </value>
                <value>
                    <fullName>DIC</fullName>
                </value>
                <value>
                    <fullName>DKP</fullName>
                </value>
                <value>
                    <fullName>DMC</fullName>
                </value>
                <value>
                    <fullName>DOC</fullName>
                </value>
                <value>
                    <fullName>DPC</fullName>
                </value>
                <value>
                    <fullName>DSC</fullName>
                </value>
                <value>
                    <fullName>DSP</fullName>
                </value>
                <value>
                    <fullName>In5</fullName>
                </value>
                <value>
                    <fullName>TECOM</fullName>
                </value>
                <value>
                    <fullName>IMPZ</fullName>
                </value>
                <value>
                    <fullName>DOZ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lease Document Delivery</fullName>
                </value>
                <value>
                    <fullName>Executed Lease Documents Delivery</fullName>
                </value>
                <value>
                    <fullName>Lease Document Collection (Along with Cheque)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Updated_On__c</fullName>
        <label>Last Updated On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Number_Of_Cheques__c</fullName>
        <label>Number Of Cheques</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Oracle_Party_ID__c</fullName>
        <label>Oracle Party ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Mobile__c</fullName>
        <label>Reference Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Service_Request_Number__c</fullName>
        <externalId>true</externalId>
        <label>Service Request Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>at dispatcher</fullName>
                </value>
                <value>
                    <fullName>At Hub</fullName>
                </value>
                <value>
                    <fullName>Out for Delivery</fullName>
                </value>
                <value>
                    <fullName>Out for Collection</fullName>
                </value>
                <value>
                    <fullName>Return to Sender</fullName>
                </value>
                <value>
                    <fullName>Allotted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Courier Request</label>
    <nameField>
        <displayFormat>CRN-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courier Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AG_Number__c</fullName>
        <displayFormat>AG-{000000}</displayFormat>
        <label>AG Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Building_Name__c</fullName>
        <label>Building</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Payment_Term__c.object
<CustomObject>
    <description>Object used to capture Payment Term information, to be used on Quotes.</description>
    <fields>
        <fullName>No_of_Installments__c</fullName>
        <label>No of Installments</label>
        <summaryForeignKey>Payment_Term_Detail__c.Payment_Term__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Payment Terms</label>
    <nameField>
        <label>Payment Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <formula>Opportunity.Contact__r.FirstName + &quot; &quot; + Opportunity.Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready To Sync</fullName>
                </value>
                <value>
                    <fullName>Synched</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Payment Terms</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CourierDocCollection.cls
@RestResource(urlMapping='/cdcollection/*')
global with sharing class CourierDocCollection {

    @HttpGet
    global static void getOpNoSchedules() {
        List<DocCollResponse> resps = new List<DocCollResponse>();
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        try{
            String oracleId = req.params.get('oracleId');
            if(oracleId!=null && oracleId!=''){
                for(Quote quote : [SELECT Id,Account.ORACLE_PARTY_ID__c,Opportunity.AG_Number__c,Status,Payment_Terms__r.No_of_Installments__c,Category__c FROM Quote WHERE Account.ORACLE_PARTY_ID__c =: OracleID AND Status = 'CCL Acceptance']){
                    DocCollResponse resp = new DocCollResponse();
                    resp.agNo =  ''+quote.Opportunity.AG_Number__c==null?'':quote.Opportunity.AG_Number__c;
                    resp.noChqs = quote.Payment_Terms__r.No_of_Installments__c==null?'':''+quote.Payment_Terms__r.No_of_Installments__c;
                    resp.oracleId = ''+oracleId;
                    resp.category = ''+quote.Category__c==null?'':quote.Category__c;
                    resp.isSuccess = true;
                    resp.errorMessage = '';
                    resps.add(resp);
                }
                String respStr = JSON.serialize(resps);
                System.debug('respStr :- '+respStr);
                res.responseBody = Blob.valueOf(respStr);
            }else{
                DocCollResponse resp = new DocCollResponse();
                resp.isSuccess = false;
                resp.errorMessage = 'Required parameter missing : Oracle Party ID';
                String respStr = JSON.serialize(new List<DocCollResponse>{resp});
                res.responseBody = Blob.valueOf(respStr);
            }
        }catch(Exception ex){
            DocCollResponse resp = new DocCollResponse();
            resp.isSuccess = false;
            resp.errorMessage = ex.getStackTraceString();
            String respStr = JSON.serialize(new List<DocCollResponse>{resp});
            res.responseBody = Blob.valueOf(respStr);
        }
    }
    
    public class DocCollResponse{
        public String agNo;
        public String noChqs;
        public String oracleId;
        public String category;
        public Boolean isSuccess;
        public String errorMessage;
    }
    
    @HttpPost
    global static void createDocCollServReq() {
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;
        System.debug('Request JSON : '+req.requestBody.toString());
        CourierDocCollection ci = (CourierDocCollection) System.JSON.deserialize(req.requestBody.toString(), CourierDocCollection.class);  
        System.debug('CourierDocCollection============>> ' + ci);
        Set<String> srNums = new Set<String>();
        Map<String,SRRequest> srMap = new Map<String,SRRequest>();
        for(SRRequest sr : ci.reqs){
            if(sr.agNo!=null && sr.agNo!='' && sr.SRN!=null && sr.SRN!=''){
                List<String> agNums = new List<String>();
                String agChqStr = sr.agNo.replace(',','_');
                agNums = agChqStr.split('_');
                Map<String,Decimal> noOfSchPerAg = new Map<String,Decimal>();
                for(String str : agNums){
                    List<String> agChqs = new List<String>();
                    agChqs = str.split(':');
                    noOfSchPerAg.put(agChqs[0],Decimal.valueOf(agChqs[1]));
                }
                if(!agNums.isEmpty()){
                    Courier_Request__c cReq = new Courier_Request__c();
                    cReq.Service_Request_Number__c = sr.SRN;
                    cReq.Airway_Bill_Number__c = sr.AWB=='null'?'':sr.AWB;
                    cReq.Status__c = sr.delStatus;
                    cReq.Source_System__c = sr.sourceSystem==null?'CorpCRM':sr.sourceSystem;
                    String timeSt = sr.timeStamp;
                    cReq.Last_Updated_On__c = DateTime.newInstance(Long.valueOf(timeSt));
                    cReq.Integration_Status__c = 'Ready';
                    if(sr.delStatus.equalsIgnoreCase('at dispatcher')){
                        //cReq.At_Dispatcher_Date__c = DateTime.newInstance(Long.valueOf(timeSt));
                    }else if(sr.delStatus.equalsIgnoreCase('At Hub')){
                        //cReq.At_Hub_Date__c = DateTime.newInstance(Long.valueOf(timeSt));
                    }else if(sr.delStatus.equalsIgnoreCase('Out for Delivery')){
                        //cReq.Out_For_Delivery_Date__c = DateTime.newInstance(Long.valueOf(timeSt));
                    }else if(sr.delStatus.equalsIgnoreCase('Delivered')){
                        //cReq.Doc_Delivered_Date__c = DateTime.newInstance(Long.valueOf(timeSt));
                    }else if(sr.delStatus.equalsIgnoreCase('Return to Sender')){
                        //cReq.Return_to_Sender_Date__c = DateTime.newInstance(Long.valueOf(timeSt));
                    }else if(sr.delStatus.equalsIgnoreCase('Allotted')){
                        //cReq.Doc_Allotted_Date__c = DateTime.newInstance(Long.valueOf(timeSt));
                    }else if(sr.delStatus.equalsIgnoreCase('Out For Collection')){
                        //cReq.Out_For_Collection_Date__c = DateTime.newInstance(Long.valueOf(timeSt));
                    }
                    cReq.Account_Name__c = sr.acName;
                    cReq.Contact_Name__c = sr.conName;
                    cReq.Oracle_Party_ID__c = sr.oracleId;
                    cReq.Document_Type__c = sr.docType;
                    cReq.Reference_Mobile__c = sr.refMobile;
                    cReq.Delivery_Zone__c = sr.delZone;
                    cReq.Building_Name__c = sr.bldngName;
                    cReq.Delivery_Location__c = sr.delLoc;
                    cReq.Notes__c = sr.notes;
                    cReq.AXS_Request_Id__c = sr.axsReqId;
                    cReq.Agreement_Num__c = sr.agNo;
                    cReq.Number_Of_Cheques__c = Decimal.valueOf(sr.noCheques);
                    System.Savepoint sp = Database.setSavepoint();
                    try{
                        insert cReq;
                        SRResponse respo = new SRResponse();
                        respo.respMsg = 'Success';
                        respo.respCode = '0';
                        String respStr = JSON.serialize(respo);
                        res.responseBody = Blob.valueOf(respStr);
                    }catch(Exception ex){
                        Database.rollback(sp);
                        SRResponse respo = new SRResponse();
                        respo.respMsg = '#Error : '+ex.getMessage()+' #Line Number : '+ex.getLineNumber();
                        respo.respCode = '1';
                        String respStr = JSON.serialize(respo);
                        res.responseBody = Blob.valueOf(respStr);
                    }
                }
            }else{
                SRResponse respo = new SRResponse();
                if(sr.agNo==null && sr.agNo=='' && sr.SRN!=null && sr.SRN!=''){respo.respMsg = 'Required field "Opportunity Id" is missing.';
                }else if(sr.agNo!=null && sr.agNo!='' && sr.SRN==null && sr.SRN==''){respo.respMsg = 'Required field "Service Request Number" is missing.';
                }else if(sr.agNo==null && sr.agNo=='' && sr.SRN==null && sr.SRN==''){respo.respMsg = 'Required fields "Service Request Number" and "Opportunity Id" are missing.';
                }
                respo.respCode = 'DE_01';
                String respStr = JSON.serialize(respo);
                res.responseBody = Blob.valueOf(respStr);
            }
        }
    }
    
    public List<SRRequest> reqs;
    
    public class SRRequest{
        public String SRN;
        public String AWB;
        public String status;
        public String delStatus;
        public String timeStamp;
        public String acName;
        public String conName;
        public String oracleId;
        public String docType;
        public String refMobile;
        public String delZone;
        public String bldngName;
        public String delLoc;
        public String notes;
        public String axsReqId;
        public String noCheques;
        public String agNo;
        public String sourceSystem;
    }
    
    public class SRResponse{
        public String SRN;
        public String respMsg;
        public String respCode;
        public String AWB;
        public String agNum;
    }
}