src/objects/Building__c.object
<CustomObject>
    <description>This object is used to store all the buildings from Yardi into Salesforce. Buildings are linked to plots, and Units are linked to buildings.</description>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Status__c</fullName>
        <label>Development Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Developed</fullName>
                </value>
                <value>
                    <fullName>Under Development</fullName>
                </value>
                <value>
                    <fullName>Undeveloped</fullName>
                </value>
                <value>
                    <fullName>Construction on hold</fullName>
                </value>
                <value>
                    <fullName>Construction Resumed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Code_YARDI__c</fullName>
        <externalId>true</externalId>
        <label>Property Code-YARDI</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Type__c</fullName>
        <label>Lease Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>land</fullName>
                </value>
                <value>
                    <fullName>office</fullName>
                </value>
                <value>
                    <fullName>retail</fullName>
                </value>
                <value>
                    <fullName>str</fullName>
                </value>
                <value>
                    <fullName>annland</fullName>
                </value>
                <value>
                    <fullName>lhland</fullName>
                </value>
                <value>
                    <fullName>unitsale</fullName>
                </value>
                <value>
                    <fullName>cowork</fullName>
                </value>
                <value>
                    <fullName>PMLA</fullName>
                    <isActive>false</isActive>
                    <label>PMLA</label>
                </value>
                <value>
                    <fullName>PMS</fullName>
                    <isActive>false</isActive>
                    <label>PMS</label>
                </value>
                <value>
                    <fullName>TECOM</fullName>
                    <isActive>false</isActive>
                    <label>TECOM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renew</fullName>
                </value>
                <value>
                    <fullName>Modification</fullName>
                </value>
                <value>
                    <fullName>Contraction</fullName>
                    <isActive>false</isActive>
                    <label>Contraction</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Payment_Term__c.object
<CustomObject>
    <description>Object used to capture Payment Term information, to be used on Quotes.</description>
    <fields>
        <fullName>Number_Of_Payments__c</fullName>
        <label>Number Of Payments</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payment Terms</label>
    <nameField>
        <label>Payment Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Park__c</fullName>
        <formula>Unit__r.Building__r.Business_Park__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Park</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Term</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Products (Payment Term)</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Terms</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DDA</fullName>
                </value>
                <value>
                    <fullName>AXS</fullName>
                </value>
                <value>
                    <fullName>Parking Cards</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCL_Sign_Date__c</fullName>
        <label>CCL Sign Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grace_Period_Mechanism__c</fullName>
        <label>Grace Period Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>initial</fullName>
                </value>
                <value>
                    <fullName>every</fullName>
                </value>
                <value>
                    <fullName>end</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period_Period__c</fullName>
        <label>Grace Period (period)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>days</fullName>
                </value>
                <value>
                    <fullName>months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <label>Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_Of_Payments__c</fullName>
        <label>Number Of Payments</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <formula>TEXT(Opportunity.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Payment Terms</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_End_Date__c</fullName>
        <label>Proposed End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <label>Proposed Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Downsize</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Grace_Period_Mechanism__c</fullName>
        <label>Offered Grace Period Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>initial</fullName>
                </value>
                <value>
                    <fullName>every</fullName>
                </value>
                <value>
                    <fullName>end</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <inlineHelpText>If &apos;Offered Grace Period&apos; is blank, the Grace Period listed at the Quote will be used for price calculation.</inlineHelpText>
        <label>Offered Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Grace Period</fullName>
                </value>
                <value>
                    <fullName>Revision</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <description>Object used to store Unit Inventory mastered in Yardi on SF.</description>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Business_Park__c</fullName>
        <formula>Building__r.Business_Park__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Park</label>
        <type>Text</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BundleUtilsTest.cls
@isTest
public with sharing class BundleUtilsTest {

	@testSetup
	public static void setupTests(){
		// Create Business Park
		Business_Park__c businessPark = new Business_Park__c();
		insert businessPark;

		// Create opportunity
		Opportunity opp = new Opportunity(
			Name = 'Test Opp',
			StageName = 'Prospecting',
			CloseDate = System.today(),
			Lease_Type__c = 'office',
			Business_Park__c = businessPark.Id,
			Opportunity_Type__c = 'New',
			Pricebook2Id = Test.getStandardPricebookId());
		insert opp;

		// Create payment term
		Payment_Term__c pTerm = new Payment_Term__c(Number_Of_Payments__c = 2);
		insert pTerm;
		
		// Create Quote
		Quote quo = new Quote(
			Name = 'Test Quote',
			OpportunityId = opp.Id,
			CCL_Sign_Date__c = System.today(),
			Pricebook2Id = Test.getStandardPricebookId(),
			Type__c = 'New',
			Lease_Start_Date__c = System.today(),
			Lease_End_Date__c = System.today().addDays(10),
			Payment_Terms__c = pTerm.Id,
			Grace_Period_Mechanism__c = 'initial',
			Grace_Period_Period__c = 'days',
			Grace_Period__c = 5,
			Proposed_Start_Date__c = System.today(),
			Proposed_End_Date__c = System.today().addMonths(5));
		insert quo;

		// Create building
		Building__c building = new Building__c(
			Development_Status__c = 'Developed',
			Property_Code_YARDI__c = 'XXXX',
			Property__c = 'Office',
			Ownership_Type__c = 'TECOM Owned');
		insert building;

		// Insert unit
		Unit__c unit = new Unit__c(
			Transactional_Unit__c = 'Sq.Ft',
			Building__c = building.Id,
			Unit_Code_YARDI__c='test');
		insert unit;

		// Insert product
		Product2 prod = new Product2(
			Name = 'Product X', 
			ProductCode = 'Pro-X', 
			isActive = true,
			Unit__c = unit.Id);
		insert prod;

		// Create PriceBookEntry
		PricebookEntry pbEntry = new PricebookEntry(
			Pricebook2Id = Test.getStandardPricebookId(), 
			Product2Id = prod.Id, 
			UnitPrice = 100.00, 
			IsActive = true);
		insert pbEntry;

		// Create Parent Quoteline
		QuotelineItem parentLineItem = new QuoteLineItem(
			Quantity = 1,
			QuoteId = quo.Id, 
			PricebookEntryId = pbEntry.Id, 
			UnitPrice = 100, 
			Product2Id = prod.Id,
			Type__c = 'Normal');
		insert parentLineItem;

		// Create Child Quoteline
		QuotelineItem firstChildLineItem = new QuoteLineItem(
			Quantity = 1,
			QuoteId = quo.Id, 
			PricebookEntryId = pbEntry.Id, 
			UnitPrice = 100, 
			Product2Id = prod.Id,
			Parent_Quote_Line_Item__c = String.valueOf(parentLineItem.Id),
			Type__c = 'Normal');
		insert firstChildLineItem;

		// Create Child Quoteline
		QuotelineItem secondChildLineItem = new QuoteLineItem(
			Quantity = 1,
			QuoteId = quo.Id, 
			PricebookEntryId = pbEntry.Id, 
			UnitPrice = 100, 
			Product2Id = prod.Id,
			Parent_Quote_Line_Item__c = String.valueOf(parentLineItem.Id),
			Type__c = 'Normal');
		insert secondChildLineItem;
	}

	@isTest
	public static void testDeleteNormalChildLineItemsPositive(){
		Integer lineItemsCount = [SELECT COUNT() FROM QuotelineItem WHERE Quote.Name = 'Test Quote'];
		// Expected: 4 as there were 4 line items created in the set up
		System.assertEquals(3, lineItemsCount);

		// Query for line items
		List<QuotelineItem> lineItems = [SELECT Id FROM QuotelineItem WHERE Type__c = 'Normal' AND Parent_Quote_Line_Item__c = null];

		// Delete parent line
		delete lineItems;

		lineItemsCount = [SELECT COUNT() FROM QuotelineItem];
		// Expected: 0 as the child records should have been deleted 
		System.assertEquals(0, lineItemsCount);
	}
}