src/objects/Building__c.object
<CustomObject>
    <description>This object is used to store all the buildings from Yardi into Salesforce. Buildings are linked to plots, and Units are linked to buildings.</description>
    <fields>
        <fullName>Building_Code__c</fullName>
        <externalId>true</externalId>
        <label>Building Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Status__c</fullName>
        <label>Development Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Developed</fullName>
                </value>
                <value>
                    <fullName>Under Development</fullName>
                </value>
                <value>
                    <fullName>Undeveloped</fullName>
                </value>
                <value>
                    <fullName>Construction on hold</fullName>
                </value>
                <value>
                    <fullName>Construction Resumed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ownership_Type__c</fullName>
        <label>Ownership Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TECOM Owned</fullName>
                </value>
                <value>
                    <fullName>PMLA</fullName>
                </value>
                <value>
                    <fullName>DED - PMS</fullName>
                </value>
                <value>
                    <fullName>TECOM - PMS</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plot</label>
        <referenceTo>Plot__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Code_YARDI__c</fullName>
        <externalId>true</externalId>
        <label>Property Code-YARDI</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Mixed</fullName>
                </value>
                <value>
                    <fullName>Parking</fullName>
                </value>
                <value>
                    <fullName>Land</fullName>
                </value>
                <value>
                    <fullName>Confirm values</fullName>
                    <isActive>false</isActive>
                    <label>Confirm values</label>
                </value>
                <value>
                    <fullName>DED - PMS</fullName>
                    <isActive>false</isActive>
                    <label>DED - PMS</label>
                </value>
                <value>
                    <fullName>PMLA</fullName>
                    <isActive>false</isActive>
                    <label>PMLA</label>
                </value>
                <value>
                    <fullName>TECOM - PMS</fullName>
                    <isActive>false</isActive>
                    <label>TECOM - PMS</label>
                </value>
                <value>
                    <fullName>TECOM Owned</fullName>
                    <isActive>false</isActive>
                    <label>TECOM Owned</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Business_Park__c.object
<CustomObject>
    <description>Object to store Business Parks. Business Parks are managed manually in Salesforce, with Oracle being the master.</description>
    <fields>
        <fullName>Business_Park_Code__c</fullName>
        <externalId>true</externalId>
        <label>Business Park Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Business_Park_Yardi__c</fullName>
        <externalId>true</externalId>
        <label>Business Park (Yardi)</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Business Park</label>
    <nameField>
        <label>Business Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plot__c.object
<CustomObject>
    <description>Object used to capture Plot information, and this is linked to Business Parks. The inventory is managed in Yardi and pushed to Salesforce.</description>
    <fields>
        <fullName>Area_sqft__c</fullName>
        <label>Area sqft</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Park_Yardi__c</fullName>
        <description>Short name for business park from Yardi</description>
        <label>Business Park Yardi</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Plots</relationshipLabel>
        <relationshipName>Plots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Status__c</fullName>
        <label>Development Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Under Development</fullName>
                </value>
                <value>
                    <fullName>Undeveloped</fullName>
                </value>
                <value>
                    <fullName>Construction on hold</fullName>
                </value>
                <value>
                    <fullName>Construction Resumed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
                <value>
                    <fullName>Status TBC</fullName>
                    <isActive>false</isActive>
                    <label>Status TBC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plot_Code_YARDI__c</fullName>
        <externalId>true</externalId>
        <label>Plot Code YARDI</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Plot_Name_YARDI__c</fullName>
        <label>Plot Name YARDI</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sector_Name__c</fullName>
        <label>Sector Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available - Sale</fullName>
                </value>
                <value>
                    <fullName>Available - Lease</fullName>
                </value>
                <value>
                    <fullName>Pre Sale</fullName>
                </value>
                <value>
                    <fullName>Pre Lease</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Granted</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Plot</label>
    <nameField>
        <label>Plot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Price_Rule__c.object
<CustomObject>
    <description>Object used to define price rules that will determine the best price on QLI based on physical, commercial and transactional attributes.</description>
    <fields>
        <fullName>Business_Park_Value__c</fullName>
        <label>Business Park Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price Rule</label>
    <nameField>
        <label>Price Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PriceRulePhysicalTabControllerTest.cls
/**
 *  @description Test Class for PriceRulePhyicalTabController class
 *
 *  2019-16-07 Anshul Garg
*/
@isTest
public class PriceRulePhysicalTabControllerTest {
    @testsetup public static void createTestData(){
        Price_Rule__c prIns = new Price_Rule__c(Name = 'Test PR');
        insert prIns;
        Business_Park__c bsp = new Business_Park__c(Name = 'TestBP1',Business_Park_Yardi__c = 'Test',Business_Park_Code__c ='TestBP1');
        insert bsp;
        Business_Park__c bsp2 = new Business_Park__c(Name = 'TestBP2',Business_Park_Yardi__c = 'Test2',Business_Park_Code__c ='TestBP2');
        insert bsp2;
        Business_Park__c bsp3 = new Business_Park__c(Name = 'TestBP3',Business_Park_Yardi__c = 'Test3',Business_Park_Code__c ='TestBP3');
        insert bsp3;
        Plot__c plot = new Plot__c(Name = 'testPlot',Plot_Code_YARDI__c = 'pricingEngineTestPlot',Area_sqft__c = 100.0,
            					   Business_Park__c = bsp2.Id,Plot_Name_YARDI__c = 'pricingEngineTestPlotName',
            					   Type__c = 'type',Status__c = 'Available - Sale',Sector_Name__c = 'sectorName');
        insert plot;
        Building__c build1 = new Building__c(Plot__c = plot.Id,Name = 'TestBuilding1' ,Ownership_Type__c = 'TECOM Owned',Building_Code__c ='TestBuilding1',
                                           Development_Status__c = 'Under Development',Property_Code_YARDI__c ='d3_cb',Property__c ='Parking');
        insert build1;
        Building__c build2 = new Building__c(Name = 'TestBuilding2' ,Ownership_Type__c = 'TECOM Owned',Business_Park__c = bsp3.Id,Building_Code__c ='TestBuilding2',
                                           Development_Status__c = 'Under Development',Property_Code_YARDI__c ='d3_cb1',Property__c ='Parking');
        insert build2;
    }
    
    public static testmethod void testGetBusinessParkList(){
        Test.startTest();
        String str = PriceRulePhysicalTabController.getBusinessParkList();
        Test.stopTest();
        System.assert(!String.isBlank(str));
    }
    
    public static testmethod void testGetBuildings(){
        List<Business_Park__c> bpList = [SELECT Id FROM Business_Park__c LIMIT 3];
        Test.startTest();
        String str1 = PriceRulePhysicalTabController.getBuildings(bpList[0].Id);
        String str2 = PriceRulePhysicalTabController.getBuildings(bpList[1].Id);
        String str3 = PriceRulePhysicalTabController.getBuildings(bpList[2].Id);
        Test.stopTest();
        System.assert(!String.isBlank(str1));
    }
    
    public static testmethod void testsaveValuesOnPriceRule(){
        Price_Rule__c prIns = [SELECT Id FROM Price_Rule__c LIMIT 1];
        String selectedBusinessPark = 'TestBP1;TestBP2';
        String selectedBuilding = 'TestBuilding1;TestBuilding2';
        Test.startTest();
        PriceRulePhysicalTabController.saveValuesOnPriceRule(prIns.Id, selectedBusinessPark, selectedBuilding);
        Test.stopTest();
        Price_Rule__c actualPR = [SELECT Id,Business_Park_Value__c FROM Price_Rule__c WHERE Id = :prIns.Id];
        System.assertEquals(selectedBusinessPark+';TestBP3', actualPR.Business_Park_Value__c);
    }
    
    public static testmethod void testgetSelectedRowsId(){
        Price_Rule__c prIns = [SELECT Id FROM Price_Rule__c LIMIT 1];
        String selectedBusinessPark = 'TestBP1;TestBP2';
        String selectedBuilding = 'TestBuilding1;TestBuilding2';
        Test.startTest();
        PriceRulePhysicalTabController.saveValuesOnPriceRule(prIns.Id, selectedBusinessPark, selectedBuilding);
        List<String> selectedValueList = PriceRulePhysicalTabController.getSelectedRowsId(prIns.Id);
        Test.stopTest();
        System.assertEquals(5, selectedValueList.size());
    }
}