src/objects/Building__c.object
<CustomObject>
    <description>This object is used to store all the buildings from Yardi into Salesforce. Buildings are linked to plots, and Units are linked to buildings.</description>
    <fields>
        <fullName>Building_Code__c</fullName>
        <externalId>true</externalId>
        <label>Building Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Status__c</fullName>
        <label>Development Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Developed</fullName>
                </value>
                <value>
                    <fullName>Under Development</fullName>
                </value>
                <value>
                    <fullName>Undeveloped</fullName>
                </value>
                <value>
                    <fullName>Construction on hold</fullName>
                </value>
                <value>
                    <fullName>Construction Resumed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ownership_Type__c</fullName>
        <label>Ownership Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TECOM Owned</fullName>
                </value>
                <value>
                    <fullName>PMLA</fullName>
                </value>
                <value>
                    <fullName>DED - PMS</fullName>
                </value>
                <value>
                    <fullName>TECOM - PMS</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plot</label>
        <referenceTo>Plot__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Code_YARDI__c</fullName>
        <externalId>true</externalId>
        <label>Property Code-YARDI</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Mixed</fullName>
                </value>
                <value>
                    <fullName>Parking</fullName>
                </value>
                <value>
                    <fullName>Land</fullName>
                </value>
                <value>
                    <fullName>Confirm values</fullName>
                    <isActive>false</isActive>
                    <label>Confirm values</label>
                </value>
                <value>
                    <fullName>DED - PMS</fullName>
                    <isActive>false</isActive>
                    <label>DED - PMS</label>
                </value>
                <value>
                    <fullName>PMLA</fullName>
                    <isActive>false</isActive>
                    <label>PMLA</label>
                </value>
                <value>
                    <fullName>TECOM - PMS</fullName>
                    <isActive>false</isActive>
                    <label>TECOM - PMS</label>
                </value>
                <value>
                    <fullName>TECOM Owned</fullName>
                    <isActive>false</isActive>
                    <label>TECOM Owned</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Business_Park__c.object
<CustomObject>
    <description>Object to store Business Parks. Business Parks are managed manually in Salesforce, with Oracle being the master.</description>
    <fields>
        <fullName>Business_Park_Code__c</fullName>
        <externalId>true</externalId>
        <label>Business Park Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Business Park</label>
    <nameField>
        <label>Business Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plot__c.object
<CustomObject>
    <description>Object used to capture Plot information, and this is linked to Business Parks. The inventory is managed in Yardi and pushed to Salesforce.</description>
    <fields>
        <fullName>Area_sqft__c</fullName>
        <label>Area sqft</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Plots</relationshipLabel>
        <relationshipName>Plots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Status__c</fullName>
        <label>Development Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Under Development</fullName>
                </value>
                <value>
                    <fullName>Undeveloped</fullName>
                </value>
                <value>
                    <fullName>Construction on hold</fullName>
                </value>
                <value>
                    <fullName>Construction Resumed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
                <value>
                    <fullName>Status TBC</fullName>
                    <isActive>false</isActive>
                    <label>Status TBC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plot_Code_YARDI__c</fullName>
        <externalId>true</externalId>
        <label>Plot Code YARDI</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Plot_Name_YARDI__c</fullName>
        <label>Plot Name YARDI</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sector_Name__c</fullName>
        <label>Sector Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available - Sale</fullName>
                </value>
                <value>
                    <fullName>Available - Lease</fullName>
                </value>
                <value>
                    <fullName>Pre Sale</fullName>
                </value>
                <value>
                    <fullName>Pre Lease</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Granted</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Plot</label>
    <nameField>
        <label>Plot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <description>Object used to store Unit Inventory mastered in Yardi on SF.</description>
    <fields>
        <fullName>Area_ft__c</fullName>
        <label>Area (ft²)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Business_Park__c</fullName>
        <formula>Building__r.Business_Park__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Park</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Soft Booked</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Sub_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Sub Category</label>
        <referenceTo>Unit_Sub_Category__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit_Category__c.object
<CustomObject>
    <description>Object used to capture Unit Categories (to align with Yardi) related to Asset Class.</description>
    <fields>
        <fullName>Asset_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Class</label>
        <referenceTo>Asset_Class__c</referenceTo>
        <relationshipLabel>Unit Categories</relationshipLabel>
        <relationshipName>Unit_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Unit Category</label>
    <nameField>
        <label>Unit Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit_Sub_Category__c.object
<CustomObject>
    <description>Object used to capture Unit Sub-Category against Units.</description>
    <fields>
        <fullName>Unit_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Category</label>
        <referenceTo>Unit_Category__c</referenceTo>
        <relationshipLabel>Unit Sub-Categories</relationshipLabel>
        <relationshipName>Unit_Sub_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Sub-Category</label>
    <nameField>
        <label>Unit Sub-Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Sub-Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UnitTriggerHelperTest.cls
/**
 *  @description Test class for UnitTriggerHelper
 *
 *  2019-08-19  Shraddha N    First version
 *  
 */

@isTest
public class UnitTriggerHelperTest {
    // Method to create test setup data.
	@isTest
    public static void test1(){
        String errorMessage = '';
        List<Unit__c> unitList = new List<Unit__c>();
        
        Business_Park__c businessParkObject = new Business_Park__c(
                Name = 'D3', Business_Park_Code__c = 'D3'
        );
        insert businessParkObject;
        
        Plot__c plotObject = new Plot__c(Name = 'testPlot',Plot_Code_YARDI__c = 'pricingEngineTestPlot',Area_sqft__c = 100.0,
            					   Business_Park__c = businessParkObject.Id,Plot_Name_YARDI__c = 'pricingEngineTestPlotName',
            					   Type__c = 'type',Status__c = 'Available - Sale',Sector_Name__c = 'sectorName');
        insert plotObject;
        
        Building__c buildingObejct = new Building__c(Plot__c = plotObject.Id,Name = 'Test Build 1' , Business_Park__c = businessParkObject.Id,
                                             Ownership_Type__c = 'TECOM Owned', Development_Status__c = 'Under Development',
                                             Property_Code_YARDI__c ='d3_cb',Property__c ='Parking', Building_Code__c = 'B-P1-1');
        insert buildingObejct;
        
        Asset_Class__c assetClassObject = new Asset_Class__c(Name = 'Commercial');
        insert assetClassObject;
        
        Unit_Category__c unitCategoryObject = new Unit_Category__c(Name = 'Office',
                                                                   Asset_Class__c = assetClassObject.Id);
        insert unitCategoryObject;

        Unit_Sub_Category__c unitSubCategoryObject = new Unit_Sub_Category__c(Name = 'Standard Office',
                                                                              Unit_Category__c = unitCategoryObject.Id
                                                                             );
        insert unitSubCategoryObject;
        
        Unit__c unitObject1 = new Unit__c(Name  ='Test Unit',Area_ft__c = 910,Building__c = buildingObejct.Id, Unit_Sub_Category__c = unitSubCategoryObject.Id,
                                 		  Unit_Code_YARDI__c = 'B106',Transactional_Unit__c ='Sqft', Floor_Number__c = 'Fifth Floor', Floor_Type__c = '05',
                                          Category_Combination__c = 'Commercial-Office-Standard Office');
       
        Test.startTest();
       
        insert unitObject1;
        unitObject1.Category_Combination__c = 'Test' ;
            
        try{
        	update unitObject1;
        } catch(Exception e){
            errorMessage = e.getMessage();
        }
        Test.stopTest();
        
        System.assertEquals(errorMessage.contains('Unable to find the unit sub category for the given combination.'), true);
    }
   
}