src/objects/Business_Park__c.object
<CustomObject>
    <description>Object to store Business Parks. Business Parks are managed manually in Salesforce, with Oracle being the master.</description>
    <fields>
        <fullName>Business_Park_Code__c</fullName>
        <externalId>true</externalId>
        <label>Business Park Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Business_Park_Yardi__c</fullName>
        <externalId>true</externalId>
        <label>Business Park (Yardi)</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Business Park</label>
    <nameField>
        <label>Business Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plot__c.object
<CustomObject>
    <description>Object used to capture Plot information, and this is linked to Business Parks. The inventory is managed in Yardi and pushed to Salesforce.</description>
    <fields>
        <fullName>Area_sqft__c</fullName>
        <label>Area sqft</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Park_Yardi__c</fullName>
        <description>Short name for business park from Yardi</description>
        <label>Business Park Yardi</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Plots</relationshipLabel>
        <relationshipName>Plots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plot_Code_YARDI__c</fullName>
        <externalId>true</externalId>
        <label>Plot Code YARDI</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Plot_Name_YARDI__c</fullName>
        <label>Plot Name YARDI</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sector_Name__c</fullName>
        <label>Sector Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link between plot and sector</description>
        <label>Sector</label>
        <referenceTo>Sector__c</referenceTo>
        <relationshipLabel>Plots</relationshipLabel>
        <relationshipName>Plots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available - Sale</fullName>
                </value>
                <value>
                    <fullName>Available - Lease</fullName>
                </value>
                <value>
                    <fullName>Pre Sale</fullName>
                </value>
                <value>
                    <fullName>Pre Lease</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Granted</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Plot</label>
    <nameField>
        <label>Plot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sector__c.object
<CustomObject>
    <description>To capture Sector information to allow for processing of parking eligibility.</description>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Sectors</relationshipLabel>
        <relationshipName>Sectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sector</label>
    <nameField>
        <label>Sector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlotTriggerHelperTest.cls
/**
 *  @description Test class for PlotTriggerHelper
 *
 *  2019-08-19  Shraddha N    First version
 *  
 */

@isTest
public class PlotTriggerHelperTest {
	 //Common test data to be used in test class
    @isTest
    public static void insertUpdateTest(){
        String errorMessage = '';
        Sector__c sectorObject = new Sector__c(Name = 'Sector 1');
        insert sectorObject;
        
        Business_Park__c businessParkObject = new Business_Park__c(Name = 'D3', Business_Park_Code__c = 'D3');
        
        Test.startTest();
        insert businessParkObject;
        
        Plot__c plotObject = new Plot__c(Name = 'Test Plot 1',Plot_Code_YARDI__c = 'pricingEngineTestPlot 1',Area_sqft__c = 100.0,
            					   		  Business_Park__c = businessParkObject.Id,Plot_Name_YARDI__c = 'pricingEngineTestPlotName 1' ,
            					   		  Type__c = 'Type 1',Status__c = 'Available - Sale',Sector_Name__c = sectorObject.Name, 
                                          Business_Park_Yardi__c = businessParkObject.Name);

        insert plotObject;
        
        plotObject.Sector_Name__c = 'Test Sector';
        plotObject.Business_Park_Yardi__c = 'Test Business Park Yardi';
        
        try{
            update plotObject;
        } catch(Exception e){
            errorMessage = e.getMessage();
        }
        
        Test.stopTest();
        
        System.assertEquals(errorMessage, '');
    }
    
}