src/objects/Business_Park__c.object
<CustomObject>
    <description>Object to store Business Parks. Business Parks are managed manually in Salesforce, with Oracle being the master.</description>
    <fields>
        <fullName>Business_Park_Yardi__c</fullName>
        <externalId>true</externalId>
        <label>Business Park (Yardi)</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Business Park</label>
    <nameField>
        <label>Business Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Plot__c.object
<CustomObject>
    <description>Object used to capture Plot information, and this is linked to Business Parks. The inventory is managed in Yardi and pushed to Salesforce.</description>
    <fields>
        <fullName>Business_Park_Yardi__c</fullName>
        <description>Short name for business park from Yardi</description>
        <label>Business Park Yardi</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Plots</relationshipLabel>
        <relationshipName>Plots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sector_Name__c</fullName>
        <label>Sector Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link between plot and sector</description>
        <label>Sector</label>
        <referenceTo>Sector__c</referenceTo>
        <relationshipLabel>Plots</relationshipLabel>
        <relationshipName>Plots</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plot</label>
    <nameField>
        <label>Plot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sector__c.object
<CustomObject>
    <description>To capture Sector information to allow for processing of parking eligibility.</description>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Sectors</relationshipLabel>
        <relationshipName>Sectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sector</label>
    <nameField>
        <label>Sector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlotTriggerHelper.cls
/***********************************************************************************************
* Name              : PlotTriggerHelper                                                 
* Description       : PlotTriggerHelper class is a helper class for PlotTrigger.
* Created Date      : 19/05/2019                                                    
* Created By        : Prachi Sinha (prachi.sinha@were4c.com)                                                                                                    
* ----------------------------------------------------------------------------------------------
* VERSION   Developer   Date        Description     Ticket/Reference                                                                    
* 1.0       Prachi      19/05/2019   Created                              
************************************************************************************************/
public with sharing class PlotTriggerHelper{

    /************************************************************************************
    Method  :         populateSector 
    Description :     populate sector lookup field based on the sector name field - before insert
    Version :         1.0
    ************************************************************************************/
    public static void populateSector(List<Plot__c> plotList){
    
        List<Sector__c> sectorList = [select id, Name from sector__c];
        Map<String,Id> sectorNameMap = new Map<String,Id>();
        
        //sector names will never be duplicate
        for(Sector__c secRec : sectorList){
            sectorNameMap.put(secRec.name,secRec.Id);
        }
        
        for(Plot__c plotRec: plotList){
            if(plotRec.Sector_Name__c <> null){
                if(sectorNameMap.containsKey(plotRec.Sector_Name__c)){
                    plotRec.Sector__c = sectorNameMap.get(plotRec.Sector_Name__c);
                }
            }
        }
    }
    
    /************************************************************************************
    Method  :         populateSectorUpdate 
    Description :     populate sector lookup field based on the sector name field - before update
    Version :         1.0
    ************************************************************************************/
    public static void populateSectorUpdate(List<Plot__c> plotNewList, Map<Id,Plot__c> plotOldMap){
    
        List<Plot__c> plotList = new List<Plot__c>();
        for(Plot__c plotRecord : plotNewList){
            if(plotOldMap.get(plotRecord.Id).Sector_Name__c != plotRecord.Sector_Name__c){
                plotList.add(plotRecord);
            }
        }
        
        if(plotList.size() > 0){
            populateSector(plotList);
        }                
    }
    
    
    /************************************************************************************
    Method  :         populateBusinessPark
    Description :     populate business park lookup field based on the business park short name field - before insert
    Version :         1.0
    ************************************************************************************/
    public static void populateBusinessPark(List<Plot__c> plotList){
    
        List<Business_Park__c> businessParkList = [select id, Name from Business_Park__c];
        Map<String,Id> bpNameMap = new Map<String,Id>();
        
        //business park names will never be duplicate
        for(Business_Park__c bpRec : businessParkList){
            bpNameMap.put(bpRec.name,bpRec.Id);
        }
        
        for(Plot__c plotRec: plotList){
            if(plotRec.Business_Park_Yardi__c <> null){
                if(bpNameMap.containsKey(plotRec.Business_Park_Yardi__c)){
                    plotRec.Business_Park__c = bpNameMap.get(plotRec.Business_Park_Yardi__c);
                }
            }
        }
    }
    
    /************************************************************************************
    Method  :         populateBusinessParkUpdate 
    Description :     populate business park lookup field based on the business park short name field - before update
    Version :         1.0
    ************************************************************************************/
    public static void populateBusinessParkUpdate(List<Plot__c> plotNewList, Map<Id,Plot__c> plotOldMap){
    
        List<Plot__c> plotList = new List<Plot__c>();
        for(Plot__c plotRecord : plotNewList){
            if(plotOldMap.get(plotRecord.Id).Business_Park_Yardi__c != plotRecord.Business_Park_Yardi__c){
                plotList.add(plotRecord);
            }
        }
        
        if(plotList.size() > 0){
            populateBusinessPark(plotList);
        }                
    }
    
}