src/objects/Business_Park__c.object
<CustomObject>
    <description>Object to store Business Parks. Business Parks are managed manually in Salesforce, with Oracle being the master.</description>
    <label>Business Park</label>
    <nameField>
        <label>Business Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <formula>Unit__r.Building__r.Business_Park__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Park</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Proposed_End_Date__c</fullName>
        <label>Proposed End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <label>Proposed Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuoteSyncUtilsTests.cls
/*
 * @Who   Cameron Stewart <cameron.stewart@weare4c.com>
 * @What  A test class for verifying the quote syncing line item deletion
 * @When  24/6/2019
 */
@isTest
public class QuoteSyncUtilsTests {
    
    @testSetup
    static void createTestData() {
        
        Product2 productRecord = new Product2(Name = 'Test', IsActive = True);
        insert productRecord;
        
        PricebookEntry pricebookEntryRecord = new PriceBookEntry(Product2Id = productRecord.Id, Pricebook2Id = test.getStandardPricebookId(), UnitPrice = 100, IsActive = true);
        insert pricebookEntryRecord;
        
        Business_Park__c businessPark = new Business_Park__c();
        insert businessPark;
        
        Opportunity opportunityRecord = new Opportunity(Name = 'Test', StageName = 'New', CloseDate = date.today().addDays(0), Business_Park__c = businessPark.Id, PriceBook2Id = test.getStandardPricebookId());
        insert opportunityRecord;
        
        //OpportunityLineItem opportunityLineItemRecord = new OpportunityLineItem(OpportunityId = opportunityRecord.Id, PricebookEntryId = pricebookEntryRecord.Id, Quantity = 1, TotalPrice = 100);
        //insert opportunityLineItemRecord;
        
        Quote quoteRecord = new Quote(OpportunityId = opportunityRecord.Id, Name = 'Test', Proposed_Start_Date__c = date.today(), Proposed_End_Date__c = date.today().addDays(1), PriceBook2Id = test.getStandardPricebookId());
        insert quoteRecord;
        
        QuoteLineItem quoteLineItem = new QuoteLineItem(QuoteId = quoteRecord.Id, Quantity = 1, PricebookEntryId = pricebookEntryRecord.Id, UnitPrice = 100, Product2Id = productRecord.Id);
        insert quoteLineItem;
        
        opportunityRecord.SyncedQuoteId = quoteRecord.Id;
        update opportunityRecord;
    }
	
    @isTest static void happyPathCheck() {
        
        Opportunity opportunityRecord  = [SELECT Id, SyncedQuoteId FROM Opportunity];
        opportunityRecord.SyncedQuoteId = null;
        
        test.startTest();
        update opportunityRecord;
        test.stopTest();

        System.assertEquals(1, [Select Id From OpportunityLineItem].size());
        
    }
}