src/objects/Business_Park__c.object
<CustomObject>
    <description>Object to store Business Parks. Business Parks are managed manually in Salesforce, with Oracle being the master.</description>
    <label>Business Park</label>
    <nameField>
        <label>Business Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>TempOwnerId__c</fullName>
        <label>TempOwnerId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company</fullName>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Land</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                    <label>Commercial Office</label>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Business Center</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Co-working</fullName>
                    <isActive>false</isActive>
                    <label>Co-Working</label>
                </value>
                <value>
                    <fullName>Common Area</fullName>
                    <isActive>false</isActive>
                    <label>Common Area</label>
                </value>
                <value>
                    <fullName>Desk</fullName>
                    <isActive>false</isActive>
                    <label>Desk</label>
                </value>
                <value>
                    <fullName>Executive Office</fullName>
                    <isActive>false</isActive>
                    <label>Executive Office</label>
                </value>
                <value>
                    <fullName>Free Parking</fullName>
                    <isActive>false</isActive>
                    <label>Free Parking</label>
                </value>
                <value>
                    <fullName>Labour Village</fullName>
                    <isActive>false</isActive>
                    <label>Labour Village</label>
                </value>
                <value>
                    <fullName>Open Yard</fullName>
                    <isActive>false</isActive>
                    <label>Open Yard</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Other Rooms</fullName>
                    <isActive>false</isActive>
                    <label>Other Rooms</label>
                </value>
                <value>
                    <fullName>Other Units</fullName>
                    <isActive>false</isActive>
                    <label>Other Units</label>
                </value>
                <value>
                    <fullName>Paid Parking</fullName>
                    <isActive>false</isActive>
                    <label>Paid Parking</label>
                </value>
                <value>
                    <fullName>Parking</fullName>
                    <isActive>false</isActive>
                    <label>Parking</label>
                </value>
                <value>
                    <fullName>Phase 2</fullName>
                    <isActive>false</isActive>
                    <label>Phase 2</label>
                </value>
                <value>
                    <fullName>Research and Development</fullName>
                    <isActive>false</isActive>
                    <label>Research and Development</label>
                </value>
                <value>
                    <fullName>Retail Support</fullName>
                    <isActive>false</isActive>
                    <label>Retail Support</label>
                </value>
                <value>
                    <fullName>Shared Desk - Daily</fullName>
                    <isActive>false</isActive>
                    <label>Shared Desk - Daily</label>
                </value>
                <value>
                    <fullName>Shared Desk - Freelancer</fullName>
                    <isActive>false</isActive>
                    <label>Shared Desk - Freelancer</label>
                </value>
                <value>
                    <fullName>Showroom</fullName>
                    <isActive>false</isActive>
                    <label>Showroom</label>
                </value>
                <value>
                    <fullName>Signage</fullName>
                    <isActive>false</isActive>
                    <label>Signage</label>
                </value>
                <value>
                    <fullName>Soundstage</fullName>
                    <isActive>false</isActive>
                    <label>Soundstage</label>
                </value>
                <value>
                    <fullName>Storage</fullName>
                    <isActive>false</isActive>
                    <label>Storage</label>
                </value>
                <value>
                    <fullName>Warehouse</fullName>
                    <isActive>false</isActive>
                    <label>Warehouse</label>
                </value>
                <value>
                    <fullName>Workshop</fullName>
                    <isActive>false</isActive>
                    <label>Workshop</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TempOwnerId__c</fullName>
        <description>Backend field to manage Lead Assignment</description>
        <label>TempOwnerId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <businessProcess>Land%2FLease</businessProcess>
        <label>Company</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LeadTriggerConvertTest.cls
/***********************************************************************************************
* Name              : LeadTriggerConvertTest                                                 
* Description       : LeadTriggerConvertTest test class for LeadTriggerConvert
* Created Date      : 23/07/2019                                                    
* Created By        : Amruta K                                                                                    
* ----------------------------------------------------------------------------------------------
* VERSION   Developer   Date        Description     Ticket/Reference                                                                    
* 1.0       Divya       23/07/2019   Created                              
************************************************************************************************/
@isTest
public class LeadTriggerConvertTest {
    
    // Method to test leadConvert method.
    testMethod static void leadConvertTestCase() {
        
        Business_Park__c businessPark = new Business_Park__c(
                Name = 'D3'
        );
        insert businessPark;
        
        Lead lead=new Lead(LastName='Doe',
                           FirstName='John',
                           Company='Test',
                           Status='Inquiry', 
                           Business_Park__c = businessPark.Id, 
                           Product_Category__c = 'Land',
                           Email = 'test@gmail.com',
                           TempOwnerId__c = 'SKIP');
        insert lead;             
        
        LeadStatus convertStatus = [Select Id, MasterLabel from LeadStatus where IsConverted=true limit 1];
        
        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(lead.id);
        lc.setConvertedStatus(convertStatus.MasterLabel);
        
        Task t = new Task();
        t.OwnerId = UserInfo.getUserId();
        t.Subject='Donni';
        t.Status='Not Started';
        t.Priority='Normal';
        t.WhoId = lead.Id;
        insert t; 

        Database.LeadConvertResult lcr;
        
        Test.startTest();
        	lcr = Database.convertLead(lc);
        Test.stopTest();
        
        List<WorkOrder> insertedWorkOrderList = [SELECT Id FROM WorkOrder];
        List<Case> insertedCaseList = [SELECT Id FROM Case];
        
        System.assertEquals(insertedWorkOrderList.size(), 1);
        System.assertEquals(insertedCaseList.size(), 2);
    }
    // Method to test afterCovertUpdateContactOnOpportunity method.
     testMethod static void afterCovertUpdateContactOnOpportunityTestCase() {
        
        Business_Park__c businessPark = new Business_Park__c(
                Name = 'D3'
        );
        insert businessPark;
        
        Lead lead=new Lead(LastName='Doe',
                           FirstName='John',
                           Company='Test',
                           Status='Inquiry', 
                           Business_Park__c = businessPark.Id, 
                           Product_Category__c = 'Land',
                           Email = 'test@gmail.com',
                           TempOwnerId__c = 'SKIP');
        insert lead;             
        
        LeadStatus convertStatus = [Select Id, MasterLabel from LeadStatus where IsConverted=true limit 1];
        
        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(lead.id);
        lc.setConvertedStatus(convertStatus.MasterLabel);
        
        Task t = new Task();
        t.OwnerId = UserInfo.getUserId();
        t.Subject='Donni';
        t.Status='Not Started';
        t.Priority='Normal';
        t.WhoId = lead.Id;
        insert t; 

        Database.LeadConvertResult lcr;
        
        Test.startTest();
        	lcr = Database.convertLead(lc);
        Test.stopTest();
        
		List<Opportunity> oppList = [SELECT Id, Contact__c FROM Opportunity WHERE Id =: lcr.getOpportunityId()];
        
         System.assertEquals(oppList[0].Contact__c,  lcr.getContactId());
    }

}