src/objects/Business_Park__c.object
<CustomObject>
    <description>Object to store Business Parks. Business Parks are managed manually in Salesforce, with Oracle being the master.</description>
    <fields>
        <fullName>Business_Park_Yardi__c</fullName>
        <externalId>true</externalId>
        <label>Business Park (Yardi)</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Business Park</label>
    <nameField>
        <label>Business Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Leasing Contact</fullName>
                </value>
                <value>
                    <fullName>Licensee Contact</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Alternate Payee</fullName>
                </value>
                <value>
                    <fullName>Authorized Signatory</fullName>
                </value>
                <value>
                    <fullName>Focal Point</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Legal Representative</fullName>
                </value>
                <value>
                    <fullName>Manager Incharge</fullName>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>PRO</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>CollectionTeam</fullName>
                </value>
                <value>
                    <fullName>Licensing Contact</fullName>
                </value>
                <value>
                    <fullName>Individual Shareholder</fullName>
                </value>
                <value>
                    <fullName>Corporate Shareholder</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Type__c</fullName>
        <label>Lease Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>land</fullName>
                </value>
                <value>
                    <fullName>office</fullName>
                </value>
                <value>
                    <fullName>retail</fullName>
                </value>
                <value>
                    <fullName>str</fullName>
                </value>
                <value>
                    <fullName>annland</fullName>
                </value>
                <value>
                    <fullName>lhland</fullName>
                </value>
                <value>
                    <fullName>unitsale</fullName>
                </value>
                <value>
                    <fullName>cowork</fullName>
                </value>
                <value>
                    <fullName>PMLA</fullName>
                    <isActive>false</isActive>
                    <label>PMLA</label>
                </value>
                <value>
                    <fullName>PMS</fullName>
                    <isActive>false</isActive>
                    <label>PMS</label>
                </value>
                <value>
                    <fullName>TECOM</fullName>
                    <isActive>false</isActive>
                    <label>TECOM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renew</fullName>
                </value>
                <value>
                    <fullName>Modification</fullName>
                </value>
                <value>
                    <fullName>Contraction</fullName>
                    <isActive>false</isActive>
                    <label>Contraction</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Payment_Schedule__c.object
<CustomObject>
    <description>Object used to capture the payment schedules against Quote. This will be managed by Yardi and will be pushed to Salesforce.</description>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Payment Schedules</relationshipLabel>
        <relationshipName>Payment_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Payment Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>CCL_Sign_Date__c</fullName>
        <label>CCL Sign Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <formula>TEXT(Opportunity.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposed_End_Date__c</fullName>
        <label>Proposed End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <label>Proposed Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Downsize</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GenerateCCLDocumentTest.cls
/**
 *  @description Test class for GenerateCCLDocument
 *
 *  2019-07-26  Amruta K   First version
 * 
 */
@isTest
public class GenerateCCLDocumentTest {
     // Method to create test setup data.
	@testSetup static void testData() {
        Account accObj = new Account();
        accObj.Name = 'Test Account';
        insert accObj;
        
        Contact conObj = new Contact();
        conObj.lastName = 'Test';
        conObj.AccountId = accObj.Id;
        insert conObj;
        
        Business_Park__c bParkObj = new Business_Park__c(Name = 'Business', Business_Park_Yardi__c = 'Yardi Park');
        insert bParkObj;
        
        Opportunity oppObj = new Opportunity(
            AccountId = accObj.Id,
            name = accObj.name,
            closedate = system.today(),
            Lease_Type__c = 'land', 
            Opportunity_Type__c = 'Renew',
            stagename='Prospecting',
            Business_Park__c = bParkObj.Id
        );
        insert oppObj;
        
        Quote quoteObj = new Quote(
            Name='01010', 
            OpportunityId=oppObj.Id, 
            Status='Approved',
        	Lease_Start_Date__c = System.today(),
            Lease_End_Date__c = System.today()+10,
            Type__c = 'New',
            Proposed_Start_Date__c = System.today()-10,
            Proposed_End_Date__c = System.today()+10,
            CCL_Sign_Date__c = System.today()
        );
        insert quoteObj;
       
    }
    
    // @isTest Method to test if Payment_Schedules__r is Empty
    public static testMethod void testCreateDocument1(){
        List<Quote> quoteObj = [SELECT Id, Name, OpportunityId, AccountId 
                                FROM Quote LIMIT 1];
        
        Test.setMock(HttpCalloutMock.class, new CongaBackgroundMockHttpResponseGenerator());
        
        Test.startTest();
        String docs = GenerateCCLDocument.createDocument(quoteObj[0].Id);
        Test.stopTest();
        
        System.assertEquals(docs, 'Quote should have one Payment Schedule record to generate CCL document.');
       
    }
    
    // @isTest Method to test if all the conditions are met and result is success
    public static testMethod void testCreateDocument2(){
        List<Quote> quoteObj = [SELECT Id, Name, OpportunityId, AccountId 
                                FROM Quote LIMIT 1];
        Payment_Schedule__c paySchedObj = NEW Payment_Schedule__c(Quote__c = quoteObj[0].Id);
        insert paySchedObj;
        Test.setMock(HttpCalloutMock.class, new CongaBackgroundMockHttpResponseGenerator());
        
        Test.startTest();
        String docs = GenerateCCLDocument.createDocument(quoteObj[0].Id);
        Test.stopTest();
        
        System.assertEquals(docs, 'Success');
      
    }
    
    // @isTest Method to test if Quote list which status is not approved
    public static testMethod void testCreateDocument3(){
        List<Quote> quoteObj = [SELECT Id, Name, OpportunityId, AccountId 
                                FROM Quote LIMIT 1];
        Payment_Schedule__c paySchedObj = NEW Payment_Schedule__c(Quote__c = quoteObj[0].Id);
        insert paySchedObj;
        
		quoteObj[0].Status='Draft';
        update quoteObj;
        Test.setMock(HttpCalloutMock.class, new CongaBackgroundMockHttpResponseGenerator());
        
        Test.startTest();
        String docs = GenerateCCLDocument.createDocument(quoteObj[0].Id);
        Test.stopTest();
        
        System.assertEquals(docs, 'Quote should be Approved to generate CCL document.');
    
    }
}