src/objects/Business_Park__c.object
<CustomObject>
    <description>Object to store Business Parks. Business Parks are managed manually in Salesforce, with Oracle being the master.</description>
    <label>Business Park</label>
    <nameField>
        <label>Business Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grace_Period__c.object
<CustomObject>
    <description>Object used to capture additional grace period, against Quotes.</description>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Grace Period</label>
    <nameField>
        <displayFormat>GP-{000000}</displayFormat>
        <label>Grace Period Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grace Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Amendment_Id__c</fullName>
        <description>this is returned by Yardi in response</description>
        <label>Amendment Id</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Building_Name__c</fullName>
        <label>Building</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Type__c</fullName>
        <label>Lease Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>land</fullName>
                </value>
                <value>
                    <fullName>office</fullName>
                </value>
                <value>
                    <fullName>retail</fullName>
                </value>
                <value>
                    <fullName>str</fullName>
                </value>
                <value>
                    <fullName>annland</fullName>
                </value>
                <value>
                    <fullName>lhland</fullName>
                </value>
                <value>
                    <fullName>unitsale</fullName>
                </value>
                <value>
                    <fullName>cowork</fullName>
                </value>
                <value>
                    <fullName>PMLA</fullName>
                    <isActive>false</isActive>
                    <label>PMLA</label>
                </value>
                <value>
                    <fullName>PMS</fullName>
                    <isActive>false</isActive>
                    <label>PMS</label>
                </value>
                <value>
                    <fullName>TECOM</fullName>
                    <isActive>false</isActive>
                    <label>TECOM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renew</fullName>
                </value>
                <value>
                    <fullName>Modification</fullName>
                </value>
                <value>
                    <fullName>Contraction</fullName>
                    <isActive>false</isActive>
                    <label>Contraction</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Amendment_Id__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Parent Amendment Id</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Downsize</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>T_Code__c</fullName>
        <label>T Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Lookup</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Junctions (Opportunity Lookup)</relationshipLabel>
        <relationshipName>Opportunity_Junctions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Junctions</relationshipLabel>
        <relationshipName>Opportunity_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Junction</label>
    <nameField>
        <label>Opportunity Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Grace_Period_Mechanism__c</fullName>
        <label>Grace Period Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>initial</fullName>
                </value>
                <value>
                    <fullName>every</fullName>
                </value>
                <value>
                    <fullName>end</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period_Period__c</fullName>
        <label>Grace Period (period)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>days</fullName>
                </value>
                <value>
                    <fullName>months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <label>Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <formula>TEXT(Opportunity.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Payment Terms</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_End_Date__c</fullName>
        <label>Proposed End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <label>Proposed Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Downsize</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grace_Period_Mechanism__c</fullName>
        <label>Offered Grace Period Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>initial</fullName>
                </value>
                <value>
                    <fullName>every</fullName>
                </value>
                <value>
                    <fullName>end</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <inlineHelpText>If &apos;Offered Grace Period&apos; is blank, the Grace Period listed at the Quote will be used for price calculation.</inlineHelpText>
        <label>Offered Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PriceSch_ChargeType__c</fullName>
        <formula>Price_Schedule__r.Charge_Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Charge Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transactional_Unit__c</fullName>
        <label>Transactional Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sqft</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Grace Period</fullName>
                </value>
                <value>
                    <fullName>Revision</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LeaseMergerBatch.cls
/************************************************************************************
* Name          : LeaseMergerBatch                                                 
* Description   : Batch for Merger of Leases
* Created Date  :                                                    
* Created By    : 4C Vaibhavi
* Jira/Req By   :                                                                                                                                           
* -----------------------------------------------------------------------------------------------------------------------
* VERSION   Developer   Date        Description     Ticket/Reference    
1.0
************************************************************************************/
global class LeaseMergerBatch implements Database.Batchable<sObject>,Database.Stateful {
    public Map<Id,Opportunity> oppIdVsRecMap = new Map<Id,Opportunity>();
    
    Id opportunityId;
    public LeaseMergerBatch() {}
    public LeaseMergerBatch(Id opportunityId) {
        this.opportunityId = opportunityId;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        Date filterDate = Date.today().addDays(120);
        String oppQuery = 'SELECT Id, Name, Type, Lease_End_Date__c,SyncedQuoteId, Lease_Type__c,Lease_Start_Date__c,CloseDate,'+
            			  'ContactId,Opportunity_Type__c,StageName,Parent_Amendment_Id__c,Amendment_Id__c,Contact__c,T_Code__c,'+
            			  'AccountId, CurrencyIsoCode, Business_Park__c, Sub_Type__c, Parent_Opportunity__c,Building_Name__c , ' +
                          '(SELECT Id FROM Opportunities__r WHERE Type = \'Renewal\' AND  StageName != \'Cancelled\')'+
            			  ' FROM Opportunity WHERE Lease_End_Date__c =:filterDate AND StageName = \'Active\' ';
        
        if(String.isNotBlank(opportunityId)) { 
            oppQuery += 'AND Id =: opportunityId';
        }
        oppQuery += ' ORDER BY CreatedDate DESC';
        List<Opportunity> oppList = Database.query(oppQuery);
        oppIdVsRecMap = new Map<Id,Opportunity>(oppList);
        return Database.getQueryLocator(oppQuery);        
    }
    
    /**
    *  @description Creates Opportunity if Parent's and Child's opportunities have same Lease End date and Building name. 
    *      Creates a quote related to the newly created opportunity and related QLI's of parent's and child's synced Quote.  
    *  @param List of Opportunity where type is Renewal
    *  @return 
    */
    
    global void execute(Database.BatchableContext bc, List<Opportunity> scope){
        // process each batch of records
        createRenewalOppAndQuoteQLI(scope);
    }            
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }    

      /**
        * @method	: createRenewalOppAndQuoteQLI()
        * @description	: Method to create renewal opportunity, quote and related QLI records
        * @return	: NA
        * @params	: scope - List of Opportunity
        */
    public void createRenewalOppAndQuoteQLI(List<Opportunity> scope) {

        Map<Id,List<Id>> oppIdVsMergeOppIdListMap = new Map<Id,List<Id>>();
        Map<String,List<Opportunity>> criteriaVsOpplistMap = new Map<String,List<Opportunity>>();
        for(Opportunity opp : scope) {
            if(opp.Opportunities__r.size() == 0) {
                String key = String.valueOf(opp.AccountId) + String.valueOf(opp.Lease_End_Date__c) + opp.Building_Name__c;
                if(!criteriaVsOpplistMap.containsKey(key)){
                    criteriaVsOpplistMap.put(key,new List<Opportunity>());
                }
                criteriaVsOpplistMap.get(key).add(opp);
            }
        }
        Map<String,List<Id>>  criteriaVsOppToMergeIdListMap = new Map<String,List<Id>>();
        List<Id> idsWithChildRecordList = new List<Id>();
        
        for(String key : criteriaVsOpplistMap.keyset()){
            List<Id> oppToMergeIdList = new List<Id>();
            List<Opportunity> sameCriteriaOppList = criteriaVsOpplistMap.get(key);
            List<Id> sameCriteriaOppIdList = new List<Id>();
            for(Opportunity o :sameCriteriaOppList){
                sameCriteriaOppIdList.add(o.Id);
            }
            for(Opportunity o : criteriaVsOpplistMap.get(key)){
                if(o.Parent_Opportunity__c == NULL){
                    if(!oppToMergeIdList.contains(o.Id))
                    	oppToMergeIdList.add(o.Id);
                }else if(!sameCriteriaOppIdList.contains(o.Parent_Opportunity__c)){
                    if(!oppToMergeIdList.contains(o.Id))
                    	oppToMergeIdList.add(o.Id);
                }else if(sameCriteriaOppIdList.contains(o.Parent_Opportunity__c)){
                    if(oppToMergeIdList.contains(o.Id)){
                        oppToMergeIdList.remove(oppToMergeIdList.indexOf(o.Id));
                    }
                    if(idsWithChildRecordList.contains(o.Id)){
                        idsWithChildRecordList.remove(oppToMergeIdList.indexOf(o.Id));
                    }
                    if(!oppToMergeIdList.contains(o.Parent_Opportunity__c))
                    	oppToMergeIdList.add(o.Parent_Opportunity__c);
                    if(!idsWithChildRecordList.contains(o.Parent_Opportunity__c))
                    	idsWithChildRecordList.add(o.Parent_Opportunity__c);
                }
            }
            criteriaVsOppToMergeIdListMap.put(key, oppToMergeIdList);
        }
        
        for(String str : criteriaVsOppToMergeIdListMap.keyset()){
            for(Id i : criteriaVsOppToMergeIdListMap.get(str)){
                if(idsWithChildRecordList.contains(i)){
                    criteriaVsOppToMergeIdListMap.get(str).remove(criteriaVsOppToMergeIdListMap.get(str).indexOf(i));
                }
            }
        }
        
        List<Opportunity> oppList = [SELECT  Id, Name, Type, Lease_End_Date__c,SyncedQuoteId, Lease_Type__c,Lease_Start_Date__c
                                     		,CloseDate,ContactId,Opportunity_Type__c,StageName,Parent_Amendment_Id__c,T_Code__c,AccountId
                                     		,CurrencyIsoCode, Business_Park__c, Sub_Type__c,Parent_Opportunity__c,Building_Name__c
                                     		,(SELECT  Id, Name, Type, Lease_End_Date__c, Lease_Start_Date__c,CloseDate, SyncedQuoteId
                                            		  ,ContactId, StageName,AccountId, CurrencyIsoCode, Business_Park__c, Sub_Type__c
                                            		  ,Parent_Opportunity__c,Building_Name__c 
                                     		  FROM Opportunities__r 
                                     		  WHERE StageName = 'Active') 
                                     FROM  Opportunity 
                                     WHERE Id IN :idsWithChildRecordList];
        
        //Create new Renewal Opportunity
        for(Opportunity o : oppList){
            if(!oppIdVsMergeOppIdListMap.containsKey(o.Id)){
                oppIdVsMergeOppIdListMap.put(o.Id,new List<Id>());
            }
            for(Opportunity childOpp : o.Opportunities__r){
                if(childOpp.Lease_End_Date__c == o.Lease_End_Date__c 
                   && childOpp.Building_Name__c == o.Building_Name__c
                   && childOpp.AccountId == o.AccountId){
                       if(oppIdVsRecMap.containsKey(childOpp.Id)){
                           oppIdVsMergeOppIdListMap.get(o.Id).add(childOpp.Id);
                       }
                   }
            }
        }
        
        for(String str : criteriaVsOppToMergeIdListMap.keyset()){
            if(criteriaVsOppToMergeIdListMap.get(str).size()>0){
                idsWithChildRecordList.add(criteriaVsOppToMergeIdListMap.get(str)[0]);
                List<Id> internalList = new List<Id>(criteriaVsOppToMergeIdListMap.get(str));
                internalList.remove(0);
                oppIdVsMergeOppIdListMap.put(criteriaVsOppToMergeIdListMap.get(str)[0],internalList);
            }
        }
        
        Map<Id,List<Id>> oppIdVsSyncQuoteIdListMap = new Map<Id,List<Id>>();
        for(Id id :oppIdVsMergeOppIdListMap.keyset()){
            if(!oppIdVsSyncQuoteIdListMap.containsKey(id)){
                oppIdVsSyncQuoteIdListMap.put(id,new List<Id>());
            }
            for(Id internalId : oppIdVsMergeOppIdListMap.get(id)){
                if(oppIdVsRecMap.get(internalId).SyncedQuoteId != NULL)
                	oppIdVsSyncQuoteIdListMap.get(id).add(oppIdVsRecMap.get(internalId).SyncedQuoteId);
            }
            if(oppIdVsRecMap.get(id).SyncedQuoteId != NULL)
            	oppIdVsSyncQuoteIdListMap.get(id).add(oppIdVsRecMap.get(id).SyncedQuoteId);
        }
       	
        List<Opportunity> renewalOppLst = new List<Opportunity>();
        
        for(Id parentOppId : idsWithChildRecordList) {
            Opportunity parentOpp = oppIdVsRecMap.get(parentOppId);
            Opportunity renewalOppObj = new Opportunity();
            renewalOppObj.Business_Park__c = parentOpp.Business_Park__c;
            renewalOppObj.CloseDate = parentOpp.CloseDate;
            renewalOppObj.ContactId = parentOpp.ContactId;
            renewalOppObj.Name = parentOpp.Name + ' Renewal';
            renewalOppObj.StageName = 'New';
            renewalOppObj.AccountId = parentOpp.AccountId;
            renewalOppObj.Contact__c = parentOpp.Contact__c;
            renewalOppObj.CurrencyIsoCode = parentOpp.CurrencyIsoCode;
            renewalOppObj.Parent_Opportunity__c = parentOpp.Id;
            renewalOppObj.Lease_Start_Date__c = parentOpp.Lease_End_Date__c.addDays(1);
            renewalOppObj.Lease_End_Date__c = parentOpp.Lease_End_Date__c.addMonths(12);
            renewalOppObj.Lease_Type__c = parentOpp.Lease_Type__c;
            renewalOppObj.Opportunity_Type__c = 'Renew';
            renewalOppObj.Parent_Amendment_Id__c = parentOpp.Amendment_Id__c;
            renewalOppObj.T_Code__c = parentOpp.T_Code__c;
            renewalOppObj.Type = 'Renewal';
            renewalOppObj.Sub_Type__c = 'Renewal';
            renewalOppObj.Building_Name__c = parentOpp.Building_Name__c;
            renewalOppLst.add(renewalOppObj);
        }
        
        if(!renewalOppLst.isEmpty()) {
            insert renewalOppLst;
            System.debug('inserted Opportunities size==='+renewalOppLst.size());
        }
        
        Set<Id> quoteIdSet = new Set<Id>();    
        for(Id id : idsWithChildRecordList){
            if(oppIdVsRecMap.get(id).SyncedQuoteId != NULL)
            	quoteIdSet.add(oppIdVsRecMap.get(id).SyncedQuoteId);
        }
        List<Quote> quoteList = [SELECT   Id,Lease_Start_Date__c,Name,Type__c,Proposed_Start_Date__c,Proposed_End_Date__c
                                 		 ,Grace_Period__c,Grace_Period_Period__c,Grace_Period_Mechanism__c,Payment_Terms__c
                                 		 ,Status, IsSyncing, OpportunityId,Lease_End_Date__c ,Pricebook2Id,Opportunity.Contact__c 
                                 FROM Quote WHERE Id IN :quoteIdSet];

        Map<id,Quote> parentOppIdSyncedQuoteMap = new Map<id,Quote>();
        for(Quote q : quoteList){
            parentOppIdSyncedQuoteMap.put(q.OpportunityId,q);
        }
        
        //Parent Synced Quote's QuoteLineItems
        Set<Id> masterSyncedQuoteIdSet = new Set<Id>();
        for(Id recId : oppIdVsRecMap.keyset()){
            if(oppIdVsRecMap.get(recId).SyncedQuoteId != NULL)
            	masterSyncedQuoteIdSet.add(oppIdVsRecMap.get(recId).SyncedQuoteId);
        }
        
        List<QuoteLineItem> lineItemsLst = [SELECT   Id
                                            		,UnitPrice
                                            		,QuoteId
                                            		,Transactional_Unit__c
                                            		,Transaction_Type__c
                                            		,Start_Date__c
                                            		,End_Date__c
                                            		,Quantity
                                            		,Product2Id
                                            		,Area__c
                                            		,PricebookEntryId
                                            		,Quote.OpportunityId
                                            		,Quote.Opportunity.Parent_Opportunity__r.Id
                                            FROM QuoteLineItem
                                            WHERE QuoteId IN: masterSyncedQuoteIdSet
                                            AND PriceSch_ChargeType__c = 'Rent'
                                            AND Type__c = 'Normal'];
        
        Map<Id,List<Id>> oppIdQLIToMergerListMap = new Map<Id,List<Id>>();
        for(Id id : oppIdVsSyncQuoteIdListMap.keyset()){
            if(!oppIdQLIToMergerListMap.containsKey(id)){
                oppIdQLIToMergerListMap.put(id,new List<Id>());
            }
            
            for(Id internalId : oppIdVsSyncQuoteIdListMap.get(id)){
                for(QuoteLineItem qli : lineItemsLst){
                    if(qli.QuoteId == internalId){
                        oppIdQLIToMergerListMap.get(id).add(qli.id);
                    }
                }
            }
        }
        
        List<Quote> renewalQuoteList = new List<Quote>();
        for(Opportunity renewalObj : renewalOppLst) {
            if(parentOppIdSyncedQuoteMap.containsKey(renewalObj.Parent_Opportunity__c) && parentOppIdSyncedQuoteMap.get(renewalObj.Parent_Opportunity__c) != NULL){
                Quote syncQuoteInstance = parentOppIdSyncedQuoteMap.get(renewalObj.Parent_Opportunity__c);
                Quote quoteObj = new Quote();
                quoteObj.Lease_End_Date__c = syncQuoteInstance.Lease_End_Date__c;
                quoteObj.Lease_Start_Date__c = syncQuoteInstance.Lease_Start_Date__c;
                quoteObj.Name = syncQuoteInstance.Name;
                quoteObj.Type__c = 'Renewal';
                quoteObj.Proposed_End_Date__c = syncQuoteInstance.Proposed_End_Date__c;
                quoteObj.Proposed_Start_Date__c = syncQuoteInstance.Proposed_Start_Date__c;
                //quoteObj.Grace_Period__c = syncQuoteInstance.Grace_Period__c;
                //quoteObj.Grace_Period_Period__c = syncQuoteInstance.Grace_Period_Period__c;
                //quoteObj.Grace_Period_Mechanism__c = syncQuoteInstance.Grace_Period_Mechanism__c;
                quoteObj.Payment_Terms__c = syncQuoteInstance.Payment_Terms__c;
                quoteObj.Status = 'Draft';
                quoteObj.OpportunityId = renewalObj.Id;
                quoteObj.Pricebook2Id = syncQuoteInstance.Pricebook2Id;
                quoteObj.Previous_Quote__c = syncQuoteInstance.Id;
                quoteObj.ContactId = syncQuoteInstance.Opportunity.Contact__c;
                renewalQuoteList.add(quoteObj);
            }
        }
        if(!renewalQuoteList.isEmpty()) {
            insert renewalQuoteList;
        }
        Set<Id> newQuoteIdSet = new Set<Id>();
        for(Quote q : renewalQuoteList){
            newQuoteIdSet.add(q.Id);
        }
        Map<Id,Quote> newQuoteIdParentOpportunityIdMap = new Map<Id,Quote>([Select OpportunityId,Opportunity.Parent_Opportunity__r.Id From Quote WHERE Id IN :newQuoteIdSet]);
        List<QuoteLineItem> parentsQLILst = new List<QuoteLineItem>();
        //Insert parent's synced QLI's to the Quote
        System.debug('parents Lineitems size===='+lineItemsLst.size());
            
        if(!renewalQuoteList.isEmpty() && !lineItemsLst.isEmpty()) {
            for(Quote quoteObj: renewalQuoteList) {
                for(QuoteLineItem parentsQLIObj : lineItemsLst) {
                    if(oppIdQLIToMergerListMap.get(newQuoteIdParentOpportunityIdMap.get(quoteObj.Id).Opportunity.Parent_Opportunity__r.Id).contains(parentsQLIObj.Id)){
                        QuoteLineItem newQLI = new QuoteLineItem();
                        newQLI.UnitPrice = parentsQLIObj.UnitPrice;
                        newQLI.QuoteId = quoteObj.Id;
                        newQLI.Transaction_Type__c = 'Renewal';
                        newQLI.Start_Date__c = parentsQLIObj.Start_Date__c;
                        newQLI.End_Date__c = parentsQLIObj.End_Date__c;
                        newQLI.Quantity = parentsQLIObj.Quantity;
                        newQLI.Product2Id = parentsQLIObj.Product2Id;
                        newQLI.PricebookEntryId = parentsQLIObj.PricebookEntryId;
                        newQLI.Transactional_Unit__c = parentsQLIObj.Transactional_Unit__c;
                        newQLI.Area__c = parentsQLIObj.Area__c;
                        parentsQLILst.add(newQLI);
                    }
                }
            }
        }
        
        List<Id> renewalOppIdList = new List<Id>();
        for(Opportunity o :renewalOppLst){
            renewalOppIdList.add(o.Id);
        }
        List<Opportunity> newOppList = new List<Opportunity>();
        newOppList = [SELECT Parent_Opportunity__r.Id,Name FROM Opportunity WHERE ID IN :renewalOppIdList];
        if(!parentsQLILst.isEmpty()) {
            try{
                insert parentsQLILst;
                List<Opportunity_Junction__c> oppJuncList = new List<Opportunity_Junction__c>();
                for(Opportunity newOpp : newOppList){
                    for(Id internalId : oppIdVsMergeOppIdListMap.get(newOpp.Parent_Opportunity__r.Id)){
                        Opportunity_Junction__c oppJun = new Opportunity_Junction__c();
                        oppJun.Name = newOpp.Name;
                        oppJun.Opportunity__c = newOpp.Id;
                        oppJun.Opportunity_Lookup__c = internalId;
                        oppJuncList.add(oppJun);
                    }
                    if(oppIdVsMergeOppIdListMap.get(newOpp.Parent_Opportunity__r.Id).size() > 0){
                        Opportunity_Junction__c oppJunParent = new Opportunity_Junction__c();
                        oppJunParent.Name = newOpp.Name;
                        oppJunParent.Opportunity__c = newOpp.Id;
                        oppJunParent.Opportunity_Lookup__c = newOpp.Parent_Opportunity__r.Id;
                        oppJuncList.add(oppJunParent);
                    }
                }
                insert oppJuncList;
            }
            catch(Exception e) {
                System.debug('Exception===='+e.getMessage());
            }
        }
    }
}