src/objects/Business_Park__c.object
<CustomObject>
    <description>Object to store Business Parks. Business Parks are managed manually in Salesforce, with Oracle being the master.</description>
    <label>Business Park</label>
    <nameField>
        <label>Business Park Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Parks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Building_Name__c</fullName>
        <label>Building</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Type__c</fullName>
        <label>Lease Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>land</fullName>
                </value>
                <value>
                    <fullName>office</fullName>
                </value>
                <value>
                    <fullName>retail</fullName>
                </value>
                <value>
                    <fullName>str</fullName>
                </value>
                <value>
                    <fullName>annland</fullName>
                </value>
                <value>
                    <fullName>lhland</fullName>
                </value>
                <value>
                    <fullName>unitsale</fullName>
                </value>
                <value>
                    <fullName>cowork</fullName>
                </value>
                <value>
                    <fullName>PMLA</fullName>
                    <isActive>false</isActive>
                    <label>PMLA</label>
                </value>
                <value>
                    <fullName>PMS</fullName>
                    <isActive>false</isActive>
                    <label>PMS</label>
                </value>
                <value>
                    <fullName>TECOM</fullName>
                    <isActive>false</isActive>
                    <label>TECOM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renew</fullName>
                </value>
                <value>
                    <fullName>Modification</fullName>
                </value>
                <value>
                    <fullName>Contraction</fullName>
                    <isActive>false</isActive>
                    <label>Contraction</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Amendment_Id__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Parent Amendment Id</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Downsize</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>T_Code__c</fullName>
        <label>T Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Lookup</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Junctions (Opportunity Lookup)</relationshipLabel>
        <relationshipName>Opportunity_Junctions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Junctions</relationshipLabel>
        <relationshipName>Opportunity_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Junction</label>
    <nameField>
        <label>Opportunity Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Quote_Line_Item__c</fullName>
        <label>Parent Quote Line Item</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transactional_Unit__c</fullName>
        <label>Transactional Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sqft</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Grace Period</fullName>
                </value>
                <value>
                    <fullName>Revision</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LeaseMergerBatchExecute.cls
public class LeaseMergerBatchExecute {
    @InvocableMethod
    public static void executeBatch(List<Id> requiredIds){
        String renewalOppId =  requiredIds[0];
        System.debug('requiredIds[0]-----'+requiredIds[0]);
        List<Opportunity> renewalOppList = [SELECT Name,Parent_Opportunity__r.Id,(Select Id From Quotes) FROM Opportunity WHERE Id = :renewalOppId];
        System.debug('renewalOppList[0]-----'+renewalOppList[0]);
        String parentOppId = renewalOppList[0].Parent_Opportunity__r.Id;
        System.debug('renewalOppList[0].Parent_Opportunity__r.Id-----'+renewalOppList[0].Parent_Opportunity__r.Id);
        Opportunity opp = renewalOppList[0];
        String quoteId = opp.Quotes[0].Id;
        System.debug('quoteId-----'+quoteId);
        String oppQuery = 'SELECT Id, Name, Type, Lease_End_Date__c,SyncedQuoteId, Lease_Type__c,Lease_Start_Date__c,CloseDate, ContactId,Opportunity_Type__c,' +
            			  'StageName,Parent_Amendment_Id__c,T_Code__c, AccountId, CurrencyIsoCode, Business_Park__c, Sub_Type__c, Parent_Opportunity__c,Building_Name__c,' +
            			  '(SELECT Id, Name, Type, Lease_End_Date__c, Lease_Start_Date__c,CloseDate, SyncedQuoteId,ContactId, StageName,' +
            			  'AccountId, CurrencyIsoCode, Business_Park__c, Sub_Type__c, Parent_Opportunity__c,Building_Name__c FROM Opportunities__r WHERE StageName =\'Active\')'+ 
            			  ' FROM Opportunity WHERE  Id =:parentOppId';
        List<Opportunity> qualifiedChildOppLst = new List<Opportunity>();
        Set<Id> syncedQuoteIdSet = new Set<Id>();
        System.debug('oppQuery-----'+oppQuery);
        List<Opportunity> listOpp = Database.query(oppQuery);
        System.debug('listOpp-----'+listOpp);
        if(!listOpp.isEmpty() && listOpp[0] != Null){
            Opportunity parentOppObj = listOpp[0];
            System.debug('parentOppObj-----'+parentOppObj);
            System.debug('listOpp[0].Opportunities__r-----'+listOpp[0].Opportunities__r);
            if(listOpp[0].Opportunities__r.size() > 0){
                for(Opportunity childOppObj : listOpp[0].Opportunities__r) {
                   if(childOppObj.Lease_End_Date__c == parentOppObj.Lease_End_Date__c 
                       && childOppObj.Building_Name__c == parentOppObj.Building_Name__c
                       && childOppObj.AccountId == parentOppObj.AccountId){
                           qualifiedChildOppLst.add(childOppObj);
                           System.debug('Here-----');
                           syncedQuoteIdSet.add(childOppObj.SyncedQuoteId);   
                       }
                }
            }
            syncedQuoteIdSet.add(parentOppObj.SyncedQuoteId);
        }
        System.debug('syncedQuoteIdSet-----'+syncedQuoteIdSet);
        List<QuoteLineItem> lineItemsLst = [SELECT   Id
                                            	   , UnitPrice 
                                                   , QuoteId 
                                                   , Transaction_Type__c 
                                                   , Start_Date__c
                                                   , End_Date__c
                                                   , Quantity
                                                   , Product2Id
                                                   , PricebookEntryId
                                            	   , Transactional_Unit__c
                                                   , Area__c
                                             FROM  QuoteLineItem
                                             WHERE QuoteId IN: syncedQuoteIdSet AND
                                             Type__c = 'Normal' AND Parent_Quote_Line_Item__c = NULL];
        System.debug('lineItemsLst-----'+lineItemsLst);
        List<QuoteLineItem> parentsQLILst = new List<QuoteLineItem>();
        
        for(QuoteLineItem parentsQLIObj : lineItemsLst) {
            QuoteLineItem newQLI = new QuoteLineItem();
            newQLI.UnitPrice = parentsQLIObj.UnitPrice;
            newQLI.QuoteId = quoteId;
            newQLI.Transaction_Type__c = 'Renewal'; 
            newQLI.Start_Date__c = parentsQLIObj.Start_Date__c;
            newQLI.End_Date__c = parentsQLIObj.End_Date__c;
            newQLI.Quantity = parentsQLIObj.Quantity;
            newQLI.Product2Id = parentsQLIObj.Product2Id;
            newQLI.PricebookEntryId = parentsQLIObj.PricebookEntryId;
            newQLI.Transactional_Unit__c = parentsQLIObj.Transactional_Unit__c;
            newQLI.Area__c = parentsQLIObj.Area__c;
            parentsQLILst.add(newQLI);
        }
        
        if(!parentsQLILst.isEmpty()) {
                try{
                    System.debug('parents QLI inserted size=1==='+parentsQLILst.size());
                    insert parentsQLILst;
                    System.debug('parents QLI inserted size===='+parentsQLILst.size());
                    List<Opportunity_Junction__c> oppJuncList = new List<Opportunity_Junction__c>();
                    for(Opportunity childOpp : qualifiedChildOppLst){
                        Opportunity_Junction__c instance = new Opportunity_Junction__c();
                        instance.Name = renewalOppList[0].Name;
                        instance.Opportunity__c = renewalOppId;
                        instance.Opportunity_Lookup__c = childOpp.Id;
                        oppJuncList.add(instance);
                    }
                    Opportunity_Junction__c instance = new Opportunity_Junction__c();
                    instance.Name = renewalOppList[0].Name;
                    instance.Opportunity__c = renewalOppId;
                    instance.Opportunity_Lookup__c = parentOppId;
                    oppJuncList.add(instance);
                    insert oppJuncList;
                    System.debug('oppJuncList---'+oppJuncList);
                }
                catch(Exception e) {
                    System.debug('Exception===='+e.getMessage());
                }
            }
    }
}