src/objects/Charge_Type__c.object
<CustomObject>
    <description>Object used as a setting to obtain Charge Types against different products in the system.</description>
    <label>Charge Type</label>
    <nameField>
        <label>Charge Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment_Term__c.object
<CustomObject>
    <description>Object used to capture Payment Term information, to be used on Quotes.</description>
    <fields>
        <fullName>Number_Of_Payments__c</fullName>
        <label>Number Of Payments</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payment Terms</label>
    <nameField>
        <label>Payment Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Price_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Charge Type</label>
        <referenceTo>Charge_Type__c</referenceTo>
        <relationshipLabel>Price Schedules</relationshipLabel>
        <relationshipName>Price_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Term</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Price Schedules</relationshipLabel>
        <relationshipName>Price_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Price Schedule</label>
    <nameField>
        <label>Price Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Term</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Products (Payment Term)</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Sub_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Sub Category</label>
        <referenceTo>Unit_Sub_Category__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_Of_Payments__c</fullName>
        <label>Number Of Payments</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Sub_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Sub-Category</label>
        <referenceTo>Unit_Sub_Category__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Charge_Type__c</fullName>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rent</fullName>
                </value>
                <value>
                    <fullName>Service Charge</fullName>
                </value>
                <value>
                    <fullName>Grace Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Schedule</label>
        <referenceTo>Price_Schedule__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <description>Object used to store Unit Inventory mastered in Yardi on SF.</description>
    <fields>
        <fullName>Unit_Sub_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Sub Category</label>
        <referenceTo>Unit_Sub_Category__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit_Category__c.object
<CustomObject>
    <description>Object used to capture Unit Categories (to align with Yardi) related to Asset Class.</description>
    <label>Unit Category</label>
    <nameField>
        <label>Unit Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit_Sub_Category__c.object
<CustomObject>
    <description>Object used to capture Unit Sub-Category against Units.</description>
    <fields>
        <fullName>Unit_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Category</label>
        <referenceTo>Unit_Category__c</referenceTo>
        <relationshipLabel>Unit Sub-Categories</relationshipLabel>
        <relationshipName>Unit_Sub_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Sub-Category</label>
    <nameField>
        <label>Unit Sub-Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Sub-Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PricingUtilsQueueable.cls
public class PricingUtilsQueueable implements Queueable {
	Set<Id> quoteLineItemSet = new Set<Id>();
    public PricingUtilsQueueable(Set<Id> quoteLineItemSet){
        this.quoteLineItemSet = quoteLineItemSet;
    }
    public void execute(QueueableContext context) {
         populatePaymentTermOnQuote(quoteLineItemSet);       
    }
    public static void populatePaymentTermOnQuote(Set<Id> quoteLineItemSet) {
        
        Map<Id, Quote> QuoteIdVsNoOfPaymentMap = new Map<Id, Quote>();
        List<QuoteLineItem> lineItemList = [SELECT Id, Price_Schedule__r.Payment_Term__r.Number_Of_Payments__c, QuoteId, 		
												   Product2.Unit__r.Unit_Sub_Category__r.Unit_Category__c
                                            FROM QuoteLineItem 
                                            WHERE Id IN: quoteLineItemSet
                                            AND Price_Schedule__r.Charge_Type__r.Name = 'Rent'
                                            AND Quote.Category__c = null
                                            AND Quote.Number_Of_Payments__c = null
                                           ];
        for(QuoteLineItem lineObj : lineItemList) {
            
            if(!QuoteIdVsNoOfPaymentMap.containsKey(lineObj.QuoteId)) {
            	QuoteIdVsNoOfPaymentMap.put(lineObj.QuoteId, new Quote(Id = lineObj.QuoteId, 
                                                                       Number_Of_Payments__c = lineObj.Price_Schedule__r.Payment_Term__r.Number_Of_Payments__c,
                                                                       Category__c = lineObj.Product2.Unit__r.Unit_Sub_Category__r.Unit_Category__c
                                                                      ));
            }
        }
        
        update (QuoteIdVsNoOfPaymentMap.values());
    }
}