src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ParentCon__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ParentCon</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Leasing Contact</fullName>
                </value>
                <value>
                    <fullName>Licensee Contact</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Agent</fullName>
                </value>
                <value>
                    <fullName>Owner Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Alternate Payee</fullName>
                </value>
                <value>
                    <fullName>Authorized Signatory</fullName>
                </value>
                <value>
                    <fullName>Focal Point</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Finance Manager</fullName>
                </value>
                <value>
                    <fullName>Legal Representative</fullName>
                </value>
                <value>
                    <fullName>Manager Incharge</fullName>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>PRO</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>CollectionTeam</fullName>
                </value>
                <value>
                    <fullName>Licensing Contact</fullName>
                </value>
                <value>
                    <fullName>Individual Shareholder</fullName>
                </value>
                <value>
                    <fullName>Corporate Shareholder</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isSubmit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isSubmit</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Work_Order_Number__c</fullName>
        <label>Work Order Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WorkOrderRejectedCtrlTest.cls
/**
 *  @description Test class for WorkOrderRejectedCTRL
 *
 *  2019-16-08  Vaibhavi Kulkarni
 */

@isTest
public class WorkOrderRejectedCtrlTest {
	/*Common test data to be used in test class*/
    @testsetup
    public static void createData(){
        
        Case c = new Case(Status = 'New');
        insert c;
        
        Account accIns = new Account(Name = 'Test',Phone='1111111');
        insert accIns;
        Contact conIns = new Contact(LastName = 'Test',Email = 'vaibhavi.kulkarni@weare4c.com', isSubmit__c = true, ParentCon__c = true, AccountId= accIns.id ,Type__c = 'Billing;Leasing Contact;Licensee Contact;Manager Incharge');
        insert conIns;
        WorkOrder wo = new WorkOrder(Status = 'New', Description = 'test Description', AccountId = accIns.id, CaseId = c.Id,Work_Order_Number__c = 1);
        insert wo;
        WorkOrder wo1 = new WorkOrder(Status = 'New',Description = 'test Description', AccountId = accIns.id ,CaseId = c.Id,Work_Order_Number__c = 2);
        insert wo1;
        WorkOrder wo2 = new WorkOrder(Status = 'In Progress' ,Description = 'test Description', AccountId = accIns.id, CaseId = c.Id,Work_Order_Number__c =3);
        insert wo2;
        
    }
    
    /*Method to test functionality if the contact gets updated to isSubmit = false after email sending*/
    @isTest
    public static void testPositiveSendMailRejected() {
        List<Contact> conLst = [SELECT Id, isSubmit__c FROM Contact];
        List<WorkOrder> workOrderList = [SELECT Id,AccountId,Status,Description, CaseId, Work_Order_Number__c FROM WorkOrder];
        Test.startTest();
        WorkOrderRejectedCTRL.SendMailRejected(workOrderList);
        Test.stopTest();
        List<Contact> conUpdatedlst = [SELECT Id, isSubmit__c FROM Contact];
        System.assertEquals(conUpdatedlst[0].isSubmit__c, false, 'Assert to check if the contact is updated');
    }
    
    /*Method to test functionality if no contacts are matched with criteria as ParentCon__c = true*/
    @isTest
    public static void testNegativeSendMailRejectedWithNoContacts() {
        Contact conObj = [SELECT Id, isSubmit__c, ParentCon__c FROM Contact];
        conObj.ParentCon__c = false;
        update conObj;
        List<WorkOrder> workOrderList = [SELECT Id,AccountId,Status,Description, CaseId, Work_Order_Number__c FROM WorkOrder];
        Test.startTest();
        WorkOrderRejectedCTRL.SendMailRejected(workOrderList);
        Test.stopTest();
        List<Contact> conUpdatedlst = [SELECT Id, isSubmit__c FROM Contact WHERE ParentCon__c = true];
        System.assertEquals(conUpdatedlst.size(), 0, 'Assert to check contact list is empty');
    }
}