src/objects/DOA_Approver__c.object
<CustomObject>
    <description>Object used to store the DoA Approver Matrix.</description>
    <fields>
        <fullName>Level_1_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Level 1 Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DOA_Approver6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_2_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Level 2 Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DOA_Approver1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_3_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Level 3 Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DOA_Approver2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_4_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Level 4 Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DOA_Approver3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_5_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Level 5 Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DOA_Approver4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_6_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Level 6 Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DOA_Approver5</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DOA Approver</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>DOA Approv Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DOA Approver</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>DOA_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOA Approver</label>
        <referenceTo>DOA_Approver__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_1_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Level 1 Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_2_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Level 2 Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_3_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Level 3 Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_4_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Level 4 Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_5_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Level 5 Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_6_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Level 6 Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Soft_Book__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Soft Book</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Revision__c.object
<CustomObject>
    <description>Object used to track the Quote Revisions to support summaries for multi-year leases.</description>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quote Revisions</relationshipLabel>
        <relationshipName>Quote_Revisions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Revision</label>
    <nameField>
        <displayFormat>REV-{000000}</displayFormat>
        <label>Quote Revision Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Revisions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Quote_Revision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Revision</label>
        <referenceTo>Quote_Revision__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MassDeleteQliController.cls
/*
 * Author : Raza khan(raza.khan@weare4c.com)
 * Dated: 03-07-2018
 * Deacription: This is controller is for lightning quick action for mass deletion of quoteline items for the given quote. 
 * 
 * 
 * */
public class MassDeleteQliController {
    
    @AuraEnabled
    public static String massQuoteLineItemsDelete(Id quoteId)
    {
        String msg = '';
        try{
            Quote q = [Select id , Status,Soft_Book__c , Level_1_Approver__c, Level_2_Approver__c , Level_3_Approver__c , Level_4_Approver__c ,
                       Level_5_Approver__c , Level_6_Approver__c  from Quote where id =:quoteId limit 1 ];
            if(q.status == 'Draft' && !q.Soft_Book__c){
                delete [Select id from QuotelineItem where quoteId =: quoteId];
                delete [SELECT Id, Quote__c, Name FROM Quote_Revision__c where Quote__c =:quoteId];
                
                q.Level_1_Approver__c = null;
                q.Level_2_Approver__c = null;
                q.Level_3_Approver__c = null;
                q.Level_4_Approver__c = null;
                q.Level_5_Approver__c = null;
                q.Level_6_Approver__c = null;
                q.DOA_Approver__c = null;
                update q;
                msg =  'deleted';
            }else{
                msg = 'not deleted';
            }
        }catch(Exception e){
            msg = e.getMessage();
        }
    return msg;
    }
    
    
    
}