src/objects/Document__c.object
<CustomObject>
    <description>Custom object used as a placeholder to associate files with records. This object has a lookup to Account, and the rest of the relationships managed using a Lightning component.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment_Schedule__c.object
<CustomObject>
    <description>Object used to capture the payment schedules against Quote. This will be managed by Yardi and will be pushed to Salesforce.</description>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Payment Schedules</relationshipLabel>
        <relationshipName>Payment_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Payment Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Opportunity.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GenerateCCLDocument.cls
/**
 *  @description Auxiliary functions related to pricing
 *
 *  2019-07-26  Amruta K   Implement calculation of total rates depending on start/end dates
 */
global class GenerateCCLDocument {    
   
    /**
     *  @description Function that create a Document
     * 
     */
    @AuraEnabled
    webservice static String createDocument(Id qouteId) {
               
        List<Quote> qouteLst = 
            [SELECT Id, Status, AccountId, (SELECT Id FROM Payment_Schedules__r)
             FROM Quote
             WHERE Id =: qouteId
             AND Status = 'Approved'];
        
        
		List<Document__c> docLst = new List<Document__c>();
        if(!qouteLst.isEmpty()) {
   
            if(!qouteLst[0].Payment_Schedules__r.isEmpty()) {
                Document__c doc = new Document__c();
                doc.Name = 'Test Provisional Approval Letter ';
                doc.Account__c = qouteLst[0].AccountId;
                doc.Quote__c = qouteId;
                docLst.add(doc);
                insert docLst;
                
                for(Document__c docObj : docLst) {
                    CongaBackground.CongaBackgroundMode(docObj.Id);
                }
                return 'Success';
            }
            else {
                return 'Quote should have one Payment Schedule record to generate CCL document.';
            }
        }
        else {
            return 'Quote should be Approved to generate CCL document.';
        }
    }
}