src/objects/Grace_Period__c.object
<CustomObject>
    <description>Object used to capture additional grace period, against Quotes.</description>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Grace Period</label>
    <nameField>
        <displayFormat>GP-{000000}</displayFormat>
        <label>Grace Period Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grace Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Type__c</fullName>
        <label>Lease Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>land</fullName>
                </value>
                <value>
                    <fullName>office</fullName>
                </value>
                <value>
                    <fullName>retail</fullName>
                </value>
                <value>
                    <fullName>str</fullName>
                </value>
                <value>
                    <fullName>annland</fullName>
                </value>
                <value>
                    <fullName>lhland</fullName>
                </value>
                <value>
                    <fullName>unitsale</fullName>
                </value>
                <value>
                    <fullName>cowork</fullName>
                </value>
                <value>
                    <fullName>PMLA</fullName>
                    <isActive>false</isActive>
                    <label>PMLA</label>
                </value>
                <value>
                    <fullName>PMS</fullName>
                    <isActive>false</isActive>
                    <label>PMS</label>
                </value>
                <value>
                    <fullName>TECOM</fullName>
                    <isActive>false</isActive>
                    <label>TECOM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renew</fullName>
                </value>
                <value>
                    <fullName>Modification</fullName>
                </value>
                <value>
                    <fullName>Contraction</fullName>
                    <isActive>false</isActive>
                    <label>Contraction</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grace_Period_Format__c</fullName>
        <label>Grace Period Format</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>days</fullName>
                </value>
                <value>
                    <fullName>months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period_Mechanism__c</fullName>
        <label>Grace Period Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>initial</fullName>
                </value>
                <value>
                    <fullName>every</fullName>
                </value>
                <value>
                    <fullName>end</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <label>Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Rule__c</fullName>
        <label>Price Rule</label>
        <referenceTo>Price_Rule__c</referenceTo>
        <relationshipLabel>Price Schedules</relationshipLabel>
        <relationshipName>Price_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price Schedule</label>
    <nameField>
        <label>Price Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <formula>Unit__r.Building__r.Business_Park__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Park</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DDA</fullName>
                </value>
                <value>
                    <fullName>AXS</fullName>
                </value>
                <value>
                    <fullName>Parking Cards</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>CCL_Sign_Date__c</fullName>
        <label>CCL Sign Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grace_Period_Mechanism__c</fullName>
        <label>Grace Period Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>initial</fullName>
                </value>
                <value>
                    <fullName>every</fullName>
                </value>
                <value>
                    <fullName>end</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <label>Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <formula>TEXT(Opportunity.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposed_End_Date__c</fullName>
        <label>Proposed End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <label>Proposed Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Downsize</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Revision__c.object
<CustomObject>
    <description>Object used to track the Quote Revisions to support summaries for multi-year leases.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote Revision</label>
    <nameField>
        <displayFormat>REV-{000000}</displayFormat>
        <label>Quote Revision Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Revisions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grace_Period_Format__c</fullName>
        <label>Offered Grace Period Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>days</fullName>
                </value>
                <value>
                    <fullName>months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period_Mechanism__c</fullName>
        <label>Offered Grace Period Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>initial</fullName>
                </value>
                <value>
                    <fullName>every</fullName>
                </value>
                <value>
                    <fullName>end</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <inlineHelpText>If &apos;Offered Grace Period&apos; is blank, the Grace Period listed at the Quote will be used for price calculation.</inlineHelpText>
        <label>Offered Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Schedule</label>
        <referenceTo>Price_Schedule__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Grace Period</fullName>
                </value>
                <value>
                    <fullName>Revision</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rate_Increase_Index__c.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Rate Increase Indexes</relationshipLabel>
        <relationshipName>Rate_Increase_Indexes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Schedule</label>
        <referenceTo>Price_Schedule__c</referenceTo>
        <relationshipLabel>Rate Increase Indexes</relationshipLabel>
        <relationshipName>Rate_Increase_Indexes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Increase Index</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Rate Increase Index Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Increase Indexes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QuoteRevisionCalculationsTest.cls
/**
 * @who		: Sadiq Adesanya <sadiq.adesanya@weare4c.com>
 * @when	: 18/06/2019
 * @what	: Test for QuoteRevisionCalculations
 */
@isTest
public class QuoteRevisionCalculationsTest{
	
    /**
     * @method		: createTestData()
     * @description	: Test setup method to insert all necessary records
     * @return		: N/A
     * @params		: N/A
     */
	@testSetup static void createTestData(){
        Id standardPricebookId = Test.getStandardPricebookId();
        Test.setMock(HttpCalloutMock.class, new DDAIntegrationMock());
		Product2 prod = new Product2(
                Name = 'Product X',
                ProductCode = 'Pro-X',
                IsActive = true);
		insert prod;

		PricebookEntry pbEntry = new PricebookEntry(
                Pricebook2Id = standardPricebookId,
                Product2Id = prod.Id,
                UnitPrice = 100.00,
                IsActive = true);
		insert pbEntry;

		Business_Park__c businessPark = new Business_Park__c();
		insert businessPark;

		Opportunity opportunity = new Opportunity(
                Name='Test O',
                StageName='Prospecting',
                CloseDate=Date.today(),
                Lease_Type__c='office',
                Business_Park__c=businessPark.Id,
                Opportunity_Type__c='New',
                Pricebook2Id=standardPricebookId);
		insert opportunity;

		Price_Rule__c priceRule = new Price_Rule__c(Name='Test PR');
		insert priceRule;

		Price_Schedule__c priceSchedule = new Price_Schedule__c(
                Grace_Period__c=10,
                Name='Test PC',
                Price_Rule__c=priceRule.Id,
				Grace_Period_Mechanism__c = 'initial',
                Grace_Period_Format__c = 'days',
                Transaction_Type__c = 'New',
                Start_Date__c = Date.Today() + 1,
               End_Date__c = Date.Today() + 100
        );
		insert priceSchedule;

        Quote quote = new Quote(
                Name='Test Q',
                OpportunityId=opportunity.Id,
                Type__c = 'New',
                CCL_Sign_Date__c=Date.today(),
                Pricebook2Id=standardPricebookId,
                Grace_Period__c=10,
                Lease_Start_Date__c=Date.today(),
                Lease_End_Date__c=Date.today().addDays(10),
                Proposed_Start_Date__c = System.today(),
                Proposed_End_Date__c = System.today().addYears(3),
            	Grace_Period_Period__c = 'days',
             	Grace_Period_Mechanism__c = 'initial'
                );
		insert quote;


        Quote quote1 = new Quote(
                Name='Test Q1',
                OpportunityId=opportunity.Id,
                Type__c = 'New',
                CCL_Sign_Date__c=Date.today(),
                Pricebook2Id=standardPricebookId,
                Grace_Period__c=10,
                Lease_Start_Date__c=Date.today(),
                Lease_End_Date__c=Date.today().addDays(10),
                Proposed_Start_Date__c = System.today(),
                Proposed_End_Date__c = System.today().addYears(10),
                Grace_Period_Period__c = 'days',
             	Grace_Period_Mechanism__c = 'initial');
		insert quote1;

        Quote_Revision__c quoteRevision = new Quote_Revision__c(Quote__c=quote.Id);
        insert quoteRevision;

        QuoteLineItem quoteLineItem = new QuoteLineItem(
                QuoteId=quote.Id,
                Quantity=1,
                PricebookEntryId=pbEntry.Id,
                Price_Schedule__c=priceSchedule.Id,
                UnitPrice=10,
                Charge_Code__c='Test',
                Area__c=10,
                Transactional_Unit__c='Sqft',
                Best_Rate__c=10,
                Offer_Price__c=10,
                Default_Grace_Period__c=quote.Grace_Period__c,Type__c='Normal',
                Parent_Quote_Line_Item__c = 'unique',
                Quote_Revision__c = quoteRevision.Id,
                Start_Date__c = System.today(),
                End_Date__c = System.today().addYears(3));
        QuoteLineItem quoteLineItem1 = new QuoteLineItem(
                QuoteId=quote1.Id,
                Quantity=1,
                PricebookEntryId=pbEntry.Id,
                Price_Schedule__c=priceSchedule.Id,
                UnitPrice=10,
                Charge_Code__c='Test',
                Area__c=10,
                Transactional_Unit__c='Sqft',
                Best_Rate__c=10,
                Offer_Price__c=10,
                Default_Grace_Period__c=quote.Grace_Period__c,Type__c='Normal',
                Parent_Quote_Line_Item__c = 'testTwo',
                Quote_Revision__c = quoteRevision.Id,
                Start_Date__c = System.today(),
                End_Date__c = System.today().addYears(3));
        QuoteLineItem quoteLineItem2 = new QuoteLineItem(
                QuoteId=quote1.Id,
                Quantity=1,
                PricebookEntryId=pbEntry.Id,
                Price_Schedule__c=priceSchedule.Id,
                UnitPrice=10,
                Charge_Code__c='Test',
                Area__c=10,
                Transactional_Unit__c='Sqft',
                Best_Rate__c=10,
                Offer_Price__c=10,
                Default_Grace_Period__c=quote.Grace_Period__c,Type__c='Normal',
                Parent_Quote_Line_Item__c = 'testTwo',
                Start_Date__c = System.today(),
                Quote_Revision__c = quoteRevision.Id,
                End_Date__c = System.today().addYears(3));


        insert new List<QuoteLineItem> {quotelineItem, quoteLineItem1,quoteLineItem2};
	}
    
    /**
     * @method		: testThreeYearContract()
     * @description	: test method to test  
     * @return		: N/A
     * @params		: N/A
     */
    private static testMethod void testThreeYearContract() {

        // Get all relevant records
        Price_Schedule__c priceSchedule = [SELECT Id FROM Price_Schedule__c WHERE Name='Test PC'];
        Rate_Increase_Index__c rateIncreaseIndex = new Rate_Increase_Index__c(
                Order__c = 1,
                Percent_Increase__c = 0.0,
                Price_Schedule__c = priceSchedule.Id,
                Duration_Years__c = 2);
        Rate_Increase_Index__c rateIncreaseIndex1 = new Rate_Increase_Index__c(
                Order__c = 2,
                Percent_Increase__c = 0.5,
                Price_Schedule__c = priceSchedule.Id,
                Duration_Years__c = 2);
        insert new List<Rate_Increase_Index__c> {rateIncreaseIndex, rateIncreaseIndex1};

        QuoteLineItem updatedLineItem = [SELECT Id, QuoteId, Quantity, PricebookEntryId, Price_Schedule__c, UnitPrice, Charge_Code__c, Area__c,
                                                Transactional_Unit__c, Best_Rate__c, Offer_Price__c, Type__c, Start_Date__c, End_Date__c, Revision_Number__c
                                         FROM QuoteLineItem WHERE Type__c = 'Normal' AND Parent_Quote_Line_Item__c = 'unique'];
        
        // pass line items and run logic
        Test.startTest();
        QuoteRevisionCalculations.generateQuoteRevisions(new List<QuoteLineItem>{updatedLineItem});
        Test.stopTest();
        
		List<QuoteLineItem> insertedLineItems = [SELECT Id,Type__c, Start_Date__c, Offer_Price__c, Total_Offered_Price__c
                                                FROM QuoteLineItem WHERE Type__c = 'Revision' ORDER BY Revision_Number__c ];
        if(!insertedLineItems.isEmpty()) {
            System.debug('insertedLineItems: ' + insertedLineItems.size());
            // Verify expected behaviour
            System.assertEquals(22 ,insertedLineItems.size());
            System.assertEquals(10,insertedLineItems[0].Offer_Price__c);
            System.assertEquals(10,insertedLineItems[1].Offer_Price__c);
        } else {
            System.assert(false, 'Failed to find quote line revisions.');
        }
    }
    
    /**
     * @method		: testSevenYearContract()
     * @description	: test method should insert 
     * @return		: N/A
     * @params		: N/A
     */
    private static testMethod void testSevenYearContract() {
   		Price_Schedule__c priceSchedule = [SELECT Id FROM Price_Schedule__c WHERE Name='Test PC'];
        QuoteLineItem  insertedTestItem = [SELECT Id, QuoteId, Quantity, PricebookEntryId, Price_Schedule__c, UnitPrice, Charge_Code__c, Area__c,
                                            Transactional_Unit__c, Offer_Price__c, Best_Rate__c, Type__c, Start_Date__c, End_Date__c, Revision_Number__c
                                           FROM QuoteLineItem WHERE Type__c = 'Normal' AND Parent_Quote_Line_Item__c = 'testTwo' LIMIT 1];
        Rate_Increase_Index__c rateIncreaseIndex = new Rate_Increase_Index__c(
                Order__c = 1,
                Percent_Increase__c = 0.1,
                Price_Schedule__c = priceSchedule.Id,
                Duration_Years__c = 2);
        Rate_Increase_Index__c rateIncreaseIndex1 = new Rate_Increase_Index__c(
                Order__c = 2,
                Percent_Increase__c = 0.5,
                Price_Schedule__c = priceSchedule.Id,
                Duration_Years__c = 3);
        Rate_Increase_Index__c rateIncreaseIndex2 = new Rate_Increase_Index__c(
                Order__c = 3,
                Percent_Increase__c = 1.00,
                Price_Schedule__c = priceSchedule.Id,
                Duration_Years__c = 2);
        insert new List<Rate_Increase_Index__c> {rateIncreaseIndex, rateIncreaseIndex1, rateIncreaseIndex2};

        Test.startTest();
        QuoteRevisionCalculations.generateQuoteRevisions(new List<QuoteLineItem>{insertedTestItem});
        Test.stopTest();
        
		List<QuoteLineItem> insertedLineItems = [SELECT Id,Type__c, Start_Date__c, Offer_Price__c, Total_Offered_Price__c
                                                FROM QuoteLineItem WHERE Type__c = 'Revision' ORDER BY Revision_Number__c ];
        if(!insertedLineItems.isEmpty()) {
            System.debug('insertedLineItems: ' + insertedLineItems.size());
            // Verify expected behaviour
            System.assertEquals(29 ,insertedLineItems.size());
            System.assertEquals(10,insertedLineItems[0].Offer_Price__c);
            System.assertEquals(10.01,insertedLineItems[1].Offer_Price__c);
            System.assertEquals(10,insertedLineItems[2].Offer_Price__c);
            System.assertEquals(10,insertedLineItems[3].Offer_Price__c);
            System.assertEquals(10,insertedLineItems[4].Offer_Price__c);
            System.assertEquals(10.05,insertedLineItems[5].Offer_Price__c);
            System.assertEquals(10,insertedLineItems[6].Offer_Price__c);
            System.assertEquals(10,insertedLineItems[7].Offer_Price__c);
            System.assertEquals(10,insertedLineItems[8].Offer_Price__c);
        } else {
            System.assert(false, 'Failed to find quote line revisions.');
        }
    }
    
    /**
     * @method		: testQuoteDateChange()
     * @description	: test method should insert 
     * @return		: N/A
     * @params		: N/A
     */
    private static testMethod void testQuoteDateChange() {
        Price_Schedule__c priceSchedule = [SELECT Id FROM Price_Schedule__c WHERE Name='Test PC'];
        Quote quote = [SELECT Id, Proposed_Start_Date__c, Proposed_End_Date__c FROM Quote WHERE Name = 'Test Q1'];
        
        QuoteLineItem  insertedTestItem = [SELECT Id, QuoteId, Quantity, PricebookEntryId, Price_Schedule__c, UnitPrice, Charge_Code__c, Area__c,
                                            Transactional_Unit__c, Offer_Price__c, Best_Rate__c, Type__c, Start_Date__c, End_Date__c, Revision_Number__c, Parent_Quote_Line_Item__c
                                           FROM QuoteLineItem WHERE Type__c = 'Normal' AND Parent_Quote_Line_Item__c = 'testTwo' LIMIT 1];
        Rate_Increase_Index__c rateIncreaseIndex = new Rate_Increase_Index__c(
                Order__c = 1,
                Percent_Increase__c = 0.1,
                Price_Schedule__c = priceSchedule.Id,
                Duration_Years__c = 2);
        Rate_Increase_Index__c rateIncreaseIndex1 = new Rate_Increase_Index__c(
                Order__c = 2,
                Percent_Increase__c = 0.5,
                Price_Schedule__c = priceSchedule.Id,
                Duration_Years__c = 3);
        Rate_Increase_Index__c rateIncreaseIndex2 = new Rate_Increase_Index__c(
                Order__c = 3,
                Percent_Increase__c = 1.00,
                Price_Schedule__c = priceSchedule.Id,
                Duration_Years__c = 2);
        insert new List<Rate_Increase_Index__c> {rateIncreaseIndex, rateIncreaseIndex1, rateIncreaseIndex2};

        QuoteRevisionCalculations.generateQuoteRevisions(new List<QuoteLineItem>{insertedTestItem});
        insertedTestItem.Parent_Quote_Line_Item__c = null;
        update insertedTestItem;
        
		List<QuoteLineItem> insertedLineItems = [SELECT Id,Type__c, Start_Date__c, Offer_Price__c, Total_Offered_Price__c
                                                FROM QuoteLineItem WHERE Type__c = 'Revision' ORDER BY Revision_Number__c ];
        if(!insertedLineItems.isEmpty()) {
            System.debug('insertedLineItems: ' + insertedLineItems.size());
            // Verify expected behaviour
            System.assertEquals(29 ,insertedLineItems.size());
            System.assertEquals(10,insertedLineItems[0].Offer_Price__c);
            System.assertEquals(10.01,insertedLineItems[1].Offer_Price__c);
        } else {
            System.assert(false, 'Failed to find quote line revisions.');
        }
        Quote clonedQuote = quote.clone(true, true, false, false);
        quote.Proposed_End_Date__c = System.today().addYears(6);
        update quote;
        
        quote = [SELECT Id, Proposed_Start_Date__c, Proposed_End_Date__c FROM Quote WHERE Name = 'Test Q1'];
        Test.startTest();
        QuoteRevisionCalculations.handleQuoteUpdate(new Map<Id, Quote>{clonedQuote.Id => clonedQuote}, new Map<Id, Quote>{quote.Id => quote});
        Test.stopTest();
        
        insertedLineItems = [SELECT Id,Type__c, Start_Date__c, Offer_Price__c, Total_Offered_Price__c FROM QuoteLineItem WHERE Type__c = 'Revision' ORDER BY Revision_Number__c ];
        if(!insertedLineItems.isEmpty()) {
            System.debug('insertedLineItems: ' + insertedLineItems.size());
            // Verify expected behaviour
            System.assertEquals(2 ,insertedLineItems.size());
            System.assertEquals(10,insertedLineItems[0].Offer_Price__c);
            System.assertEquals(10,insertedLineItems[1].Offer_Price__c);
            //System.assertEquals(15,insertedLineItems[2].Offer_Price__c);
            //System.assertEquals(15,insertedLineItems[3].Offer_Price__c);
            //System.assertEquals(20,insertedLineItems[4].Offer_Price__c);            
        }

    }

    /*
    * @method rollUpQuoteRevisions
    * @case when inserting a new QuoteLineItem with a QuoteRevision
    * @result expect QuoteRevion's total fields to be updated with the correct values
    */
    private static testMethod void insertQuoteRevisionLineItem() {

        List<Quote_Revision__c> revisions = [SELECT Id, Total_Best_Rate__c, (SELECT Id FROM Quote_Line_Items__r), Total_Offered_Price__c FROM Quote_Revision__c];
        for(Quote_Revision__c revision:revisions){
            if(!revision.Quote_Line_Items__r.isEmpty()){
                System.assertNotEquals(null, (Integer) revision.Total_Best_Rate__c);
                System.assertNotEquals(null, (Integer) revision.Total_Offered_Price__c);
            }
        }
    }

      /*
    * @method rollUpQuoteRevisions
    * @case when updating a new QuoteLineItem with a QuoteRevision
    * @result expect QuoteRevion's total fields to be updated with the correct values
    */
    private static testMethod void updateQuoteRevisionLineItem() {

        List<QuoteLineItem> lineItems = [SELECT Id FROM QuoteLineItem];
        lineItems.get(0).Best_Rate__c = 20;
        lineItems.get(0).Offer_Price__c = 20;
        update lineItems;
        
        List<Quote_Revision__c> revisions = [SELECT Id, Total_Best_Rate__c, (SELECT Id FROM Quote_Line_Items__r), Total_Offered_Price__c FROM Quote_Revision__c];
        for(Quote_Revision__c revision:revisions){
            if(!revision.Quote_Line_Items__r.isEmpty()){
                System.assertEquals(200, (Integer) revision.Total_Best_Rate__c);
                System.assertEquals(200, (Integer) revision.Total_Offered_Price__c);
            }
        }
    }

    private static testMethod void deleteQuoteRevisionLineItem() {

        List<QuoteLineItem> lineItems = [SELECT Id FROM QuoteLineItem];
        delete lineItems.get(0);
        
        List<Quote_Revision__c> revisions = [SELECT Id, Total_Best_Rate__c, (SELECT Id FROM Quote_Line_Items__r), Total_Offered_Price__c FROM Quote_Revision__c];
        for(Quote_Revision__c revision:revisions){
            if(!revision.Quote_Line_Items__r.isEmpty()){
                System.assertEquals(200, (Integer) revision.Total_Best_Rate__c);
                System.assertEquals(200, (Integer) revision.Total_Offered_Price__c);
            }
        }
    }

}