src/objects/Grace_Period__c.object
<CustomObject>
    <description>Object used to capture additional grace period, against Quotes.</description>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Grace Periods</relationshipLabel>
        <relationshipName>Grace_Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Grace Period</label>
    <nameField>
        <displayFormat>GP-{000000}</displayFormat>
        <label>Grace Period Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grace Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment_Schedule__c.object
<CustomObject>
    <description>Object used to capture the payment schedules against Quote. This will be managed by Yardi and will be pushed to Salesforce.</description>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Payment Schedules</relationshipLabel>
        <relationshipName>Payment_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Payment Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Grace_Period_Mechanism__c</fullName>
        <label>Grace Period Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>initial</fullName>
                </value>
                <value>
                    <fullName>every</fullName>
                </value>
                <value>
                    <fullName>end</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period_Period__c</fullName>
        <label>Grace Period (period)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>days</fullName>
                </value>
                <value>
                    <fullName>months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <label>Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Payment Terms</label>
        <referenceTo>Payment_Term__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_End_Date__c</fullName>
        <label>Proposed End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <label>Proposed Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuoteTriggerHelper.cls
/*
 * Created by: Raza khan (raza.khan@weare4c.com)
 * Dated:      29/07/2019
 * Description: This controller is for helper methodd for quote trigger 
 * 
 * 
 * */
public class QuoteTriggerHelper {
    
    public static void isStatusDraft(List<Quote> newList, map<Id, Quote> oldMap)
    {
        List<Id> quoteIds = new List<Id>();
        for(Quote q: newList)
        {
			if(q.status != oldmap.get(q.id).status && (q.status == 'Draft' && oldmap.get(q.id).status == 'Approved' ))
            {
                quoteIds.add(q.id);
            }
        }
        if(!quoteIds.isempty())
        {
            dletePaymentScheule(quoteIds);
        }
    }
    
    public static void dletePaymentScheule(List<Id> quoteIds)
    {
        List<Payment_Schedule__c> pSchedule = [Select id, Quote__c  from Payment_Schedule__c where Quote__c in: quoteIds ];
        if(pSchedule != null)
        {
            delete pSchedule;
        }
    }
    
    // 31/07/2019 - Adeel Ahmad
    // Reinitialize approver fields if certain fields on quetes gets changed
    // 04/08/2019 - Raza khan
    // Update the fields of grace period trigger the DOA 
    public static void reinitializeApprover(List<Quote> newList, map<Id, Quote> oldMap){
        SET<Id> updateableQuoteIds = new SET<Id>();
        for(Quote q: newList){
            if(q.Payment_Terms__c  != oldMap.get(q.Id).Payment_Terms__c ||
               q.Proposed_Start_Date__c != oldMap.get(q.Id).Proposed_Start_Date__c ||
               q.Proposed_End_Date__c  != oldMap.get(q.Id).Proposed_End_Date__c ||
               q.Grace_Period__c  != oldMap.get(q.Id).Grace_Period__c  ||
               q.Grace_Period_Period__c !=  oldMap.get(q.Id).Grace_Period_Period__c ||
               q.Grace_Period_Mechanism__c != oldMap.get(q.Id).Grace_Period_Mechanism__c
              ){
                  updateableQuoteIds.add(q.Id);
              }
        }
        if(updateableQuoteIds.size() > 0){
            DOAUtils.populateApprover(updateableQuoteIds);
        }
    }

}