src/objects/Grace_Period__c.object
<CustomObject>
    <description>Object used to capture additional grace period, against Quotes.</description>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Grace Period</label>
    <nameField>
        <displayFormat>GP-{000000}</displayFormat>
        <label>Grace Period Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grace Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Price_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <label>Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transactional_Unit__c</fullName>
        <label>Transactional Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sq ft</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price Schedule</label>
    <nameField>
        <label>Price Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Additional_GP_Discount_Amount__c</fullName>
        <label>Additional GP Discount Amount</label>
        <summarizedField>QuoteLineItem.Additional_GP_Discount_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>QuoteLineItem.Type__c</field>
            <operation>equals</operation>
            <value>Normal</value>
        </summaryFilterItems>
        <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Default_GP_Discount_Amount__c</fullName>
        <label>Default GP Discount Amount</label>
        <summarizedField>QuoteLineItem.Default_GP_Discount_Amount__c</summarizedField>
        <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Grace_Period_Period__c</fullName>
        <label>Grace Period (period)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>days</fullName>
                </value>
                <value>
                    <fullName>months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <label>Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Proposed_End_Date__c</fullName>
        <label>Proposed End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <label>Proposed Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Downsize</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Additional_GP_Discount_Amount__c</fullName>
        <label>Additional GP Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default_GP_Discount_Amount__c</fullName>
        <label>Default GP Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default_Grace_Period__c</fullName>
        <label>Default Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <inlineHelpText>If &apos;Offered Grace Period&apos; is blank, the Grace Period listed at the Quote will be used for price calculation.</inlineHelpText>
        <label>Offered Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Quote_Line_Item__c</fullName>
        <label>Parent Quote Line Item</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Schedule</label>
        <referenceTo>Price_Schedule__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Offered_Price__c</fullName>
        <label>Total Offered Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transactional_Unit__c</fullName>
        <label>Transactional Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sqft</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Grace Period</fullName>
                </value>
                <value>
                    <fullName>Revision</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuotePriceManagement.cls
public class QuotePriceManagement {

    public static final String TYPE_NORMAL = 'Normal';
    
    /**
    * @method	: handleQuoteUpdate()
    * @description	: Method to handle changes made on the quote object
    * @return	: N/A
    * @params	: oldMap - old quote version
    * newMap - version of quote containing changed values
    */
    public static void handleQuoteUpdate(Map<Id,Quote> oldMap, Map<Id,Quote> newMap) {
        Set<Id> parentQuoteIds = new Set<Id>();
        Map<Id, Quote> parentQuoteCalculationIdsMap = new Map<Id, Quote>();
        for(Quote loopQuote : newMap.values()) {
            if(loopQuote.Proposed_Start_Date__c != oldMap.get(loopQuote.Id).Proposed_Start_Date__c ||
            	loopQuote.Proposed_End_Date__c != oldMap.get(loopQuote.Id).Proposed_End_Date__c) {
            	parentQuoteIds.add(loopQuote.Id);
            }
            if(loopQuote.Grace_Period__c != oldMap.get(loopQuote.Id).Grace_Period__c ||
               loopQuote.Grace_Period_Period__c != oldMap.get(loopQuote.Id).Grace_Period_Period__c) {
               		parentQuoteCalculationIdsMap.put(loopQuote.Id, loopQuote);
            }
        }
        if(!parentQuoteIds.isEmpty()) {
        
            // Get Quote Line Item for related changed Quote to calculate new price rule for them.
            Map<Id, QuoteLineItem> rentLineItemsByIds = new Map<Id, QuoteLineItem>([
                                        SELECT Start_Date__c, Product2Id, Transactional_Unit__c, Transaction_Type__c,
                                        PricebookEntryId, UnitPrice, Area__c, QuoteId, Parent_Quote_Line_Item__c,
                                        End_Date__c, Quote.Proposed_Start_Date__c, Quote.Proposed_End_Date__c, Price_Schedule__c
                                        FROM QuoteLineItem
                                        WHERE QuoteId IN: parentQuoteIds
                                        AND Type__c = :TYPE_NORMAL
                                        AND Parent_Quote_Line_Item__c = null
            ]);
        
            if(!rentLineItemsByIds.isEmpty()) {
                // Delete all quote line items except Rent
                delete [SELECT Id FROM QuoteLineItem WHERE QuoteId IN :parentQuoteIds AND Parent_Quote_Line_Item__c != null AND Type__c = :TYPE_NORMAL];
                
                // Reset Price Schedule on Rent qlis
                for(QuoteLineItem rentLineItem : rentLineItemsByIds.values()) {
                    rentLineItem.Price_Schedule__c = null;
                }
                // Update Rent QLI to assign new price rule with updated values.
                try {
                    update rentLineItemsByIds.values();
                }
                catch(Exception ex) {
                    if(ex.getMessage().contains(System.Label.Rate_Of_Mechanism_Blank_Error)) {
                        throw new RateValidationException(System.Label.Rate_Of_Mechanism_Blank_Error);
                    }
                    else {
                       throw new RateValidationException(ex.getMessage());
                    }
                    
                }
            }
    	}
        
        if(!parentQuoteCalculationIdsMap.isEmpty()) {
            
            calculateGraceDiscountsAmountForQuoteUpdate(parentQuoteCalculationIdsMap);
        }
        
    }
    
    /**
    * @method	: handleQuoteLineItemUpdate()
    * @description	: Method to handle changes made on the quote line item object.
    * @return	: N/A
    * @params	: newMap - New quote version
    *             oldMap - Old Quote Version
    */
    public static void handleQuoteLineItemUpdate(Map<Id, QuoteLineItem> newMap, Map<Id, QuoteLineItem> oldMap) {
        
        List<QuoteLineItem> quoteLineItemList = new List<QuoteLineItem>();
        for(QuoteLineItem qliObj : newMap.values()) {
            if(oldMap.get(qliObj.Id).Price_Schedule__c != null &&
               String.isBlank(qliObj.Price_Schedule__c) &&
               String.isBlank(qliObj.Parent_Quote_Line_Item__c)) {
                quoteLineItemList.add(qliObj);
            }
        }
        
        if(!quoteLineItemList.isEmpty())
            PricingUtils.pricingScheduleRealTimeCalculation(new Map<Id, QuoteLineItem> (quoteLineItemList));
        
    }
    
    /**
    * @method	: handleQuoteLineItemInsert()
    * @description	: Method to handle insert on the quote line item.
    * @return	: N/A
    * @params	: newList - New quote version
    */
    public static void handleQuoteLineItemInsert(List<QuoteLineItem> newList) {
        
        List<QuoteLineItem> quoteLineItemList = new List<QuoteLineItem>();
        for(QuoteLineItem qliObj : newList) {
            if(String.isBlank(qliObj.Price_Schedule__c) &&
               String.isBlank(qliObj.Parent_Quote_Line_Item__c)) {
                quoteLineItemList.add(qliObj);
            }
        }
        
        if(!quoteLineItemList.isEmpty())
            PricingUtils.pricingScheduleRealTimeCalculation(new Map<Id, QuoteLineItem> (quoteLineItemList));
        
    }
    
   /**
    * @method	: handleQuoteLineItemInsert()
    * @description	: Method to handle delete on the quote line item.
    * @return	: N/A
    * @params	: oldMap - old quote version
    */
    public static void handleQuoteLineItemDelete( Map<Id, QuoteLineItem> oldMap) {
        
        Set<Id> quoteLineItemIds = new Set<Id>();
        for (QuoteLineItem item : oldMap.values()) {
			if (item.Type__c == TYPE_NORMAL && item.Parent_Quote_Line_Item__c == null) {
                quoteLineItemIds.add(item.QuoteId);
			}
		}

        if(!quoteLineItemIds.isEmpty()) {
            
             // Get Quote Line Item for related changed Quote to calculate new price rule for them.
            Map<Id, QuoteLineItem> rentLineItemsByIds = new Map<Id, QuoteLineItem>([
                SELECT Start_Date__c, Product2Id, Transactional_Unit__c, Transaction_Type__c,
                PricebookEntryId, UnitPrice, Area__c, QuoteId, Parent_Quote_Line_Item__c,
                End_Date__c, Quote.Proposed_Start_Date__c, Quote.Proposed_End_Date__c, Price_Schedule__c
                FROM QuoteLineItem
                WHERE QuoteId IN: quoteLineItemIds
                AND Type__c = :TYPE_NORMAL
                AND Parent_Quote_Line_Item__c = null
            ]);
            
            if(!rentLineItemsByIds.isEmpty()) {
                // Delete all quote line items except Rent
                delete [SELECT Id FROM QuoteLineItem WHERE QuoteId IN: quoteLineItemIds AND Parent_Quote_Line_Item__c != null AND Type__c = :TYPE_NORMAL];
                
                // Reset Price Schedule on Rent qlis
                for(QuoteLineItem rentLineItem : rentLineItemsByIds.values()) {
                    rentLineItem.Price_Schedule__c = null;
                }
               //Update Rent QLI to assign new price rule with updated values.
               update rentLineItemsByIds.values();
        	}
        }
    }
    
    /**
    * @method	: calculateGraceDiscountsAmountForQuoteUpdate()
    * @description	: Method to calculate discount fields on change in quote record.
    * @return	: N/A
    * @params	: quoteMap - new quote version
    */
    public static void calculateGraceDiscountsAmountForQuoteUpdate(Map<Id, Quote> quoteMap) {
        
        List<QuoteLineItem> quoteLineItemList = [SELECT Id, Total_Offered_Price__c, Price_Schedule__c, Default_Grace_Period__c, QuoteId 
                                                 FROM QuoteLineItem
                                                 WHERE QuoteId IN : quoteMap.keySet()
                                                ];
        
        for(QuoteLineItem qliObj : quoteLineItemList) {

            Decimal defaultGPDiscountAmount = 0.0;
            Decimal additionalGPDiscountAmount = 0.0;
            Quote quoteObj = quoteMap.get(qliObj.QuoteId);
            if(quoteObj.Grace_Period__c == null || qliObj.Total_Offered_Price__c == null || qliObj.Price_Schedule__c == null ||
               quoteObj.Grace_Period__c == 0 || quoteObj.Grace_Period_Period__c == null) {
                defaultGPDiscountAmount = 0.0;
            }
            else if(quoteObj.Grace_Period__c <= qliObj.Default_Grace_Period__c) {
                if(quoteObj.Grace_Period_Period__c.equalsIgnoreCase('days')) {
                    defaultGPDiscountAmount = (qliObj.Total_Offered_Price__c / 365) * quoteObj.Grace_period__c;
                }
                else {
                    defaultGPDiscountAmount = (qliObj.Total_Offered_Price__c / 12) * quoteObj.Grace_period__c;
                }   
            }
            else if(quoteObj.Grace_Period__c >  qliObj.Default_Grace_Period__c) {
                Decimal qliGracePeriod = qliObj.Default_Grace_Period__c != null ? qliObj.Default_Grace_Period__c : 1;
                if(quoteObj.Grace_Period_Period__c.equalsIgnoreCase('days')) {
                    defaultGPDiscountAmount = (qliObj.Total_Offered_Price__c / 365) *  qliGracePeriod;
                    additionalGPDiscountAmount = (qliObj.Total_Offered_Price__c / 365) * (quoteObj.Grace_period__c -  qliGracePeriod);

                }
                else {
                    defaultGPDiscountAmount = (qliObj.Total_Offered_Price__c / 12) *  qliGracePeriod;
                    additionalGPDiscountAmount = (qliObj.Total_Offered_Price__c / 12) * (quoteObj.Grace_period__c -  qliGracePeriod);

                }   
            }
            qliObj.Default_GP_Discount_Amount__c = defaultGPDiscountAmount;
            qliObj.Additional_GP_Discount_Amount__c = additionalGPDiscountAmount;
        }
        update quoteLineItemList;
    }
    
    public class RateValidationException extends Exception{}
}