src/objects/Grace_Period__c.object
<CustomObject>
    <description>Object used to capture additional grace period, against Quotes.</description>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Grace Periods</relationshipLabel>
        <relationshipName>Grace_Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Grace Period</label>
    <nameField>
        <displayFormat>GP-{000000}</displayFormat>
        <label>Grace Period Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grace Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Park</label>
        <referenceTo>Business_Park__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Type__c</fullName>
        <label>Lease Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>land</fullName>
                </value>
                <value>
                    <fullName>office</fullName>
                </value>
                <value>
                    <fullName>retail</fullName>
                </value>
                <value>
                    <fullName>str</fullName>
                </value>
                <value>
                    <fullName>annland</fullName>
                </value>
                <value>
                    <fullName>lhland</fullName>
                </value>
                <value>
                    <fullName>unitsale</fullName>
                </value>
                <value>
                    <fullName>cowork</fullName>
                </value>
                <value>
                    <fullName>PMLA</fullName>
                    <isActive>false</isActive>
                    <label>PMLA</label>
                </value>
                <value>
                    <fullName>PMS</fullName>
                    <isActive>false</isActive>
                    <label>PMS</label>
                </value>
                <value>
                    <fullName>TECOM</fullName>
                    <isActive>false</isActive>
                    <label>TECOM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renew</fullName>
                </value>
                <value>
                    <fullName>Modification</fullName>
                </value>
                <value>
                    <fullName>Contraction</fullName>
                    <isActive>false</isActive>
                    <label>Contraction</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Price_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grace_Period_Format__c</fullName>
        <label>Grace Period Format</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>days</fullName>
                </value>
                <value>
                    <fullName>months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period_Mechanism__c</fullName>
        <label>Grace Period Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>initial</fullName>
                </value>
                <value>
                    <fullName>every</fullName>
                </value>
                <value>
                    <fullName>end</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <label>Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Rule__c</fullName>
        <label>Price Rule</label>
        <referenceTo>Price_Rule__c</referenceTo>
        <relationshipLabel>Price Schedules</relationshipLabel>
        <relationshipName>Price_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price Schedule</label>
    <nameField>
        <label>Price Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Park__c</fullName>
        <formula>Unit__r.Building__r.Business_Park__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Park</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DDA</fullName>
                </value>
                <value>
                    <fullName>AXS</fullName>
                </value>
                <value>
                    <fullName>Parking Cards</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>CCL_Sign_Date__c</fullName>
        <label>CCL Sign Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grace_Period_Mechanism__c</fullName>
        <label>Grace Period Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>initial</fullName>
                </value>
                <value>
                    <fullName>every</fullName>
                </value>
                <value>
                    <fullName>end</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period_Period__c</fullName>
        <label>Grace Period (period)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>days</fullName>
                </value>
                <value>
                    <fullName>months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <label>Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lease_End_Date__c</fullName>
        <label>Lease End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Start_Date__c</fullName>
        <label>Lease Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <formula>TEXT(Opportunity.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposed_End_Date__c</fullName>
        <label>Proposed End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <label>Proposed Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Downsize</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Revision__c.object
<CustomObject>
    <description>Object used to track the Quote Revisions to support summaries for multi-year leases.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote Revision</label>
    <nameField>
        <displayFormat>REV-{000000}</displayFormat>
        <label>Quote Revision Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Revisions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grace_Period_Format__c</fullName>
        <label>Offered Grace Period Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>days</fullName>
                </value>
                <value>
                    <fullName>months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period_Mechanism__c</fullName>
        <label>Offered Grace Period Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>initial</fullName>
                </value>
                <value>
                    <fullName>every</fullName>
                </value>
                <value>
                    <fullName>end</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grace_Period__c</fullName>
        <inlineHelpText>If &apos;Offered Grace Period&apos; is blank, the Grace Period listed at the Quote will be used for price calculation.</inlineHelpText>
        <label>Offered Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Schedule</label>
        <referenceTo>Price_Schedule__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Revision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Revision</label>
        <referenceTo>Quote_Revision__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Grace Period</fullName>
                </value>
                <value>
                    <fullName>Revision</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MassDeleteQliControllerTest.cls
/*
 * Created by : Raza khan (raza.khan@weare4c.com)
 * 
 * Description: this controller is for completing the code coverage of the MassDeleteController
 * 
 * */
@istest
public class MassDeleteQliControllerTest {
    private static Id quoteId;
    /*
     * Method :setupData
     * 
     * Desrciption: it is for setting up the setup data for testing
     * 
     * */
    private static void setupData(){
     Id standardPricebookId = Test.getStandardPricebookId();
		Product2 prod = new Product2(
                Name = 'Product X',
                ProductCode = 'Pro-X',
                IsActive = true);
		insert prod;

		PricebookEntry pbEntry = new PricebookEntry(
                Pricebook2Id = standardPricebookId,
                Product2Id = prod.Id,
                UnitPrice = 100.00,
                IsActive = true);
		insert pbEntry;

		Business_Park__c businessPark = new Business_Park__c();
		insert businessPark;

		Opportunity opportunity = new Opportunity(
                Name='Test O',
                StageName='Prospecting',
                CloseDate=Date.today(),
                Lease_Type__c='office',
                Business_Park__c=businessPark.Id,
                Opportunity_Type__c='New',
                Pricebook2Id=standardPricebookId);
		insert opportunity;

		Price_Rule__c priceRule = new Price_Rule__c(Name='Test PR');
		insert priceRule;

		Price_Schedule__c priceSchedule = new Price_Schedule__c(
                Grace_Period__c=10,Grace_Period_Format__c = 'days', Grace_Period_Mechanism__c = 'end',
                Name='Test PC',Transaction_Type__c = 'New', Start_Date__c = Date.today(), End_Date__c = Date.today() + 10,
                Price_Rule__c=priceRule.Id);
		insert priceSchedule;

        Quote quote = new Quote(
                Name='Test Q',
                OpportunityId=opportunity.Id,
                Type__c = 'New',
                CCL_Sign_Date__c=Date.today(),
                Pricebook2Id=standardPricebookId,
                Grace_Period__c=10,
            	Grace_Period_Period__c = 'days',
            	Grace_Period_Mechanism__c = 'initial',
                Lease_Start_Date__c=Date.today(),
                Lease_End_Date__c=Date.today().addDays(10),
                Proposed_Start_Date__c = System.today(),
                Proposed_End_Date__c = System.today().addYears(3));
		insert quote;
        quoteId = quote.id;


        Quote quote1 = new Quote(
                Name='Test Q1',
                OpportunityId=opportunity.Id,
                Type__c = 'New',
                CCL_Sign_Date__c=Date.today(),
                Pricebook2Id=standardPricebookId,
                Grace_Period__c=10,
            	Grace_Period_Period__c = 'days',
            	Grace_Period_Mechanism__c = 'initial',
                Lease_Start_Date__c=Date.today(),
                Lease_End_Date__c=Date.today().addDays(10),
                Proposed_Start_Date__c = System.today(),
                Proposed_End_Date__c = System.today().addYears(10));
		insert quote1;

        Quote_Revision__c quoteRevision = new Quote_Revision__c(Quote__c=quote.Id);
        insert quoteRevision;

        QuoteLineItem quoteLineItem = new QuoteLineItem(
                QuoteId=quote.Id,
                Quantity=1,
                PricebookEntryId=pbEntry.Id,
                Price_Schedule__c=priceSchedule.Id,
                UnitPrice=10,
                Charge_Code__c='Test',
                Area__c=10,
                Transactional_Unit__c='Sqft',
                Best_Rate__c=10,
                Offer_Price__c=10,
                Default_Grace_Period__c=quote.Grace_Period__c,Type__c='Normal',
                Parent_Quote_Line_Item__c = 'unique',
                Quote_Revision__c = quoteRevision.Id,
                Start_Date__c = System.today(),
                End_Date__c = System.today().addYears(3));
      
       // insert quotelineItem; //new List<QuoteLineItem> {quotelineItem};//, quoteLineItem1,quoteLineItem2};//
            }
    
    /*
     * Method :massDeleteQliTest
     * 
     * Desrciption: it is for testing MassDeleteQliController
     * 
     * */
    @istest
    private static void massDeleteQliTest()
    {
        setupData();
        test.startTest();
        string resp = MassDeleteQliController.massQuoteLineItemsDelete(quoteId);
        Quote q = new Quote(Id =quoteId );
        q.Soft_Book__c = true;
        update q; 
        resp = MassDeleteQliController.massQuoteLineItemsDelete(quoteId);
        
        test.stopTest();
        System.assert(resp != null);
        
    }
}