src/objects/Manage_Price_Revision_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Allow_To_Edit_Best_Rate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow To Edit Best Rate</label>
        <type>Checkbox</type>
    </fields>
    <label>Manage Price Revision Setting</label>
</CustomObject>

src/objects/Price_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transactional_Unit__c</fullName>
        <label>Transactional Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sq ft</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price Schedule</label>
    <nameField>
        <label>Price Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Area_ft__c</fullName>
        <label>Area (ft²)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transaction_Unit__c</fullName>
        <label>Transaction Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>Sqft</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
                <value>
                    <fullName>Bed</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DDA</fullName>
                </value>
                <value>
                    <fullName>AXS</fullName>
                </value>
                <value>
                    <fullName>Parking Cards</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Total_Best_Rate__c</fullName>
        <label>Total Rent Best Rate</label>
        <summarizedField>QuoteLineItem.Total_Best_Rate__c</summarizedField>
        <summaryFilterItems>
            <field>QuoteLineItem.Parent_Quote_Line_Item__c</field>
            <operation>equals</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Downsize</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Revision__c.object
<CustomObject>
    <description>Object used to track the Quote Revisions to support summaries for multi-year leases.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Revision_Number__c</fullName>
        <label>Revision Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Best_Rate__c</fullName>
        <label>Total Best Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Offered_Price__c</fullName>
        <label>Total Offered Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Revision</label>
    <nameField>
        <displayFormat>REV-{000000}</displayFormat>
        <label>Quote Revision Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Revisions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Area_ft__c</fullName>
        <label>Area (ft²)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Best_Rate__c</fullName>
        <label>Best Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DOA_Discount2__c</fullName>
        <formula>Offer_Best_Discount_Amount__c +  Additional_GP_Discount_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DOA Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Default_Grace_Period__c</fullName>
        <label>Default Grace Period</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offer_Price__c</fullName>
        <label>Offer Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PriceSch_ChargeType__c</fullName>
        <formula>Price_Schedule__r.Charge_Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Charge Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Schedule</label>
        <referenceTo>Price_Schedule__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Revision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Revision</label>
        <referenceTo>Quote_Revision__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revision_Number__c</fullName>
        <label>Revision Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Best_Rate__c</fullName>
        <label>Total Best Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Offered_Price__c</fullName>
        <label>Total Offered Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Unit__c</fullName>
        <formula>IF(ISBLANK(TEXT(Transactional_Unit__c)),TEXT(Product2.Transaction_Unit__c),TEXT(Transactional_Unit__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Transaction Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transactional_Unit__c</fullName>
        <label>Transactional Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sqft</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Grace Period</fullName>
                </value>
                <value>
                    <fullName>Revision</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ManagePriceRevisionsController.cls
/************************************************************************************
* Name          : ManagePriceRevisionsController                                                 
* Description   : Controller class for Manage Pricing Revision lightning component
* Created Date  : 19/08/2019                                                   
* Created By    : Amruta Kumbhakarn (amruta.kumbhakarn@weare4c.com)
* Jira/Req By   :                                                                                                                                           
* -----------------------------------------------------------------------------------------------------------------------
* VERSION   Developer   Date        Description     Ticket/Reference    
************************************************************************************/
public class ManagePriceRevisionsController {
    
    /************************************************************************************
    Method      :   getLineItemsDetailsByUnitApx
    Description :   Method to get quote line item group by unit related quote paased.
    Params      :   QuoteId
	Return Type :   Return list of UnitLineItemWrapper class
    Created Date:   19/08/2019
    *************************************************************************************
    */
    @AuraEnabled
    public static List<UnitLineItemWrapper> getLineItemsDetailsByUnitApx(Id quoteId) {
        
        Manage_Price_Revision_Setting__c settingObj = 
            Manage_Price_Revision_Setting__c.getValues(UserInfo.getProfileId());
        Map<Id, List<QuoteLineItem>> productIdVsLineItemListMap = new Map<Id, List<QuoteLineItem>>();
        Map<Id, String> productIdVsNameMap = new Map<Id, String>();
        Map<Id, String> productIdVsAreaMap = new Map<Id, String>();
        Map<Id, List<QuoteLineItem>> revisionIdVsLineItemListMap = new Map<Id, List<QuoteLineItem>>();
        Map<Id, Quote_Revision__c> revisionIdVsRevisionMap = new Map<Id, Quote_Revision__c>();
        List<UnitLineItemWrapper> quoteLineItemList = new List<UnitLineItemWrapper> (); 
        List<RevisionLineItemWrapper> revisionquoteLineItemList = new List<RevisionLineItemWrapper> (); 
        
        for(QuoteLineItem itemObj : [SELECT Id, 
                                     Revision_Number__c, 
                                     Type__c, 
                                     Total_Offered_Price__c, 
                                     Total_Best_Rate__c, 
                                     Best_Rate__c, 
                                     Offer_Price__c, 
                                     DOA_Discount2__c,
                                     Product2Id,
                                     Product2.Name,
                                     Product2.Area_ft__c,
                                     Product2.Transaction_Unit__c,
                                     Start_Date__c, 
                                     End_Date__c, 
                                     Transactional_Unit__c,
                                     Area__c,
                                     PriceSch_ChargeType__c,
                                     Transaction_Unit__c,
                                     Price_Schedule__c,
                                     Default_Grace_Period__c,
                                     QuoteId
                                     FROM QuoteLineItem
                                     WHERE QuoteId =: quoteId
                                     AND IsDeleted = false
                                     Order By Revision_Number__c ASC
                                    ]) {
                                        
            if(productIdVsLineItemListMap.containsKey(itemObj.Product2Id)) {
                productIdVsLineItemListMap.get(itemObj.Product2Id).add(itemObj);
            }
            else {
                 productIdVsLineItemListMap.put(itemObj.Product2Id, new List<QuoteLineItem> {itemObj});
                 productIdVsNameMap.put(itemObj.Product2Id, itemObj.Product2.Name);
                 productIdVsAreaMap.put(itemObj.Product2Id, String.valueOf(itemObj.Product2.Area_ft__c) + ' '+ itemObj.Product2.Transaction_Unit__c);
            }
        }
        for(Id productId : productIdVsLineItemListMap.keySet()) {
            List<QuoteLineItem> lineItemList = productIdVsLineItemListMap.get(productId);
            quoteLineItemList.add(new UnitLineItemWrapper(productIdVsNameMap.get(productId),
                                                          productId,
                                                          productIdVsAreaMap.get(productId),
                                                          lineItemList,
                                                          settingObj != null ? settingObj.Allow_To_Edit_Best_Rate__c : false
                                                         )
                                 );
        }
        
        return quoteLineItemList;
    }
    /************************************************************************************
    Method      :   getLineItemsDetailsByRevisionApx
    Description :   Method to get quote line item group by unit related quote paased.
    Params      :   QuoteId
	Return Type :   Return list of UnitLineItemWrapper class
    Created Date:   19/08/2019
    *************************************************************************************
    */
    @AuraEnabled
    public static List<RevisionLineItemWrapper> getLineItemsDetailsByRevisionApx(Id quoteId) {
        
        Manage_Price_Revision_Setting__c settingObj = 
            Manage_Price_Revision_Setting__c.getValues(UserInfo.getProfileId());
        Map<Id, List<QuoteLineItem>> productIdVsLineItemListMap = new Map<Id, List<QuoteLineItem>>();
        Map<Id, String> productIdVsNameMap = new Map<Id, String>();
        Map<Id, String> productIdVsAreaMap = new Map<Id, String>();
        Map<Id, List<QuoteLineItem>> revisionIdVsLineItemListMap = new Map<Id, List<QuoteLineItem>>();
        Map<Id, Quote_Revision__c> revisionIdVsRevisionMap = new Map<Id, Quote_Revision__c>();
        List<UnitLineItemWrapper> quoteLineItemList = new List<UnitLineItemWrapper> (); 
        List<RevisionLineItemWrapper> revisionquoteLineItemList = new List<RevisionLineItemWrapper> (); 
        
        for(QuoteLineItem itemObj : [SELECT Id, 
                                     Revision_Number__c, 
                                     Type__c, 
                                     Total_Offered_Price__c, 
                                     Total_Best_Rate__c, 
                                     Best_Rate__c, 
                                     Offer_Price__c, 
                                     DOA_Discount2__c,
                                     Product2Id,
                                     Product2.Name,
                                     Product2.Area_ft__c,
                                     Product2.Transaction_Unit__c,
                                     Quote_Revision__c,
                                     Start_Date__c, 
                                     End_Date__c, 
                                     Transactional_Unit__c,
                                     Area__c,
                                     PriceSch_ChargeType__c,
                                     Transaction_Unit__c,
                                     Price_Schedule__c,
                                     Default_Grace_Period__c,
                                     QuoteId
                                     FROM QuoteLineItem
                                     WHERE QuoteId =: quoteId
                                     AND Quote_Revision__c != null
                                     AND IsDeleted = false
                                     Order By Revision_Number__c ASC 
                                    ]) {
                                        
             if(revisionIdVsLineItemListMap.containsKey(itemObj.Quote_Revision__c)) {
                 revisionIdVsLineItemListMap.get(itemObj.Quote_Revision__c).add(itemObj);
             }
             else {
                 revisionIdVsLineItemListMap.put(itemObj.Quote_Revision__c, new List<QuoteLineItem> {itemObj});
             }
        }
        revisionIdVsRevisionMap = new Map<Id, Quote_Revision__c> ([SELECT Id, 
                                                                   		  Start_Date__c,
                                                                          End_Date__c,
                                                                          Total_Offered_Price__c,
                                                                          Revision_Number__c
                                                                   FROM Quote_Revision__c
                                                                   WHERE Id IN: revisionIdVsLineItemListMap.keySet()
                                                                  ]);
        for(Id revisionId : revisionIdVsLineItemListMap.keySet()) {
			
			quoteLineItemList = new List<UnitLineItemWrapper> (); 
			productIdVsLineItemListMap = new Map<Id, List<QuoteLineItem>>();
			
            for(QuoteLineItem itemObj : revisionIdVsLineItemListMap.get(revisionId)) {
				
				if(productIdVsLineItemListMap.containsKey(itemObj.Product2Id)) {
					productIdVsLineItemListMap.get(itemObj.Product2Id).add(itemObj);
				}
				else {
					productIdVsLineItemListMap.put(itemObj.Product2Id, new List<QuoteLineItem> {itemObj});
					productIdVsNameMap.put(itemObj.Product2Id, itemObj.Product2.Name);
					productIdVsAreaMap.put(itemObj.Product2Id, String.valueOf(itemObj.Product2.Area_ft__c) + ' '+ itemObj.Product2.Transaction_Unit__c);
				}
			}
			for(Id productId : productIdVsLineItemListMap.keySet()) {
				List<QuoteLineItem> lineItemList = productIdVsLineItemListMap.get(productId);
				quoteLineItemList.add(new UnitLineItemWrapper(productIdVsNameMap.get(productId),
															  productId,
															  productIdVsAreaMap.get(productId),
															  lineItemList,
                                                              settingObj != null ? settingObj.Allow_To_Edit_Best_Rate__c : false
															 )
									 );
			}
			revisionquoteLineItemList.add(new RevisionLineItemWrapper(revisionIdVsRevisionMap.get(revisionId),
																	  quoteLineItemList
																	 )
										 ); 
        }
        
        return revisionquoteLineItemList;
    }
    
    /**
     *  @description Function that return QLI with updated Total offered price rate
     *  @param  lineItem    lineItem to update
     *  @return LineItem wrapper instance.
     */
    @AuraEnabled
    public static QuoteLineItem getTotalOfferedPrice(QuoteLineItem li) {

        List<QuoteLineItem> itemList  = new List<QuoteLineItem>{li};
        PricingUtils.calculateQuoteLineItemTotals(itemList);
        PricingUtils.calculateGraceDiscountsAmount(itemList);
        return itemList[0];
    }
    @AuraEnabled
    public static String saveLineItemApx(List<QuoteLineItem> quoteLineItemList, List<String> qliToBeUpdatedList) {
        
        List<QuoteLineItem> quoteLineToUpdateList = new List<QuoteLineItem>();
        Set<Id> uniqueIdSet = new Set<Id>();
        String returnStr = '';
        for(QuoteLineItem itemObj : quoteLineItemList) { 
            if(!itemObj.Type__c.equalsIgnoreCase('Grace Period') &&
               !uniqueIdSet.contains(itemObj.Id) &&
                qliToBeUpdatedList.contains(itemObj.Id)) {
                quoteLineToUpdateList.add(itemObj);
                uniqueIdSet.add(itemObj.Id);  
            }
        }
        if(!quoteLineToUpdateList.isEmpty()) {
            try {
                system.debug('I am in-----:'+quoteLineToUpdateList);
                update quoteLineToUpdateList;
                returnStr = 'SUCCESS';
            }
            catch(Exception ex) {
                returnStr = ex.getMessage();
            }
        }
        return returnStr;
    }
    
    public class UnitLineItemWrapper {
        
        @AuraEnabled
        public String productName;
        @AuraEnabled
        public String productId;
        @AuraEnabled
        public String unitArea;
        @AuraEnabled
        public List<QuoteLineItem> lineItemList;
        @AuraEnabled
        public Boolean allowBestRateEdit; 
        
        public UnitLineItemWrapper(String productName,  
                                   String productId, 
                                   String unitArea, 
                                   List<QuoteLineItem> lineItemList, 
                                   Boolean allowBestRateEdit) {
        	
            this.productName = productName;
            this.productId = productId;
            this.unitArea = unitArea;
            this.lineItemList = lineItemList;
            this.allowBestRateEdit = allowBestRateEdit;
        }
    }
    
    public class RevisionLineItemWrapper {
        
        @AuraEnabled
        public Quote_Revision__c revisionObj; 
        @AuraEnabled
        public List<UnitLineItemWrapper> unitLineItemList;

        
        public RevisionLineItemWrapper(Quote_Revision__c revisionObj, 
                                       List<UnitLineItemWrapper> unitLineItemList
                                      ) {
        	
            this.revisionObj = revisionObj;
            this.unitLineItemList = unitLineItemList;
        }
        
    }

}