src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>HSE_Status__c</fullName>
        <label>HSE Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Applicable</fullName>
                </value>
                <value>
                    <fullName>Under Process</fullName>
                </value>
                <value>
                    <fullName>Approved with comments</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Payment_Schedule__c.object
<CustomObject>
    <description>Object used to capture the payment schedules against Quote. This will be managed by Yardi and will be pushed to Salesforce.</description>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Payment Schedules</relationshipLabel>
        <relationshipName>Payment_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Payment Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Turn_Over_Rent__c.object
<CustomObject>
    <description>Object used to store Turn-Over Rent information related to Retail Leases.</description>
    <fields>
        <fullName>BreakPoint_Frequency__c</fullName>
        <label>BreakPoint Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>Annually</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Monthly</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Natural_Breakpoint_Percentage__c</fullName>
        <label>Natural Breakpoint Percentage</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Natural_Breakpoint__c</fullName>
        <label>Natural Breakpoint</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>0</fullName>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Overage_From_Date__c</fullName>
        <label>Overage From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Overage_Offset_Account_Charge_Code_1__c</fullName>
        <label>Overage Offset Account Charge Code 1</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overage_Offset_Type__c</fullName>
        <label>Overage Offset Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Fixed Offset</label>
                </value>
                <value>
                    <fullName>0</fullName>
                    <label>Offset Accounts</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Overage_To_Date__c</fullName>
        <label>Overage To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Turn Over Rents</relationshipLabel>
        <relationshipName>Turn_Over_Rents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retail_Billing_Frequency__c</fullName>
        <label>Retail Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>4</fullName>
                    <label>Annually</label>
                </value>
                <value>
                    <fullName>0</fullName>
                    <label>Monthly</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Retail_End_Date__c</fullName>
        <label>Retail End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Retail_Start_Date__c</fullName>
        <label>Retail Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_End_Of_Year__c</fullName>
        <label>Sales End Of Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>January</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Febrary</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>March</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>April</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>May</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>June</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>July</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>August</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <label>September</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>October</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>November</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <label>December</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Report_Frequency__c</fullName>
        <label>Sales Report Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>4</fullName>
                    <label>Annually</label>
                </value>
                <value>
                    <fullName>0</fullName>
                    <label>Monthly</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>Quarterly</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>SemiAnnually</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Turn Over Rent</label>
    <nameField>
        <displayFormat>TOR-{00000}</displayFormat>
        <label>Turn Over Rent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Turn Over Rents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewRenewLeaseIntegrationTest.cls
/***********************************************************************************************
* Name              : NewRenewLeaseIntegrationTest                                               
* Description       : Test class to test NewRenewLeaseIntegration integration
* Created Date      :                                                                                                                                                    
* ----------------------------------------------------------------------------------------------
* VERSION   Developer   Date        Description     Ticket/Reference                                                                    
************************************************************************************************/
@istest
public class NewRenewLeaseIntegrationTest {
    
    @TestSetup
    private static void setupData()
    {
        PricingUtilsTest.createData();
    }
    
    //Method to test sendLeaseToOIC method
    @istest
    private static void sendNewLeaseTest()
    {
        string response = '{"yardiIntegrationStatus":"Success","yardiIntegrationErrorMessage":"Successfully Imported. SF Lease Status - Approved","opportunityTCode":"t0003396","opportunityAmendmentId":"5383","paymentSchedule":[{"propertyCode":"d3_b05 ","tenantCode":"t0003396","description":"Rental Income - Office","chargeCode":"rntoff ","billedAmount":"10.83","chargeFrom":"2019-07-16","chargeTo":"2019-08-15","quoteId":"0Q0Q0000000TzjBKAS"}]}';
        Test.setMock(HttpCalloutMock.class, new NewRenewLeaseMockResponse(response));
        List<Quote> quotes = [Select id, status, OpportunityId from Quote where name = 'Test Quote'];
        Turn_Over_Rent__c sobj = new Turn_Over_Rent__c(
            Quote__c = quotes[0].id,
            Retail_Start_Date__c = system.today().addDays(-30),   // Retail Start Date
            Retail_End_Date__c =  system.today().addDays(30),    // Retail End Date
            Sales_Report_Frequency__c = '4',            // Sales Report Frequency
            Retail_Billing_Frequency__c = '4',          // Retail Billing Frequency
            BreakPoint_Frequency__c = '4',              // BreakPoint Frequency
            Sales_End_Of_Year__c = '1',                  // Sales End Of Year
            Overage_From_Date__c =  system.today().addDays(30),  // Overage From Date
            Overage_To_Date__c =  system.today().addDays(60),    // Overage To Date
            Natural_Breakpoint__c = '1',                     // Natural Breakpoint
            Natural_Breakpoint_Percentage__c = 15,             // Natural Breakpoint Percentage
            Overage_Offset_Type__c = '1',           // Overage Offset Type
            Overage_Offset_Account_Charge_Code_1__c = '10'    // Overage Offset Account Charge Code 1
        );
        insert sobj;
          
        quotes[0].status = 'Approved';
        update  quotes[0];
        test.startTest();
     
        NewRenewLeaseIntegration.sendLeaseToOIC(new List<Id>{quotes[0].id});
        quotes[0].status = 'Accepted';
        update  quotes[0];
        //NewRenewLeaseIntegration.sendLeaseToOIC(new List<Id>{quotes[0].id});
        test.stopTest();
        
        List<Payment_Schedule__c> paymenySchedulesInserted = [SELECT Id, Name FROM Payment_Schedule__c];
        System.assertEquals(paymenySchedulesInserted.size(),1,'Size of payment schedules');
        
        List<Opportunity> oppLst = [SELECT Id, Name FROM Opportunity];
        List<Quote> quoteLst = [SELECT Id, Name,OpportunityId FROM Quote];
        
        System.assertEquals(oppLst[0].Id, quoteLst[0].OpportunityId);
    }
    
    //Method to test sendHSEStatus method
    @istest
    private static void sendHseStatusTest()
    {
        string response = '{"yardiIntegrationStatus":"Success","yardiIntegrationErrorMessage":"Hse status imported successfully"}';
        Test.setMock(HttpCalloutMock.class, new NewRenewLeaseMockResponse(response));
        List<Opportunity> opportunities = [Select id, HSE_Status__c  from Opportunity where name = 'Test Opp'];
        
        test.startTest();
        opportunities[0].HSE_Status__c = 'Approved';
        update  opportunities[0]; 
        NewRenewLeaseIntegration.hseOpportunityStatus(new List<Id>{opportunities[0].id});
        test.stopTest();
        
        List<Opportunity> updatedOppLst = [Select id, HSE_Status__c  from Opportunity where name = 'Test Opp']; 
        System.assertEquals(updatedOppLst[0].HSE_Status__c, opportunities[0].HSE_Status__c);
    }
    
    //Method to test sendApprovedQuote method
    @istest
    private static void sendApprovedQuotesTest(){
        Map<Id, Quote> quoteIdVsQUoteOldmap = new  Map<Id, Quote>();
        List<Quote> newQuoteList = new List<Quote>();
        List<Quote> quoteList = [SELECT Id, Status FROM Quote WHERE Name = 'Test Quote'];
        
        for(Quote quoteObject :quoteList){
            quoteIdVsQUoteOldmap.put(quoteObject.Id, quoteObject);
            Quote quoteObject2 = quoteObject.clone(true,true);
            quoteObject2.Status = 'Approved';
            newQuoteList.add(quoteObject2);
        }
        
        Test.startTest();
        NewRenewIntegrationIntegrationUtil.sendApprovedQuote(newQuoteList, quoteIdVsQUoteOldmap);
        Test.stopTest();
        
        System.assertNotEquals(newQuoteList, NULL);
        System.assertNotEquals(quoteIdVsQUoteOldmap, NULL);
        System.assertEquals(newQuoteList[0].Status, 'Approved');
    }
    
    //Method to test sendCclSignedQuote method
    @istest
    private static void sendCclSignedQuoteTest(){
        Map<Id, Quote> quoteIdVsQUoteOldmap = new  Map<Id, Quote>();
        List<Quote> newQuoteList = new List<Quote>();
        List<Quote> quoteList = [SELECT Id, Status FROM Quote WHERE Name = 'Test Quote'];
        
        for(Quote quoteObject :quoteList){
            quoteIdVsQUoteOldmap.put(quoteObject.Id, quoteObject);
            Quote quoteObject2 = quoteObject.clone(true,true);
            quoteObject2.Status = 'Accepted';
            newQuoteList.add(quoteObject2);
        }
        
        Test.startTest();
        NewRenewIntegrationIntegrationUtil.sendCclSignedQuote(newQuoteList, quoteIdVsQUoteOldmap);
        Test.stopTest();
        
        System.assertNotEquals(newQuoteList, NULL);
        System.assertNotEquals(quoteIdVsQUoteOldmap, NULL);
        System.assertEquals(newQuoteList[0].Status, 'Accepted');
    }
    
}