src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>HSE_Clearance_Date__c</fullName>
        <label>HSE Clearance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HSE_Status__c</fullName>
        <label>HSE Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Applicable</fullName>
                </value>
                <value>
                    <fullName>Under Process</fullName>
                </value>
                <value>
                    <fullName>Approved with comments</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/NewRenewIntegrationIntegrationUtil.cls
public without sharing class NewRenewIntegrationIntegrationUtil {
    
    public static void sendApprovedQuote(List<Quote> quotes, map<Id, Quote> oldmap)
    {
        List<Id> approvedQuotes = new List<Id>();
        for(Quote q: quotes)
        {
            if(q.status != oldmap.get(q.id).status && q.status == 'Approved')
            {
                approvedQuotes.add(q.id);
            }
        }
        if(!approvedQuotes.isEmpty())
        {
            sendNewLeaseToYardi(approvedQuotes);
        }
    }
    public static void sendCclSignedQuote(List<Quote> quotes, map<Id, Quote> oldmap)
    {
        List<Id> approvedQuotes = new List<Id>();
        for(Quote q: quotes)
        {
            if(q.status != oldmap.get(q.id).status && q.status == 'Accepted')
            {
                approvedQuotes.add(q.id);
            }
        }
        if(!approvedQuotes.isEmpty())
        {
            sendNewLeaseToYardi(approvedQuotes);
        }
    }
    
    public static void sendHSEStatus(List<Opportunity> newOpps, Map<Id,Opportunity> oldmap)
    {
        List<Id> oppIds = new List<Id>();
        for(Opportunity opp: newOpps)
        {
            if(opp.HSE_Status__c  != oldmap.get(opp.id).HSE_Status__c ||
              opp.HSE_Clearance_Date__c  != oldmap.get(opp.id). HSE_Clearance_Date__c )
            {
                oppIds.add(opp.id);
            }
        }
      
        if(!oppIds.isempty())
        {
            sendHseStatusToYardi(oppIds);
        }
        
    }
    
    @future(callout = true)
    public static void sendHseStatusToYardi(List<Id> opportuntyIds ){
        
        NewRenewLeaseIntegration.hseOpportunityStatus(opportuntyIds);
    }
    
    @future(callout=true)
    public static void sendNewLeaseToYardi(List<Id> quoteIds)
    {
        NewRenewLeaseIntegration.sendLeaseToOIC(quoteIds);
    }

}