src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Soft Booked</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                    <isActive>false</isActive>
                    <label>NA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Soft_Book__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Soft Book</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Soft_Booking_Date_Time__c</fullName>
        <label>Soft Booking Date/Time</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <description>Object used to store Unit Inventory mastered in Yardi on SF.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Soft Booked</fullName>
                </value>
                <value>
                    <fullName>Leased</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SoftBookComponentController.cls
/***********************************************************************************************
* Name              : SoftBookComponentController                                                 
* Description       : Controller class for lightning component 'SoftBook'
* Created Date      : 31/07/2019                                                    
* Created By        : Adeel Ahmad (adeel.ahmad@were4c.com)                                                                                                    
* ---------------------------------------------------------------------------------------------- */
public class SoftBookComponentController {
    
    /*
     * 31/07/2019 - Adeel Ahmad
     * Lightning method to do soft booking.
     * Returns list of products2 if already soft booked.
    */
	@AuraEnabled
    public static SoftBookWrapper doSoftBooking(String quoteId){
        SoftBookWrapper wrp = new SoftBookWrapper();
		wrp.isSuccessfull = true;
        Quote quote = [SELECT Id, Soft_Book__c,Opportunity.Id, Opportunity.Probability,Soft_Booking_Date_Time__c FROM Quote WHERE Id=:quoteId];
        LIST<QuoteLineItem> qItems = [SELECT Id,Product2.Id,Product2.Name,Product2.Status__c,Product2.Unit__c,Product2.Unit__r.Status__c FROM QuoteLineItem WHERE QuoteId =:quoteId];
        if(quote.Opportunity.Probability < 50){
            wrp.isSuccessfull = false;
            wrp.validationMessage = 'The Opportunity probability is less than 50%. You can not soft book the products or Unit on this Quote.';
        }else if(quote.Soft_Book__c == true){
            wrp.isSuccessfull = false;
            wrp.validationMessage = 'The Quote has already been soft-booked.';            
        }else{
            if(qItems.size() == 0){
                wrp.isSuccessfull = false;
                wrp.validationMessage = 'Please add Products to be able to Soft-Book the Quote';                            
            }else{
                try{
                    SET<String> alreadyBookedProducts = new SET<String>();
                    for(QuoteLineItem qli : qItems){
                        if(qli.Product2.Status__c == 'Soft Booked'){
                            alreadyBookedProducts.add(qli.Product2.Name);
                        }
                        if(qli.Product2.Unit__r.Status__c == 'Soft Booked'){
                            alreadyBookedProducts.add(qli.Product2.Name);
                        }
                    }
                    if(alreadyBookedProducts.size() > 0){
                        wrp.isSuccessfull = false;
                        wrp.validationMessage = 'Unable to perform action.';     
                        wrp.softBookedItems = new LIST<String>();
                        wrp.softBookedItems.addAll(alreadyBookedProducts);
                    }else{
                        quote.Soft_Book__c = true;
                        quote.Soft_Booking_Date_Time__c = DateTime.now();
                        update quote;                    
                        wrp.isSuccessfull = true;
                        wrp.successMessage = 'Congratulations! The Quote has been Soft-Booked.';                        
                    }
                }catch(Exception e){
                    wrp.isSuccessfull = false;
                	wrp.validationMessage = e.getMessage();
                }
            }
        }
		return wrp;
    }
    
    public class SoftBookWrapper{
        @AuraEnabled public Boolean isSuccessfull {get; set;}
        @AuraEnabled public String validationMessage {get; set;}
        @AuraEnabled public String successMessage {get; set;}
        @AuraEnabled public LIST<String> softBookedItems {get; set;}
    }
}