src/objects/Registration_Request_Status_Setting__mdt.object
<CustomObject>
    <description>This setting is used in license registration request to manage statuses and toolbar.</description>
    <fields>
        <fullName>Legal_Framework__c</fullName>
        <label>Legal Framework</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Move_To_Next_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Move To Next Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Registration Request Status Setting</label>
    <pluralLabel>Registration Request Status Settings</pluralLabel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Assigned_To_RC__c</fullName>
        <label>Assigned To RC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Branch__c</fullName>
        <label>Bank Branch</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <label>Bank</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_For_Review_Reason__c</fullName>
        <label>Call For Review Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDA_Request_Id__c</fullName>
        <externalId>true</externalId>
        <label>DDA Request Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsMovedToNextStep__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Moved To Next Step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Data_Migrated_and_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Data Migrated and Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legal_Framework__c</fullName>
        <formula>TEXT(Account.Legal_Framework__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Legal Framework</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minimum_Required_Share_Capital__c</fullName>
        <label>Minimum Required Share Capital</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skip_Lease_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Skip Lease Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Due__c</fullName>
        <label>Total Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Under_Registration_BU_Sub_Category__c</fullName>
        <label>Under Registration BU Sub Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LicenseRegistrationWebservice.cls
global class LicenseRegistrationWebservice {
    
    global class ServiceRequest{
        webservice String ddaSerReqId;
        webservice String workOrderId;
        webservice String serviceName;
        webservice String status;
        webservice Boolean isDataMigratedLocked;
        webservice String assignedToRCName;
        webservice String busiUnitSubCat;
        webservice Boolean skipLeaseValidation;
        webservice String callForReviewReason;
        webservice Decimal totalAmountDue;
        webservice Decimal minReqShareCapital;
        webservice String bank;
        webservice String bankBranch;
    }
    
    global class RequestResponse{
        webservice Boolean success;
        webservice String errorMessage;
    }
    
    webservice static RequestResponse pushServiceRequestUpdates(List<ServiceRequest> reqs){
        RequestResponse reqRes = new RequestResponse();
        reqRes.success = true;
        reqRes.errorMessage  = '';
        try{
            Set<String> statuses = new Set<String>();
            for(Registration_Request_Status_Setting__mdt rrss : [SELECT Id,Legal_Framework__c,Status__c FROM Registration_Request_Status_Setting__mdt WHERE Move_To_Next_Status__c = TRUE]){
                statuses.add(rrss.Status__c);
            }
            List<WorkOrder> workOrders = new List<WorkOrder>();
            for(ServiceRequest servReq : reqs){
                WorkOrder wo = new WorkOrder();
                wo.Id = servReq.workOrderId;
                wo.DDA_Request_Id__c = servReq.ddaSerReqId;
                wo.Service_Name__c = servReq.serviceName;
                wo.Status = servReq.status;
                wo.Is_Data_Migrated_and_Locked__c = servReq.isDataMigratedLocked;
                wo.Assigned_To_RC__c = servReq.assignedToRCName;
                wo.Under_Registration_BU_Sub_Category__c = servReq.busiUnitSubCat;
                wo.Skip_Lease_Validation__c = servReq.skipLeaseValidation;
                wo.Call_For_Review_Reason__c = servReq.callForReviewReason;
                wo.Total_Amount_Due__c = servReq.totalAmountDue;
                wo.Minimum_Required_Share_Capital__c = servReq.minReqShareCapital;
                wo.Bank__c = servReq.bank;
                wo.Bank_Branch__c = servReq.bankBranch;
                if(statuses.contains(servReq.status)){
                    wo.IsMovedToNextStep__c = false;
                }
                workOrders.add(wo);
            }
            update workOrders;
            return reqRes;
        }catch(Exception ex){
            reqRes.success = false;
            reqRes.errorMessage  = 'Error message :- '+ex.getMessage()+' Stack trace :- '+ex.getStackTraceString();
            return reqRes;
        }
    }
}